type Source = { name: string; url: string; note: string };
type Detail = { updated: string; takeaways: string[]; fitRows: { signal: string; example: string; reason: string }[]; sections: { heading: string; paragraphs: string[] }[]; brief: string[]; faqs: { q: string; a: string }[]; sources: Source[]; related: string[] };

const source: Source = { name: 'U.S. Small Business Administration — Hiring and managing employees', url: 'https://www.sba.gov/business-guide/manage-your-business/hire-and-manage-employees', note: 'Reference for defining responsibilities, access, training, and management boundaries.' };

const topics = [
  ['philippines-outsourced-order-exception-review', 'Review order exceptions with Philippines-based support', 'Separate routine order updates from cases that need an owner decision.', 'order exception review', 'Compare the order record, fulfillment status, customer request, and applicable policy before routing the exception.'],
  ['philippines-support-handoff-context', 'Preserve customer context across support handoffs', 'Keep the facts, promise, next action, and owner together when a case changes hands.', 'support handoff context', 'Write a compact case summary that distinguishes verified facts from customer claims and unresolved questions.'],
  ['philippines-admin-request-intake', 'Design an intake queue for Philippines admin support', 'Turn scattered requests into a visible queue with required context and approval boundaries.', 'admin request intake', 'Require the requester, desired outcome, source record, due date, and approval status before work begins.'],
  ['philippines-vendor-record-check', 'Check vendor records before outsourced follow-up', 'Give follow-up work a source-backed status so staff do not guess at vendor commitments.', 'vendor record checking', 'Reconcile the vendor name, latest contact, open question, expected reply, and evidence link before drafting follow-up.'],
  ['filipino-support-macro-review', 'Review saved support replies before use', 'Keep reusable replies accurate by checking sources, limits, tone, and escalation triggers.', 'support reply review', 'Test each saved reply against a current policy source and mark the cases where a personalized answer is required.'],
  ['philippines-admin-shared-drive-index', 'Build a shared-drive index for admin records', 'Make recurring records findable without broad access or duplicate folders.', 'shared-drive indexing', 'Index the approved location, record owner, naming pattern, status, and access boundary rather than copying files.'],
  ['philippines-ecommerce-returns-prep', 'Prepare ecommerce returns cases for manager review', 'Collect order facts and policy evidence while keeping exceptions with the accountable owner.', 'returns case preparation', 'Present the order timeline, item condition evidence, policy passage, customer request, and decision question in one packet.'],
  ['filipino-calendar-request-rules', 'Set calendar request rules for remote admin support', 'Define what can be scheduled, what needs confirmation, and how time zones are recorded.', 'calendar request handling', 'Record the meeting purpose, participants, time zone, link owner, conflicts, and missing confirmation before sending an invite.'],
  ['philippines-research-source-log', 'Keep a source log for Philippines-based research support', 'Connect each finding to a dated source, the question it answers, and a caveat worth reviewing.', 'research source logging', 'Capture the claim, source title, publication date, retrieval date, relevant passage, and confidence note for every finding.'],
  ['philippines-customer-record-merge-review', 'Review customer record merges with CRM support', 'Use evidence and approval boundaries before combining duplicate customer records.', 'customer record merge review', 'Compare identifying fields, activity history, ownership, and conflicts; flag uncertain matches instead of forcing a merge.'],
  ['outsourced-admin-invoice-exception-queue', 'Create an invoice exception queue for admin support', 'Separate complete invoice preparation from missing evidence and approval decisions.', 'invoice exception handling', 'Label each invoice as ready, missing evidence, conflicting, or awaiting approval and attach the source for the label.'],
  ['philippines-operations-status-board', 'Build an operations status board for remote staff', 'Show current work, blockers, evidence, and owner decisions without confusing activity with completion.', 'operations status boards', 'Give each work item one status, one owner, one next action, and one evidence link that a manager can inspect.'],
  ['filipino-customer-policy-boundaries', 'Define policy boundaries for Filipino customer support', 'Give support staff useful response room while routing exceptions and sensitive commitments to an owner.', 'support policy boundaries', 'List approved actions, prohibited promises, required evidence, and the escalation question for each common request.'],
  ['philippines-admin-missing-file-tracker', 'Track missing files in a Philippines admin queue', 'Make document requests visible with a source, request date, follow-up owner, and stop condition.', 'file request tracking', 'Record exactly what is missing, why it matters, who can supply it, the next follow-up date, and when to escalate.'],
  ['outsourced-order-note-standard', 'Standardize order notes for outsourced support', 'Capture verified facts and next steps so order cases stay understandable after a handoff.', 'order note standards', 'Use a fixed note sequence: customer goal, verified order facts, action taken, open risk, and next owner.'],
  ['philippines-weekly-queue-sample', 'Sample a weekly queue for outsourced labor quality', 'Use a defined sample to see accuracy, completeness, and unresolved exceptions together.', 'weekly queue sampling', 'Select cases across statuses and ages, score the same quality fields, and turn repeated misses into a specific coaching example.'],
  ['filipino-staff-access-review-cycle', 'Run an access review cycle for Philippines staff', 'Compare current duties with permissions and document removals when a role changes.', 'access review cycles', 'Match each permission to a current task, named approver, last review date, and removal trigger.'],
  ['philippines-customer-followup-calendar', 'Schedule customer follow-ups with clear ownership', 'Prevent missed promises by recording verified status, next date, and the person responsible for the update.', 'customer follow-up scheduling', 'Set the next-contact date only after checking the latest case note and identify the owner who can answer the customer.'],
  ['outsourced-operations-backlog-age-review', 'Review backlog age in a remote operations queue', 'Use age, impact, missing inputs, and owner decisions to move stuck work safely.', 'backlog age review', 'Group aging work by the reason it is waiting, then assign the smallest next action that resolves the actual constraint.'],
  ['filipino-training-case-notes', 'Write training case notes for Filipino staff', 'Turn real examples into learning records with the rule, exception, result, and review date.', 'training case documentation', 'Explain what the worker saw, which rule applied, where judgment stopped, and how the approved result was reached.'],
  ['philippines-service-recovery-intake', 'Prepare service recovery cases for owner decisions', 'Give support staff a factual intake without authorizing promises they cannot make.', 'service recovery intake', 'Summarize the customer impact, timeline, prior response, requested remedy, policy context, and decision the owner must make.'],
  ['outsourced-report-source-map', 'Map report fields to their source records', 'Make outsourced reporting easier to trust by showing where each number came from and who reviews it.', 'report source mapping', 'For every reported field, name the source, transformation, refresh point, reviewer, and unresolved limitation.'],
] as const;

export const august13BlogPosts = topics.map(([slug, title, excerpt]) => ({ slug, title, excerpt, minutes: 9 }));

const detail = (topic: string, sentence: string): Omit<Detail, 'updated'> => ({
  takeaways: [sentence, 'Keep decisions about money, policy exceptions, access, deletion, and customer promises with a named owner.', 'Use a small reviewed sample before widening the work lane.'],
  fitRows: [
    { signal: 'Good first scope', example: 'Repeatable records, checks, updates, or drafts', reason: 'The finished output is visible and can be sampled' },
    { signal: 'Needs approval', example: 'Money, policy exceptions, sensitive data, or promises', reason: 'A named owner retains the decision' },
    { signal: 'Stop condition', example: 'Missing source, conflicting record, or unclear instruction', reason: 'The worker can escalate with evidence' },
  ],
  sections: [
    { heading: `Define ${topic} around evidence`, paragraphs: [sentence, `Start with one named input and one finished record for ${topic}. State which source proves each important field, what the ordinary path looks like, and when the worker must pause.`, 'Include an ordinary example and an exception example. That makes the boundary teachable and gives a manager something concrete to review.'] },
    { heading: 'Keep the decision line visible', paragraphs: ['A support contributor can gather facts, organize records, and draft language. The accountable owner should retain decisions involving money, policy exceptions, access, deletion, or unusual customer commitments.', `Mark each ${topic} item ready, waiting for evidence, waiting for approval, or escalated. Pair the status with an owner and a dated next action so it does not become a hiding place for delay.`, 'Use individual access and a written escalation note containing the evidence, question, deadline, and decision owner.'] },
    { heading: 'Review quality through real cases', paragraphs: [`Review ${topic} for accuracy, completeness, timeliness, and handoff usefulness. A fast record with unsupported facts is not a finished record.`, 'Keep one accepted case and one corrected case in the working guidance. Explain the difference in plain language so future work can be compared to an actual standard.', 'Expand the lane only when the sample shows reliable handling of the ordinary path and recognition of exceptions.'] },
  ],
  brief: [`Role goal: Complete the ${topic} lane by the agreed cutoff.`, 'Work source: The named system, queue, report, or folder supplied by the manager.', 'Done means: Required fields are complete, evidence is linked, and the next action is dated.', 'Manager approves: Exceptions involving money, policy, access, deletion, or customer promises.'],
  faqs: [{ q: 'When should the worker pause?', a: 'Pause when the source is missing, the request crosses an approval boundary, or the instructions do not cover the case.' }, { q: 'What should the manager review first?', a: 'Review the source trail, completeness, exception handling, and whether the handoff makes the next decision clear.' }],
  sources: [source], related: ['outsourced-labor-planning', 'philippines-operations-support-sop'],
});

export const august13BlogDetails: Record<string, Detail> = Object.fromEntries(topics.map(([slug, , , , sentence]) => [slug, { updated: '2026-08-13', ...detail(slug.replaceAll('-', ' '), sentence) }]));
