type Source = { name: string; url: string; note: string };
type Detail = { updated: string; takeaways: string[]; fitRows: { signal: string; example: string; reason: string }[]; sections: { heading: string; paragraphs: string[] }[]; brief: string[]; faqs: { q: string; a: string }[]; sources: Source[]; related: string[] };

const sba: Source = { name: 'SBA: Hire and Manage Employees', url: 'https://www.sba.gov/business-guide/manage-your-business/hire-and-manage-employees', note: 'Reference for setting responsibilities, training, and manager expectations.' };
const nist: Source = { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Reference for identifying access and operational risk.' };
const topics = [
  ['philippines-article-brief-qa', 'Build a Philippines article brief QA gate', 'Catch weak briefs before a Philippines-based writer spends time drafting.', 'article brief QA', 'brief completeness', 'Check the reader, decision, evidence standard, outline, internal-link intent, and approval owner before drafting begins.', 'A brief that says “write about staffing” creates avoidable interpretation; a brief that names a buyer question and proof boundary creates reviewable work.'],
  ['filipino-daily-editorial-queue', 'Run a daily editorial queue with Filipino staff', 'Turn article production into visible stages with clear owners, waiting states, and handoffs.', 'daily editorial queues', 'queue design', 'Separate brief-ready, research, drafting, edit, fact review, metadata, approval, and publish-ready states.', 'A daily queue should explain why an item is waiting, not merely show that it is late.'],
  ['outsourced-content-source-register', 'Create a source register for outsourced content research', 'Keep every material claim connected to a source, retrieval context, and editorial decision.', 'content source registers', 'source traceability', 'Record source authority, publication date, retrieval date, claim supported, limitation, and reviewer disposition.', 'Research becomes safer to edit when a reviewer can trace a sentence without reconstructing the researcher’s browser history.'],
  ['philippines-article-outline-review', 'Review article outlines with Philippines-based writers', 'Use an outline review to settle scope, sequence, examples, and role boundaries early.', 'article outline reviews', 'outline calibration', 'Review search intent, reader progression, section purpose, evidence placement, and the conclusion’s practical decision.', 'An outline is a decision map: every heading should earn its place by moving the reader toward a bounded answer.'],
  ['filipino-content-fact-check-handoff', 'Design a fact-check handoff for Filipino content staff', 'Make fact review a structured pass rather than a vague request to “check everything.”', 'content fact-check handoffs', 'fact-check handoffs', 'Pass claims, sources, dates, confidence limits, unresolved wording, and the editor who decides whether a change is needed.', 'Fact checking is most useful when the reviewer receives claims and evidence separately from the writer’s preferred conclusion.'],
  ['outsourced-article-revision-log', 'Keep an article revision log for outsourced labor', 'Make material edits explainable across writers, editors, and approving owners.', 'article revision logs', 'revision history', 'Record changed section, reason, evidence, reviewer, decision, and whether related metadata or links also need review.', 'A revision log preserves editorial reasoning without turning routine copy edits into bureaucracy.'],
  ['philippines-content-calendar-dependencies', 'Map content calendar dependencies with Philippines support', 'Show which briefs, sources, approvals, and assets can delay an article date.', 'content calendar dependencies', 'calendar dependencies', 'Link each publish target to prerequisite inputs, responsible owner, due date, fallback, and escalation point.', 'A calendar date is not a plan until its dependencies and decision owners are visible.'],
  ['filipino-article-metadata-checklist', 'Use a metadata checklist for Filipino article support', 'Protect titles, descriptions, dates, canonical URLs, and structured fields before publishing.', 'article metadata checks', 'metadata quality', 'Verify title alignment, description accuracy, slug identity, visible date, structured date, canonical, and index eligibility.', 'Metadata work is small but consequential: a polished article can still be hard to interpret when its public signals disagree.'],
  ['outsourced-content-internal-link-map', 'Build an internal-link map for outsourced content', 'Help writers connect related articles without creating forced or misleading navigation.', 'internal-link maps', 'contextual linking', 'Map source article, destination purpose, anchor meaning, reader transition, and the point at which a link should be removed.', 'Useful links answer the next natural question; they should not be inserted merely to increase link count.'],
  ['philippines-article-example-library', 'Build an example library for Philippines-based article writers', 'Teach the editorial standard through accepted, corrected, and out-of-scope examples.', 'article example libraries', 'example-based training', 'Pair each example with the reader question, evidence boundary, structural choice, correction reason, and review date.', 'Examples teach judgment better when they explain why a passage works, not just whether a manager accepted it.'],
  ['filipino-editorial-exception-register', 'Keep an editorial exception register with Filipino staff', 'Make unusual claims, sources, and approval questions visible before they become published errors.', 'editorial exception registers', 'exception routing', 'Log the exception, affected article, evidence, risk, decision needed, owner, deadline, and final disposition.', 'An exception register protects the queue from treating unusual work as if it were an ordinary checklist item.'],
  ['outsourced-article-acceptance-standard', 'Define an acceptance standard for outsourced articles', 'Replace subjective “looks good” approval with evidence a writer and editor can use.', 'article acceptance standards', 'acceptance criteria', 'Define required substance, structure, originality, sources, links, metadata, reader usefulness, and unresolved-risk handling.', 'Acceptance is a shared finish line, not a personal preference revealed only after delivery.'],
  ['philippines-research-question-bank', 'Create a research question bank for Philippines content teams', 'Give researchers bounded questions that produce useful evidence instead of broad topic notes.', 'research question banks', 'question design', 'Separate factual questions, comparison questions, implementation questions, risk questions, and questions that require owner judgment.', 'A good research question names the decision it will inform and the evidence that would change the answer.'],
  ['filipino-content-refresh-triggers', 'Set content refresh triggers with Filipino staff', 'Keep published guidance current through explicit signals rather than arbitrary rewrites.', 'content refresh triggers', 'refresh governance', 'Track source changes, dated claims, policy changes, reader confusion, broken links, and known review intervals.', 'Refreshing an article should respond to a reason that can be recorded and reviewed.'],
  ['outsourced-blog-claim-boundaries', 'Set claim boundaries for outsourced blog writing', 'Help writers distinguish useful guidance from unsupported company, market, or outcome claims.', 'blog claim boundaries', 'claim discipline', 'Classify observed facts, general guidance, sourced claims, conditional examples, and statements that require owner approval.', 'A bounded claim can still be practical; it simply tells the reader what is known, assumed, and still dependent on context.'],
  ['philippines-content-review-calendar', 'Plan a content review calendar for Philippines teams', 'Balance review effort across new articles, high-risk pages, and aging guidance.', 'content review calendars', 'review scheduling', 'Rank pages by claim sensitivity, traffic purpose, source age, change likelihood, and reader consequence.', 'A review calendar should prioritize risk and usefulness, not only the date an article was last touched.'],
  ['filipino-article-status-notes', 'Write article status notes for Filipino editorial handoffs', 'Give the next owner a concise, trustworthy picture of what is done and what remains.', 'article status notes', 'editorial handoffs', 'Record stage, completed evidence, open question, blocked input, next action, date, and accountable owner.', 'A status note is successful when the next person can act without asking for the same context again.'],
  ['outsourced-content-duplicate-review', 'Review duplicate content risk in outsourced articles', 'Find overlapping promises, examples, and search intent before two articles compete with each other.', 'content duplicate reviews', 'originality review', 'Compare thesis, audience question, route identity, structure, examples, conclusion, and internal-link destination before approval.', 'Two articles can use different words and still answer the same question; review must compare purpose, not just phrases.'],
  ['philippines-editorial-approval-lane', 'Create an editorial approval lane for Philippines support', 'Route routine article work quickly while reserving high-consequence decisions for an owner.', 'editorial approval lanes', 'approval routing', 'Define what can be checked, edited, scheduled, or approved by role and what requires an accountable editor.', 'An approval lane works when it shortens routine review without disguising unresolved authority.'],
  ['filipino-content-performance-notes', 'Prepare content performance notes with Filipino staff', 'Turn page signals and reader feedback into bounded editorial questions.', 'content performance notes', 'performance interpretation', 'Separate measured page signals, reader comments, plausible explanations, missing evidence, and the next test.', 'A performance note should support a decision without pretending that correlation proves a cause.'],
  ['outsourced-blog-publishing-readiness', 'Run a publishing-readiness review for outsourced blogs', 'Catch route, date, structured data, copy, and navigation issues before an article enters the public queue.', 'publishing-readiness reviews', 'release readiness', 'Verify content, canonical identity, visible and structured dates, family index, sitemap, links, and prohibited claims.', 'Readiness is a cross-functional check: the article and the public record must agree.'],
  ['philippines-content-backlog-triage', 'Triage a content backlog with Philippines-based staff', 'Choose what to research, revise, defer, or retire using reader value and evidence quality.', 'content backlog triage', 'backlog decisions', 'Rank by audience need, business relevance, evidence readiness, freshness risk, effort, and dependency on owner decisions.', 'A backlog becomes manageable when every item has a reason to move, wait, or leave the queue.'],
] as const;

const makeDetail = (topic: typeof topics[number], index: number): Detail => {
  const [slug, title, excerpt, lane, focus, rule, thesis] = topic;
  const source = index % 2 ? nist : sba;
  const stages = ['intake', 'evidence', 'drafting', 'review', 'approval', 'handoff'];
  const sections = [
    { heading: `Start with the decision behind ${lane}`, paragraphs: [`${thesis} For OutsourcedLabor.com’s audience, the useful unit is not “content” in the abstract; it is a repeatable article task with a reader, a business question, a source boundary, and a visible finish line. A Philippines-based contributor can work confidently when those details are written before the item enters the queue.`, `Write the requested outcome in one sentence, then name the evidence that would make the result acceptable. The outcome might be a practical guide, a comparison, a risk explanation, or a checklist. Do not let a broad topic substitute for a decision. If the owner cannot say what the reader should understand or do differently, pause the assignment and return a focused question.`, `Use ${focus} to separate editorial preparation from editorial authority. The contributor can collect material, organize a draft, identify gaps, and propose wording. The accountable owner still decides whether a claim is supportable, whether the page fits the site, and whether an exception deserves publication.`] },
    { heading: 'Make the input inspectable', paragraphs: [`Before work starts, create a compact record for ${lane}: target reader, primary question, intended route, evidence standard, source list, required sections, internal-link purpose, and approving owner. Add a due date only after those inputs exist. A date on an undefined task creates pressure without clarity.`, `Ask the contributor to mark each input as supplied, missing, or questionable. Missing information should name the exact field and the consequence of guessing. A questionable source should include its title, date, retrieval context, and the reason it may not support the intended sentence. This turns a vague blocker into an answerable request.`, `The manager should review the first few records for completeness rather than waiting for a finished article. Early review is where repeated ambiguity is cheapest to remove. If writers keep asking the same question, revise the brief or example library instead of adding another private reminder.`] },
    { heading: `Use a deliberate ${focus} pass`, paragraphs: [`Work through the article in stages: ${stages[(index + 0) % stages.length]}, ${stages[(index + 1) % stages.length]}, ${stages[(index + 2) % stages.length]}, and ${stages[(index + 3) % stages.length]}. Each stage should leave an observable record. A source list without claim mapping is not evidence review; a draft without a reader question is not a finished brief.`, `At the ${stages[(index + 3) % stages.length]} stage, test the thesis against the examples. Does the article actually explain the decision named at intake? Are the examples ordinary enough to teach and specific enough to be useful? Are exceptions identified where a worker or owner could otherwise overreach? Remove a section that cannot answer one of those questions.`, `A practical article can acknowledge uncertainty. Use conditional language when the answer depends on tools, policy, jurisdiction, role authority, or current source material. Record unresolved points for the owner instead of converting them into confident prose. This protects the reader and keeps the work within the agreed role boundary.`] },
    { heading: 'Keep access and authority separate', paragraphs: [`Editorial support often touches shared documents, research sources, publishing fields, and review notes. Give each person a named account and only the access needed for the current lane. A contributor who can prepare a metadata field does not automatically need permission to publish, alter site navigation, or change an approval record.`, `The stop rules should be concrete: conflicting sources, a sensitive claim, a request to invent a result, an unverified testimonial, a public pricing statement, an altered publication date, or a route that overlaps an existing article. The escalation note should include the article, evidence, question, deadline, and person who can decide.`, `Review access when the scope changes and when work ends. Keep an owner for each tool, a record of the permission granted, and a clear removal action. These controls are part of a dependable content routine because they prevent a rushed handoff from becoming an invisible publishing decision.`] },
    { heading: 'Measure the handoff, not just the draft', paragraphs: [`For ${lane}, measure whether the next owner can verify and use the output. Useful checks include brief completeness, source traceability, substantive originality, structural fit, correction rate, and the time an item waits for a decision. Choose a small set that reflects the lane; counting drafts alone rewards activity while hiding rework.`, `Review one accepted item and one corrected item together. Identify the exact difference: missing evidence, unclear reader progression, unsupported language, weak route identity, metadata mismatch, or an approval boundary that was missed. Turn the explanation into an example or instruction that another contributor can apply.`, `Reduce review frequency only after the evidence supports it. A manager can move from full review to a sample when ordinary work is reliable and exceptions are escalated early. If quality falls, restore the earlier check, find the cause, and repair the system rather than blaming the person who followed incomplete guidance.`] },
    { heading: 'Close with a dated next action', paragraphs: [`A finished ${lane} record should state what passed, what remains uncertain, and who owns the next action. Do not close an article because the document has words in it. Close it when the evidence, structure, route identity, dates, links, and approval state match the agreed standard.`, `Use a short handoff note: completed stages, source limitations, material edits, open questions, publication readiness, and the next review date. This is especially important across working hours because the next owner may not share the conversation in which the decision was made.`, `The routine is working when a manager can inspect the record quickly, a writer can learn from the examples, and a reader receives bounded guidance that remains central to Philippines-based staffing decisions. Keep the lane narrow enough to improve, then expand only when the records show that the new responsibility can be taught, checked, and escalated safely.`] },
  ];
  return { updated: '2026-08-19', takeaways: [rule, `Keep ${focus} visible in the article record.`, 'Reserve unsupported claims, sensitive decisions, and publication authority for a named owner.'], fitRows: [{ signal: 'Ready', example: 'Reader, question, evidence, structure, owner', reason: 'The work can be reviewed against a finish line' }, { signal: 'Hold', example: 'Missing source or conflicting instruction', reason: 'Guessing would create rework or risk' }, { signal: 'Escalate', example: 'Sensitive claim or authority exception', reason: 'The accountable owner must decide' }], sections, brief: [`Role goal: Complete the ${lane} lane by the agreed cutoff.`, 'Work source: The named editorial queue, brief, and source register.', 'Done means: Required content fields are complete, evidence is linked, and the next action is dated.', 'Worker may decide: Organization, standard formatting, and checks covered by the approved guidance.', 'Manager approves: Unsupported claims, sensitive topics, publication authority, and process changes.', 'Handoff note: Completed stages, limitations, corrections, open questions, and owner.'], faqs: [{ q: 'When should the contributor pause?', a: 'Pause for missing evidence, conflicting sources, an unclear reader question, a sensitive claim, or a decision outside the written guidance.' }, { q: 'What should the manager review?', a: 'Review the source trail, thesis, originality, exception handling, metadata, and whether the next owner can act from the record.' }, { q: 'When can the lane expand?', a: 'Expand after ordinary cases are accurate, access is controlled, and the review sample shows that exceptions are recognized early.' }], sources: [source], related: ['philippines-content-operations-workflow', 'filipino-research-fact-checking-workflow', 'outsourced-labor-process-improvement-loop'] };
};

export const august19BlogPosts = topics.map(([slug, title, excerpt]) => ({ slug, title, excerpt, minutes: 12 }));
export const august19BlogDetails: Record<string, Detail> = Object.fromEntries(topics.map((topic, index) => [topic[0], makeDetail(topic, index)]));
