type Source = { name: string; url: string; note: string };
type Detail = { updated: string; takeaways: string[]; fitRows: { signal: string; example: string; reason: string }[]; sections: { heading: string; paragraphs: string[] }[]; brief: string[]; faqs: { q: string; a: string }[]; sources: Source[]; related: string[] };

const sba: Source = { name: 'U.S. Small Business Administration — Hire and manage employees', url: 'https://www.sba.gov/business-guide/manage-your-business/hire-and-manage-employees', note: 'Reference for responsibilities, training, and management expectations.' };
const nist: Source = { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Reference for identifying access and operational risk.' };

const topics = [
  ['philippines-outsourced-intake-checklist', 'Build an intake checklist for Philippines-based support', 'Turn incomplete requests into a visible queue with required context and a safe stop rule.', 'support intake', 'Ask for the work object, requested outcome, source record, deadline, and decision owner before assigning the item.', '2026-08-17'],
  ['filipino-admin-recurring-task-register', 'Keep a recurring task register with Filipino admin support', 'Prevent repeat administrative work from disappearing between calendar reminders and inbox threads.', 'recurring task registers', 'Record cadence, trigger, expected output, source, owner, and what happens when the task is late or the source is missing.', '2026-08-17'],
  ['outsourced-labor-approval-evidence', 'Prepare approval evidence for outsourced labor decisions', 'Give managers a compact record for decisions without handing approval authority to the person preparing the case.', 'approval evidence packets', 'Put the request, relevant source, options considered, consequence of waiting, and explicit decision question in one record.', '2026-08-17'],
  ['philippines-customer-record-correction', 'Handle customer record corrections with Philippines-based staff', 'Make corrections traceable by separating the requested change, source proof, and authorized update.', 'customer record corrections', 'Compare the requested value with the authoritative source and preserve the old value, reason, date, and approving owner when the change matters.', '2026-08-17'],
  ['filipino-operations-work-intake-priorities', 'Set intake priorities for Filipino operations staff', 'Convert competing requests into a ranked queue that protects deadlines and owner decisions.', 'operations intake priorities', 'Rank by consequence, deadline, dependency, and reversibility rather than by who sent the loudest message.', '2026-08-17'],
  ['outsourced-support-sensitive-case-boundary', 'Set sensitive-case boundaries for outsourced support', 'Help support staff recognize cases that need a manager before a reply creates a commitment.', 'sensitive support cases', 'Name trigger words, account signals, evidence to collect, and the manager who owns the final response.', '2026-08-17'],
  ['philippines-admin-source-of-truth-map', 'Map sources of truth for Philippines admin work', 'Reduce conflicting spreadsheets and folders by naming which record controls each field.', 'admin source-of-truth mapping', 'For every recurring output, identify the authoritative system, update owner, freshness expectation, and fallback when it is unavailable.', '2026-08-17'],
  ['filipino-research-evidence-handoff', 'Create an evidence handoff for Filipino research staff', 'Make research usable by connecting each finding to a source, date, limitation, and business question.', 'research evidence handoffs', 'Separate observed fact, interpretation, and open question, then attach the exact source and retrieval context for each material finding.', '2026-08-17'],
  ['outsourced-labor-queue-aging-review', 'Review queue aging in outsourced labor operations', 'Show where work is waiting and whether the remedy is capacity, missing evidence, or an owner decision.', 'queue aging reviews', 'Group open items by age and waiting reason, then inspect the oldest case in each group before changing staffing or priority.', '2026-08-17'],
  ['philippines-support-reply-approval-lane', 'Design a reply approval lane for Philippines support', 'Move from drafts to live replies with explicit examples, limits, and review evidence.', 'support reply approval', 'Start with approved reply classes, sample every new class, and escalate any case involving policy, money, identity, or an unusual promise.', '2026-08-17'],
  ['filipino-admin-calendar-access-boundary', 'Set calendar access boundaries for Filipino admin support', 'Share scheduling work while protecting private event details and decisions that belong to the owner.', 'calendar access boundaries', 'Define what can be viewed, edited, invited, or disclosed, including time-zone and confidential-meeting rules.', '2026-08-17'],
  ['outsourced-labor-work-completion-standard', 'Define a completion standard for outsourced labor work', 'Replace vague “done” language with evidence a manager and the next owner can verify.', 'work completion standards', 'State the required fields, source link, status, exception note, and next action that make an item complete.', '2026-08-17'],
  ['philippines-vendor-followup-escalation', 'Set vendor follow-up escalation for Philippines operations', 'Keep supplier dependencies moving without letting staff make unauthorized commitments.', 'vendor follow-up escalation', 'Track request date, promised response, evidence, operational impact, and the point at which an owner must intervene.', '2026-08-17'],
  ['filipino-customer-context-handoff', 'Preserve customer context in Filipino support handoffs', 'Give the next support owner enough verified history to act without rereading private conversations.', 'customer context handoffs', 'Capture the request, verified facts, action already taken, unresolved question, promised next update, and accountable owner.', '2026-08-17'],
  ['outsourced-labor-missing-information-loop', 'Build a missing-information loop for outsourced labor', 'Turn blocked work into a structured request instead of repeated messages and silent assumptions.', 'missing-information loops', 'Name the missing field, why it matters, who can provide it, request date, and fallback or escalation date.', '2026-08-17'],
  ['philippines-admin-report-reconciliation', 'Reconcile admin reports with Philippines-based support', 'Find mismatched totals and stale fields before a manager relies on a weekly report.', 'admin report reconciliation', 'Compare the report to its source population, period, filters, exclusions, and known exceptions before presenting a conclusion.', '2026-08-17'],
  ['filipino-operations-change-request', 'Route process change requests from Filipino operations staff', 'Capture useful improvement ideas while keeping process authority with the owner.', 'operations change requests', 'Record the observed problem, example cases, proposed change, risk, test boundary, and owner decision.', '2026-08-17'],
  ['outsourced-support-case-reopen-rules', 'Set case-reopen rules for outsourced support', 'Keep unresolved customer work visible without reopening every closed item for a minor follow-up.', 'support case reopening', 'Define new evidence, customer response, missed promise, and unresolved outcome as separate reopen reasons with owners.', '2026-08-17'],
  ['philippines-remote-work-contingency-notes', 'Write contingency notes for Philippines remote work', 'Make a disruption response practical by documenting paused work, fallback ownership, and safe recovery.', 'remote-work contingency notes', 'List critical queues, current state, access dependency, backup owner, customer promise at risk, and return-to-normal check.', '2026-08-17'],
  ['filipino-staff-review-calibration', 'Calibrate review standards with Filipino staff', 'Use shared examples to make quality feedback consistent across managers and work lanes.', 'review calibration', 'Compare the same ordinary and exception cases against one rubric, explain the difference, and record the rule that needs clarification.', '2026-08-17'],
  ['outsourced-labor-task-boundary-audit', 'Audit task boundaries before expanding outsourced labor', 'Check whether a new task fits the role’s evidence, access, authority, and review capacity.', 'task boundary audits', 'Compare proposed work with the current SOP, data exposure, consequence, approval line, and manager review time before adding it.', '2026-08-17'],
  ['philippines-content-approval-handoff', 'Set a content approval handoff for Philippines-based support', 'Coordinate briefs, evidence, edits, and owner approval without turning support staff into final publishers.', 'content approval handoffs', 'Pass the brief, audience, source notes, draft status, open questions, metadata, and named approver together.', '2026-08-17'],
] as const;

const detailFor = (topic: string, sentence: string): Omit<Detail, 'updated'> => ({
  takeaways: [sentence, 'Keep authority for money, policy, sensitive access, deletion, and unusual customer promises with a named owner.', 'Review ordinary and exception cases before widening the lane.'],
  fitRows: [
    { signal: 'Good first scope', example: 'Repeatable records, checks, drafts, or routing decisions', reason: 'The result is visible and can be sampled' },
    { signal: 'Manager boundary', example: 'Money, policy exceptions, sensitive data, or commitments', reason: 'The consequence requires accountable approval' },
    { signal: 'Stop condition', example: 'Missing source, conflicting record, or unclear rule', reason: 'The worker can escalate with evidence' },
  ],
  sections: [
    { heading: `Define ${topic} around a finished record`, paragraphs: [sentence, `Start with one ordinary example and one exception for ${topic}. Identify the input, authoritative source, required fields, status, and evidence that proves the item is complete.`, 'Keep the first work lane narrow enough for a manager to review every result and correct the instruction while the examples are still fresh.'] },
    { heading: 'Make the decision boundary explicit', paragraphs: ['Separate preparation from approval. Staff may gather facts, organize records, draft language, and apply an approved rule; an owner retains decisions that change money, policy, access, deletion, or customer commitments.', 'Add a pause rule for missing or contradictory evidence. The escalation note should state what was checked, what remains uncertain, the deadline, and who can decide.', 'Use named accounts and the smallest useful permissions. Review access when the task changes, and document the removal step when the assignment ends.'] },
    { heading: 'Review evidence before adding volume', paragraphs: [`Review ${topic} for accuracy, completeness, timeliness, and handoff usefulness. A fast record without a source trail is not complete.`, 'Keep one accepted case and one corrected case beside the instructions, with the reason the outcomes differ.', 'Expand only when the reviewer can see reliable ordinary handling and early recognition of exceptions.'] },
  ],
  brief: [`Role goal: Complete the ${topic} lane by the agreed cutoff.`, 'Work source: The named queue, system, report, or folder supplied by the manager.', 'Done means: Required fields are present, evidence is linked, and the next action is dated.', 'Manager approves: Money, policy exceptions, sensitive access, deletion, unusual customer promises, and process changes.'],
  faqs: [{ q: 'When should the worker pause?', a: 'Pause when the source is missing, records conflict, the request crosses an approval boundary, or the instruction does not cover the case.' }, { q: 'What should the manager review first?', a: 'Review the source trail, completeness, exception handling, and whether the handoff makes the next decision clear.' }],
  sources: [sba, nist],
  related: ['outsourced-labor-planning', 'philippines-operations-support-sop'],
});

export const august17BlogPosts = topics.map(([slug, title, excerpt]) => ({ slug, title, excerpt, minutes: 10 }));
export const august17BlogDetails: Record<string, Detail> = Object.fromEntries(topics.map(([slug, , , , sentence, updated]) => [slug, { updated, ...detailFor(slug.replaceAll('-', ' '), sentence) }]));
