type Source = { name: string; url: string; note: string };
type Detail = { updated: string; takeaways: string[]; fitRows: { signal: string; example: string; reason: string }[]; sections: { heading: string; paragraphs: string[] }[]; brief: string[]; faqs: { q: string; a: string }[]; sources: Source[]; related: string[] };

const source: Source = { name: 'U.S. Small Business Administration — Hire and manage employees', url: 'https://www.sba.gov/business-guide/manage-your-business/hire-and-manage-employees', note: 'Reference for responsibilities, access, training, and management boundaries.' };
const topics = [
  ['philippines-appointment-confirmation-support', 'Set appointment confirmation support in the Philippines', 'Reduce missed appointments with verified details, clear ownership, and a safe exception path.', 'appointment confirmation support', 'Confirm the attendee, time zone, location or link, latest change, and owner before sending a reminder.'],
  ['outsourced-customer-address-update-review', 'Review customer address updates with outsourced support', 'Keep address changes accurate by separating evidence gathering from approval-sensitive edits.', 'customer address update review', 'Compare the customer request with the existing record and flag conflicting identity or order details before changing anything.'],
  ['filipino-admin-renewal-calendar', 'Build a renewal calendar with Filipino admin support', 'Keep recurring renewals visible with source records, lead times, owners, and approval checkpoints.', 'renewal calendar management', 'Record the contract or account, renewal date, notice window, decision owner, and evidence location for each item.'],
  ['philippines-outsourced-lead-research', 'Scope lead research for Philippines-based support', 'Make list-building useful by defining the target, evidence standard, and disqualification rules.', 'lead research scope', 'Specify the target profile, required fields, source quality, retrieval date, and reason a record belongs in the list.'],
  ['outsourced-support-escalation-packet', 'Prepare escalation packets for outsourced support', 'Give an owner the facts and decision question needed to resolve an exception quickly.', 'support escalation packets', 'Summarize the request, timeline, verified records, prior response, impact, and decision needed without guessing at intent.'],
  ['filipino-admin-contract-index', 'Index contracts with Filipino administrative support', 'Make agreements findable while keeping interpretation and approval with the accountable owner.', 'contract indexing', 'Capture the counterparty, effective dates, renewal terms, storage location, owner, and review trigger from the source document.'],
  ['philippines-inventory-count-reconciliation', 'Reconcile inventory counts with Philippines support', 'Spot record differences with a repeatable comparison that preserves the final adjustment decision.', 'inventory count reconciliation', 'Compare the count date, item identifier, source systems, variance, evidence, and owner decision before recording a correction.'],
  ['outsourced-customer-feedback-summary', 'Summarize customer feedback for outsourced support teams', 'Turn conversations into useful themes without losing the original wording or context.', 'customer feedback summaries', 'Group comments by a small approved category set, link representative cases, and separate observation from interpretation.'],
  ['filipino-admin-travel-records', 'Organize travel records with Filipino admin support', 'Keep itineraries and documents usable while reserving booking, payment, and policy exceptions for an owner.', 'travel record organization', 'Match each trip to traveler, dates, time zones, documents, confirmation status, and the person approving changes.'],
  ['philippines-vendor-question-log', 'Keep a vendor question log for Philippines operations support', 'Prevent supplier questions from disappearing by tracking evidence, promised replies, and next actions.', 'vendor question logs', 'Record the question, source record, date sent, promised response, current owner, and escalation date.'],
  ['outsourced-crm-field-review', 'Review CRM fields with outsourced administrative support', 'Improve record consistency through defined fields, examples, and a clear stop condition.', 'CRM field review', 'Check required fields against source evidence and flag uncertain values instead of filling gaps with assumptions.'],
  ['filipino-support-order-timeline', 'Build order timelines with Filipino support staff', 'Give each order case a readable sequence of requests, actions, status changes, and owners.', 'order timeline preparation', 'Place dated events in source order and label customer statements, verified system events, and unresolved questions separately.'],
  ['philippines-admin-approval-aging', 'Review aging approvals with Philippines admin support', 'Make waiting decisions visible without transferring authority to the person tracking them.', 'approval aging review', 'Show request date, decision needed, evidence, owner, due date, and the smallest follow-up that moves the request forward.'],
  ['outsourced-work-record-retention', 'Organize work-record retention for outsourced teams', 'Keep operational evidence findable with ownership, retention reasons, and access boundaries.', 'work-record retention', 'Classify the record, owner, source location, retention trigger, access group, and approved archive or deletion path.'],
  ['filipino-customer-callback-notes', 'Write customer callback notes with Filipino support', 'Preserve promises and next steps when a customer conversation continues later.', 'customer callback notes', 'Capture the reason for contact, verified facts, commitment made, next update date, and escalation owner.'],
  ['philippines-admin-data-validation', 'Validate admin data before manager reporting', 'Catch missing, stale, or contradictory fields before they become a misleading summary.', 'admin data validation', 'Check required fields, source freshness, duplicate records, outliers, and unresolved limitations before sharing the report.'],
  ['outsourced-service-request-routing', 'Route service requests with outsourced support', 'Send each request to the right owner using visible rules for urgency, evidence, and exceptions.', 'service request routing', 'Classify the request, confirm the destination, attach the source context, and record why an exception was escalated.'],
  ['filipino-operations-daily-handoff', 'Write a daily handoff for Filipino operations staff', 'Make the next shift productive with current status, blockers, evidence, and explicit ownership.', 'daily operations handoffs', 'List completed work, open risks, waiting inputs, next actions, and the owner who can make each pending decision.'],
  ['philippines-ecommerce-product-question-log', 'Log ecommerce product questions with Philippines support', 'Keep product answers accurate by connecting each response to current source information.', 'product question logs', 'Record the customer question, product identifier, source checked, answer boundary, and follow-up needed.'],
  ['outsourced-report-review-notes', 'Write review notes for outsourced reports', 'Turn a report review into actionable corrections, accepted evidence, and an owner for each issue.', 'report review notes', 'Tie every comment to a field or claim, describe the evidence, state the correction, and assign the follow-up owner.'],
  ['filipino-admin-queue-capacity-review', 'Review queue capacity with Filipino admin staff', 'Match incoming work to available attention without hiding urgent work in a single backlog.', 'admin queue capacity review', 'Compare queue age, effort, deadlines, blockers, and available coverage before changing priorities.'],
  ['philippines-outsourced-file-completeness', 'Check file completeness with Philippines-based support', 'Make document packets review-ready by showing what is present, missing, or awaiting approval.', 'file completeness checks', 'Use a required-file list, source links, version dates, missing-item owner, and a clear readiness status.'],
] as const;

export const august14BlogPosts = topics.map(([slug, title, excerpt]) => ({ slug, title, excerpt, minutes: 9 }));
const detail = (topic: string, sentence: string): Omit<Detail, 'updated'> => ({
  takeaways: [sentence, 'Keep money, policy exceptions, access, deletion, and customer promises with a named owner.', 'Review a small set of real cases before widening the work lane.'],
  fitRows: [
    { signal: 'Good first scope', example: 'Repeatable records, checks, updates, or drafts', reason: 'The finished output is visible and can be sampled' },
    { signal: 'Needs approval', example: 'Money, policy exceptions, sensitive data, or promises', reason: 'A named owner retains the decision' },
    { signal: 'Stop condition', example: 'Missing source, conflicting record, or unclear instruction', reason: 'The worker can escalate with evidence' },
  ],
  sections: [
    { heading: `Define ${topic} around evidence`, paragraphs: [sentence, `Start with one named input and one finished record for ${topic}. State which source proves each important field, what the ordinary path looks like, and when the worker must pause.`, 'Include an ordinary example and an exception example so the boundary is teachable and reviewable.'] },
    { heading: 'Keep the decision line visible', paragraphs: ['A support contributor can gather facts, organize records, and draft language. The accountable owner should retain decisions involving money, policy exceptions, access, deletion, or unusual customer commitments.', `Mark each ${topic} item ready, waiting for evidence, waiting for approval, or escalated. Pair the status with an owner and a dated next action.`, 'Use individual access and a written escalation note containing the evidence, question, deadline, and decision owner.'] },
    { heading: 'Review quality through real cases', paragraphs: [`Review ${topic} for accuracy, completeness, timeliness, and handoff usefulness. A fast record with unsupported facts is not finished.`, 'Keep one accepted case and one corrected case in the working guidance, explaining the difference in plain language.', 'Expand the lane only when the sample shows reliable handling of ordinary work and recognition of exceptions.'] },
  ],
  brief: [`Role goal: Complete the ${topic} lane by the agreed cutoff.`, 'Work source: The named system, queue, report, or folder supplied by the manager.', 'Done means: Required fields are complete, evidence is linked, and the next action is dated.', 'Manager approves: Exceptions involving money, policy, access, deletion, or customer promises.'],
  faqs: [{ q: 'When should the worker pause?', a: 'Pause when the source is missing, the request crosses an approval boundary, or the instructions do not cover the case.' }, { q: 'What should the manager review first?', a: 'Review the source trail, completeness, exception handling, and whether the handoff makes the next decision clear.' }],
  sources: [source], related: ['outsourced-labor-planning', 'philippines-operations-support-sop'],
});

export const august14BlogDetails: Record<string, Detail> = Object.fromEntries(topics.map(([slug, , , , sentence]) => [slug, { updated: '2026-08-14', ...detail(slug.replaceAll('-', ' '), sentence) }]));
