import fs from 'node:fs';
import path from 'node:path';
import { Header, Footer, CTA } from './components';

const SITE = 'https://outsourcedlabor.com';
type Article = { title: string; description: string; hero: string; sections: Array<[string, string, string]> };
const article = (title: string, description: string, hero: string, sections: Array<[string,string,string]>): Article => ({title,description,hero,sections});

type Expansion = { lens: string; artifact: string; risk: string; example: string; owner: string; check: string; input: string; boundary: string; handoff: string; review: string };
const expansion: Record<string, Expansion> = {
  'outsourced-labor-daily-article-briefing': { lens:'the daily article briefing', artifact:'a one-page brief with a reader question, evidence limits, and an approval line', risk:'a writer can mistake a broad topic for permission to make a broad claim', example:'a brief about preparing a recurring article queue for a Philippines-based contributor', owner:'the editor who owns public accuracy', check:'the final paragraph answers the exact decision named at intake', input:'the queue, source register, intended audience, and known exceptions', boundary:'drafting authority ends where a company fact, promise, or sensitive interpretation begins', handoff:'the next reviewer receives the brief version, source notes, open questions, and suggested links', review:'which missing field caused the most clarification this week' },
  'philippines-content-source-freshness': { lens:'source-freshness review', artifact:'a source card recording dates, supported claims, change sensitivity, and the next trigger', risk:'an old source can be treated as current simply because its wording sounds confident', example:'a staffing workflow whose access or approval steps may change while the general principle remains useful', owner:'the editor accountable for the article’s evidence boundary', check:'each date-sensitive sentence still has a traceable source and cautious wording', input:'retrieval date, revision signal, claim sensitivity, and reader consequence', boundary:'researchers report what a source says; they do not certify an outcome the source does not measure', handoff:'the review packet identifies unchanged claims, changed claims, and decisions still waiting', review:'whether the trigger list catches meaningful changes before readers do' },
  'filipino-writer-feedback-loop': { lens:'feedback for Filipino article writers', artifact:'a comment record that names the sentence job, edit type, evidence, and requested action', risk:'vague feedback creates several rounds of rewriting without teaching the underlying standard', example:'a paragraph about a remote handoff that needs a missing exception rather than more enthusiasm', owner:'the editor or owner who can resolve a claim question', check:'the writer can explain why a material edit was requested', input:'the brief, draft version, source note, and unresolved decision', boundary:'a writer may flag uncertainty and propose wording but cannot manufacture proof', handoff:'resolved comments remain beside the draft so the next contributor can learn from them', review:'which repeated correction belongs in the brief or example library' },
  'outsourced-blog-research-queue': { lens:'an outsourced blog research queue', artifact:'a queue card with question, thesis, source standard, state, owner, and finish condition', risk:'a long list of topics can hide that no one has defined what the research must decide', example:'a question about how a Philippines staffing team should document a recurring content task', owner:'the person responsible for deciding consequential public claims', check:'evidence-ready items contain claim-level notes rather than a pile of links', input:'reader question, route identity, source access, and role boundary', boundary:'research can prepare options but cannot approve commitments or sensitive interpretations', handoff:'the receiving writer sees the useful evidence and the limits without reopening the whole queue', review:'where items wait longest and whether that wait is correctly labeled' },
  'philippines-article-refresh-review': { lens:'a refresh review for Philippines staffing guidance', artifact:'a change record connecting the trigger, old wording, new evidence, and approval', risk:'a routine update can silently change the article’s promise or publication history', example:'a broken source link that reveals one instruction needs review while the article thesis remains sound', owner:'the editor who approves material changes', check:'the refreshed page retains a recognizable question and truthful date', input:'trigger, affected claims, source comparison, links, and unresolved limits', boundary:'refresh work does not turn an old route into a new claim or a new article', handoff:'the reviewer gets a section-by-section change list and a reason for every deletion', review:'whether the trigger justified the edit or merely created an opportunity to add filler' },
  'filipino-content-escalation-map': { lens:'an escalation map for Filipino content support', artifact:'a route showing routine work, triggers, evidence to attach, and accountable decision roles', risk:'contributors either escalate everything or continue past a boundary because the route is unclear', example:'a source conflict involving a public statement about a staffing workflow', owner:'the accountable owner for policy, proof, or publication decisions', check:'a worker can identify both the next safe action and the point to pause', input:'ordinary task definition, exception trigger, queue state, and fallback owner', boundary:'escalation transfers a question with context; it does not transfer accountability to the writer', handoff:'the receiving owner sees the disputed source, reader consequence, and proposed safe options', review:'whether resolved exceptions are being converted into clearer instructions' },
  'outsourced-labor-content-brief-archive': { lens:'an archive of outsourced content briefs', artifact:'a decision record holding thesis, evidence limits, rejected approaches, and route identity', risk:'future writers can copy an old article when they should learn from its reasoning', example:'two staffing articles that share a work lane but answer different buyer questions', owner:'the editorial owner who decides whether overlap is material', check:'a new brief has a distinct question, structure, examples, and conclusion', input:'reader, lane, prior decision, source notes, and review trigger', boundary:'archival context informs a new draft but is not permission to reuse public copy', handoff:'retrieval results include limitations and unresolved decisions, not just a convenient template', review:'whether the archive reduces repeated confusion without narrowing originality' },
  'philippines-blog-reader-intent': { lens:'reader intent in Philippines staffing guidance', artifact:'a decision path from search question through scope, evidence, controls, and next step', risk:'an article can match a keyword while failing to help the reader choose or prepare anything', example:'a manager asking how to prepare a recurring admin or content queue for remote support', owner:'the editor who checks that recommendations remain bounded', check:'the conclusion returns to the original decision rather than making a generic invitation', input:'starting state, desired decision, constraints, source standard, and role line', boundary:'helpful guidance does not imply a guaranteed result, universal benchmark, or company-specific fact', handoff:'the draft records what the reader can test and what requires an owner decision', review:'whether examples clarify the decision or merely repeat the search phrase' },
  'filipino-article-proof-boundaries': { lens:'proof boundaries for Filipino article production', artifact:'a claim ledger classifying facts, guidance, examples, and statements needing owner evidence', risk:'a polished sentence can quietly overstate what the available source proves', example:'a remote worker describing a control without claiming that the control produced a measured outcome', owner:'the accountable owner for sensitive or company-specific assertions', check:'major edits are followed by a fresh claim review', input:'sentence purpose, source, confidence, reader action, and escalation status', boundary:'filling an evidence gap with invented history, credentials, testimonials, or outcomes is prohibited', handoff:'the editor receives both the proposed copy and the reason a claim is bounded', review:'which unsupported-claim corrections repeat because the brief is underspecified' },
  'outsourced-content-handoff-window': { lens:'a handoff window for outsourced content', artifact:'a transfer note with state, completed work, sources, blockers, authority, and next action', risk:'work crosses time zones while the receiving person lacks the context needed to review it safely', example:'a Philippines-based contributor finishing research while an editor begins the publication review', owner:'the named owner of approval and public accuracy', check:'the receiver can accept, return, or escalate without searching private messages', input:'route, version, source limits, material edits, open questions, and due point', boundary:'handoff is not approval and a contributor cannot infer authority from silence', handoff:'the short acceptance response records whether work was received for review or returned', review:'which missing handoff field caused avoidable delay or rework' },
  'philippines-content-calendar-recovery': { lens:'calendar recovery for Philippines content work', artifact:'a recovery board showing factual readiness, dependencies, consequence, owner, and next date', risk:'a missed date can pressure a team to hide uncertainty or alter an existing record', example:'a delayed article waiting for source confirmation, image assignment, or owner review', owner:'the person who can reorder work and accept a bounded next step', check:'each restored date corresponds to evidence rather than optimism', input:'brief, research, draft, metadata, asset, review status, and delay reason', boundary:'recovery never re-dates old work or turns a changed premise into a forced refresh', handoff:'the next contributor sees what is ready, what is blocked, and what must not be assumed', review:'whether the smaller restart promise is actually repeatable' },
  'outsourced-labor-editorial-retrospective': { lens:'an editorial retrospective for outsourced labor content', artifact:'a short record of observed patterns, hypotheses, one repair, owner, and test evidence', risk:'a meeting can produce blame or a long wish list instead of a change that can be evaluated', example:'repeated rework caused by unclear source limits in articles about Philippines-based staffing', owner:'the manager who can authorize a process change', check:'the next review compares the change with an observed baseline', input:'briefs, source registers, drafts, correction themes, waits, and handoffs', boundary:'the retrospective cannot claim improved results without measured support', handoff:'the chosen repair is written where the people doing the work will encounter it', review:'whether the intervention addressed the observed cause rather than its most visible symptom' }
};

export const articles: Record<string, Article> = {
  'outsourced-labor-daily-article-briefing': article('Run a daily article briefing for outsourced content teams','A practical daily briefing routine for keeping Philippines-based article work focused, sourced, and reviewable.','/aug20-heroes/outsourced-labor-daily-article-briefing.webp',[
    ['Begin with the reader decision','A daily briefing is useful when it names the decision a reader is trying to make. “Write about outsourcing” is a subject, not an assignment. A stronger brief says whether the reader needs to choose a work lane, prepare an intake queue, protect customer context, or decide where an owner must remain involved. That distinction keeps a Philippines-based writer from filling space with general advice.','Write the intended reader, the question, and the consequence of a weak answer at the top of the record. The consequence might be rework, an unsafe promise, a stale process, or a confused buyer. The writer can then select examples that explain the decision instead of decorating it.'],
    ['Set the evidence boundary','Give the writer a source list and say what each source is allowed to support. A public standard may frame a control, while a company record may establish a current process. Neither should be stretched into proof of a result that has not been measured. Mark facts, guidance, examples, and open questions separately.','For outsourced labor topics, the evidence boundary matters because readers are making operating decisions. A briefing can ask for a sourced explanation of access review without claiming that a particular team reduced risk. The owner approves sensitive claims and any statement about outcomes, credentials, locations, or customers.'],
    ['Make the outline executable','A good outline gives each heading a job. One section may define the work lane, another may show the input record, and another may explain an escalation. Ask the writer to put the example beside the rule it illustrates. This makes the draft easier to check and stops the conclusion from introducing a new promise.','Include the intended internal link and its purpose. A link should answer the next natural question, such as how to document an SOP after a role is scoped. It should not be inserted just to increase count.'],
    ['Design the handoff','The writer’s handoff should include the brief version, sources consulted, unresolved questions, and a short note about changes from the outline. The editor should not have to reconstruct why a section exists. If a source was unavailable, say so and identify the sentence affected.','Keep publication authority separate from drafting. A contributor can prepare the article, metadata proposal, and link map; a named owner decides whether the copy is accurate, within scope, and ready to publish.'],
    ['Use a closing test','At the end of the day, compare the draft with the original reader decision. Check that the body answers it, examples stay tied to Philippines-based staffing, and exceptions are visible. Count substantive words after removing headings and navigation.','Record one next action with an owner and date. The routine is working when a manager can review the record quickly and the writer can start tomorrow without repeating the same questions.']
  ]),
  'philippines-content-source-freshness': article('Keep source freshness visible in Philippines content research','How content teams can track source age, change risk, and review triggers without making unsupported freshness claims.','/aug20-heroes/philippines-content-source-freshness.webp',[
    ['Treat source age as a risk signal','A source’s publication date is not a verdict on its usefulness. Some principles remain stable while procedures, product details, and rules change quickly. A Philippines-based researcher should record publication date, retrieval date, source owner, and the part of the article the source supports. That gives an editor something more useful than a vague label such as current.','Classify claims by change sensitivity. A general workflow principle may need periodic review, while an access instruction or legal statement needs a much tighter check. The content brief should tell the researcher which category applies before research begins.'],
    ['Build a review trigger','A freshness routine needs a reason to revisit a source. Triggers can include a broken link, a changed policy page, a reader question that exposes ambiguity, a dated statistic, or a source owner publishing a revision. Record the trigger with the article rather than silently replacing prose.','When a trigger appears, compare the old claim, the new source, and the decision the reader might make from the sentence. This prevents a cosmetic refresh from hiding a material change to role boundaries or access guidance.'],
    ['Separate retrieval from interpretation','Researchers can retrieve and summarize evidence; they should not turn an uncertain source into a confident company claim. Keep notes for observed fact, interpretation, and unresolved question in separate fields. Include enough context for an editor to find the exact source again.','This separation is especially useful when outsourcing article research. A worker can flag that a source is ambiguous or stale and propose a cautious rewrite. The accountable editor decides whether the claim remains, changes, or is removed.'],
    ['Prioritize the queue','Do not refresh every source on the same schedule. Rank work by claim sensitivity, likelihood of change, reader consequence, and how central the source is to the thesis. A source supporting a minor example can wait behind one supporting an access or approval boundary.','A visible queue should show ready, checking, waiting for owner, and complete states. Waiting should name the missing decision. This gives managers a way to allocate review without asking for status in separate messages.'],
    ['Close with an audit note','The final freshness note should say what was checked, what changed, which claims remain bounded, and when the next review is due. Preserve the old wording when the change matters so the editor can understand the decision.','Measure rework and unresolved source questions, not just the number of URLs collected. A smaller, traceable source set is more useful than a long list no one can maintain.']
  ]),
  'filipino-writer-feedback-loop': article('Build a useful feedback loop with Filipino article writers','A practical way to make article feedback specific, teachable, and connected to the reader’s decision.','/aug20-heroes/filipino-writer-feedback-loop.webp',[
    ['Anchor feedback in the assignment','Feedback is easiest to use when it points back to the brief. Start by restating the reader, decision, evidence standard, and role boundary. A comment that says “make this stronger” is not actionable; a comment that identifies a missing exception or unsupported conclusion is.','Ask the writer to respond to the decision behind each material edit. This creates a shared record of judgment without requiring a long meeting.'],
    ['Distinguish kinds of edits','Separate factual correction, structural change, clarity edit, originality concern, and owner decision. Different edit types need different responses. A writer can fix a heading sequence; an owner may need to decide whether a claim is supportable.','Use examples from outsourced labor operations, such as a queue handoff or customer escalation, to show why the distinction matters. Keep examples conditional unless the site has evidence for a specific result.'],
    ['Make comments locatable','A good comment names the section, sentence purpose, source, and requested action. Avoid feedback that depends on a private call. If a source does not support the sentence, link the source and explain the limit.','For remote teams, record the comment in the same system as the draft and preserve the resolved decision. The next writer should learn from the example rather than encountering the same correction as a surprise.'],
    ['Protect the writer’s authority line','A writer may suggest a safer wording or flag a gap, but should not invent company facts, testimonials, credentials, commercial terms, or outcomes to satisfy a review comment. The editor owns the public claim.','Create a stop rule for conflicting instructions. The handoff should state which sources disagree and who can resolve the issue. This is faster than asking the writer to guess which comment wins.'],
    ['Review the loop itself','Every few articles, inspect whether feedback is recurring because the brief is weak, the example library is incomplete, or the reviewer is using inconsistent standards. Retire comments that no longer teach anything.','Track correction themes and time to resolution. The goal is not fewer comments at any cost; it is clearer first drafts and earlier escalation of decisions that truly belong to an owner.']
  ]),
  'outsourced-blog-research-queue': article('Design a research queue for outsourced blog production','How to route blog research from question to usable evidence while keeping the site’s Philippines staffing niche central.','/aug20-heroes/outsourced-blog-research-queue.webp',[
    ['Queue questions, not just topics','A research queue should contain questions that change an article decision. Ask what inputs a Philippines-based specialist needs, what a manager must approve, or how an exception should be recorded. A topic label alone encourages broad notes that a writer cannot use.','Give every item a target reader, intended route, thesis, evidence standard, and owner. If any is missing, the item should wait in clarification rather than entering research.'],
    ['Use explicit states','Separate queued, researching, evidence ready, owner question, and handed off. Each state should have a finish condition. Evidence ready means the researcher has connected material claims to sources and marked limitations; it does not mean the article is approved.','Waiting reasons make capacity discussions honest. A queue full of “in progress” work hides whether the real constraint is source access, a missing brief, or an unresolved policy choice.'],
    ['Match source to question','Use primary or authoritative references for claims that affect access, safety, or role boundaries. Use practical examples to explain implementation, but label them as examples. Avoid turning one company’s workflow into a universal benchmark.','The researcher should record retrieval context and the exact claim supported. This lets an editor remove a sentence without losing the rest of the evidence packet.'],
    ['Keep the writer out of owner decisions','A research contributor can flag tradeoffs and prepare options. They should not decide public commercial terms, customer commitments, legal interpretations, or claims about performance. Route those items with a concise question and a named decision owner.','A clear boundary protects both quality and throughput. Routine evidence can move without waiting for an owner, while consequential choices become visible early.'],
    ['Measure queue health','Review age by state, clarification rate, source gaps, and rework after handoff. A fast-moving queue is not healthy if most items return because the question was never defined.','Use the review to improve briefs, examples, and source registers. Keep the queue narrow enough that the next owner can understand it without a meeting.']
  ]),
  'philippines-article-refresh-review': article('Run a refresh review for Philippines staffing articles','A bounded review method for updating guidance when sources, workflows, or reader questions change.','/aug20-heroes/philippines-article-refresh-review.webp',[
    ['Name the reason to refresh','Start with the trigger: a changed source, broken link, new reader confusion, a dated example, or an operating rule that no longer matches. “It has been a while” can justify inspection, but not a rewrite without evidence.','Preserve the original thesis during the first pass and list every proposed change. This makes it possible to distinguish a necessary correction from a new article idea.'],
    ['Check the article’s operating center','A refresh should still answer a real question about planning or managing Philippines-based staffing. Remove drift into generic productivity or unsupported market claims. Check examples for current role boundaries, approvals, and source quality.','If the reader’s question has changed materially, create a new brief rather than stretching the old URL. A refreshed page should retain a recognizable purpose.'],
    ['Re-test sources and dates','Verify every material source, date-sensitive statement, canonical identity, visible publication date, and structured date. Do not silently change publication history to make an old article appear new.','Record whether each source still supports the sentence and whether the sentence now needs conditional wording. This is where a source register prevents guesswork.'],
    ['Review links and examples','Internal links should lead to the next natural decision, not merely a nearby keyword. Replace broken or misleading links and check that examples do not repeat another article’s thesis.','A refresh is a good time to remove decorative detail that distracts from the decision. Keep the body substantive by adding verified explanation, not filler.'],
    ['Approve and schedule transparently','The editor approves material claims, role boundaries, and any change that affects a reader’s action. Record the review date, changed sections, unresolved limits, and next trigger.','Measure whether the refresh reduced confusion or corrected a known risk. Do not claim improved performance unless the site has evidence.']
  ]),
  'filipino-content-escalation-map': article('Map escalation paths for Filipino content support','How to show writers and researchers when routine article work must move to an accountable owner.','/aug20-heroes/filipino-content-escalation-map.webp',[
    ['Start with ordinary work','Define what the contributor can complete without intervention: formatting, source capture, outline organization, link checking, and corrections covered by examples. This keeps escalation from becoming a synonym for every question.','Write the ordinary path beside the exception path so the worker knows when to continue and when to pause.'],
    ['Name escalation triggers','Triggers include conflicting sources, sensitive personal data, a request to invent proof, an unsupported public commercial statement, a customer promise, a legal interpretation, or an altered publication date. Use plain language and examples.','Each trigger should identify the evidence to attach and the role that can decide. An escalation without context only transfers the confusion.'],
    ['Design the route','Map contributor to editor to accountable owner, with a fallback when someone is unavailable. Include response expectation, queue state, and what work can continue safely while waiting.','For a Philippines-based team working across hours, a dated handoff matters. It should show what is blocked and what is explicitly not blocked.'],
    ['Prevent escalation loops','If a question returns repeatedly, repair the source, brief, or example instead of sending it around the same people. Record the final interpretation and where it belongs in the routine.','Do not resolve a policy disagreement by majority vote. The accountable owner decides; the editor documents the result.'],
    ['Audit the map','Sample resolved escalations for completeness, decision authority, and whether the public copy reflects the final answer. Retire routes that no longer match tools or roles.','A good map makes safe work faster because contributors spend less time guessing and owners see consequential questions earlier.']
  ]),
  'outsourced-labor-content-brief-archive': article('Create an archive that makes outsourced content briefs reusable','How to preserve useful editorial decisions without copying old articles or flattening distinct reader questions.','/aug20-heroes/outsourced-labor-content-brief-archive.webp',[
    ['Archive decisions, not templates','Keep the reader, thesis, evidence boundary, approved examples, rejected approaches, and owner decisions. Do not treat a prior article as a body to recycle. A brief archive should teach why a choice was made.','Tag records by work lane and buyer question, then check for overlap before assigning a new route.'],
    ['Keep route identity explicit','Record title, slug, canonical, family, date, and related links. A new article needs its own identity even when it addresses a nearby service.','Compare thesis and conclusion, not only keywords. Two pages can use different nouns and still compete for the same question.'],
    ['Preserve limitations','Archive source limitations and claims that were deliberately excluded. This protects future writers from turning a cautious article into an unsupported promise.','Add review dates for evidence that may change and note which decisions require owner approval again.'],
    ['Make retrieval practical','Use a short index with question, lane, status, and owner. Link to source records and examples. Avoid a giant folder that depends on one person’s memory.','A Filipino writer should be able to find relevant context and still make an original structure. Retrieval should inform judgment, not dictate prose.'],
    ['Audit reuse risk','Before drafting, compare the new brief with the archive for duplicate route, thesis, scenarios, and conclusion. If overlap is material, merge the question or choose a new one.','Measure fewer repeated corrections and faster briefing, not article volume. The archive earns its place by improving decisions.']
  ]),
  'philippines-blog-reader-intent': article('Translate reader intent into Philippines staffing guidance','A practical method for turning a search question into an article that helps a staffing decision.','/aug20-heroes/philippines-blog-reader-intent.webp',[
    ['Identify the decision beneath the query','Readers may ask about virtual assistants, admin support, or outsourcing, but the real decision may concern scope, access, coverage, or review. Name that decision before choosing headings.','Keep the Philippines context central through realistic role boundaries and handoffs, while avoiding invented company experience.'],
    ['Describe the reader’s starting state','State what the reader likely has: a recurring queue, inconsistent records, unclear approvals, or a need to prepare work for remote staff. This gives the article a concrete opening.','Use conditional examples rather than pretending to know the reader’s tools, location, or results.'],
    ['Build a decision path','Move from problem to options, evidence, controls, and next action. A reader should understand what to prepare, what to test, and what remains an owner decision.','Place exceptions where they matter. A late warning about sensitive data does not protect the reader as well as a boundary beside the workflow.'],
    ['Match claims to proof','General guidance can be explained directly; statistics, legal points, and claims about outcomes need appropriate sources. Mark uncertainty and source age.','A useful article can be honest about what it cannot conclude. That makes it more trustworthy than a confident but unsupported comparison.'],
    ['Test the conclusion','The conclusion should answer the original question and propose a bounded next step, such as documenting one queue or collecting sample records. Do not end with a generic sales promise or commercial call to action.','Review whether the article is distinct from adjacent pages by comparing thesis, examples, structure, and links.']
  ]),
  'filipino-article-proof-boundaries': article('Set proof boundaries for Filipino article production','How to keep useful guidance separate from unsupported claims when remote content staff prepare public articles.','/aug20-heroes/filipino-article-proof-boundaries.webp',[
    ['Classify every material statement','Use four buckets: observed source fact, general guidance, conditional example, and claim requiring owner evidence. The writer can organize the first three when the brief permits; the last needs a decision.','This classification helps a Filipino contributor pause without feeling that every sentence needs a meeting.'],
    ['Do not fill evidence gaps','When a source does not prove a result, remove the result or rewrite it as a possible consideration. Never invent a testimonial, credential, location, client, benchmark, or company history to make an article sound complete.','A bounded sentence can still teach a reader what to check and who should approve it.'],
    ['Connect proof to the reader action','For each important recommendation, say what evidence would make it reasonable: a sample queue, a policy, a source record, or an owner decision. This turns abstract advice into a checkable step.','Keep the evidence trail close to the draft so review does not depend on memory.'],
    ['Escalate sensitive language','Route claims about money, legal duties, privacy, security, employment classification, customer outcomes, or guarantees. The editor can propose careful wording; the accountable owner decides whether it belongs publicly.','Record the question and source rather than hiding the uncertainty in a private chat.'],
    ['Review proof after edits','A structural rewrite can change the meaning of a supported sentence. Recheck claims after major edits, metadata changes, and link substitutions.','Measure unsupported-claim corrections and repeat causes. Improve briefs and examples so proof boundaries become part of normal production.']
  ]),
  'outsourced-content-handoff-window': article('Design a clean handoff window for outsourced content','How to move article work between time zones without losing source context, decision ownership, or publication readiness.','/aug20-heroes/outsourced-content-handoff-window.webp',[
    ['Define the handoff moment','A handoff is not simply the end of a shift. Name the state that makes the item transferable: draft complete, sources mapped, open questions listed, and next owner identified.','For Philippines-based contributors and other remote collaborators, use a predictable cutoff and a visible queue state.'],
    ['Write the minimum useful record','Include article question, completed work, files or links, source limitations, material edits, blockers, and next action. Avoid long narrative that hides the one decision the next owner needs.','The next owner should be able to act without rereading a private thread.'],
    ['Keep authority with the owner','A contributor may hand off a recommendation, not approval. Publishing, policy exceptions, public claims, and customer commitments remain with the named owner.','If the owner is unavailable, mark the item waiting rather than allowing a different role to infer authority.'],
    ['Protect continuity','Preserve version identity, route, date, and related links. Check that a late edit did not change metadata or source meaning.','Use a short acceptance response: received, accepted for review, returned for clarification, or escalated.'],
    ['Learn from failed handoffs','Review items returned for missing context, contradictory edits, or unclear ownership. Convert repeat issues into a better brief or checklist.','A handoff window succeeds when work progresses across hours without making the public article less accurate or less original.']
  ]),
  'philippines-content-calendar-recovery': article('Recover a Philippines content calendar after a delay','How to restore an article routine after missed dates without hiding risk or rewriting publication history.','/aug20-heroes/philippines-content-calendar-recovery.webp',[
    ['Freeze the facts','List what is actually ready: brief, research, draft, review, metadata, asset, and owner decision. Do not call an item publish-ready because a calendar date passed.','Keep the original target visible and record the reason for delay.'],
    ['Sort by consequence','Prioritize items with high reader value, time-sensitive sources, active dependencies, or a clear owner decision. Do not let the loudest request reorder everything.','A Philippines-based support routine benefits from explicit queue states and local handoff times.'],
    ['Repair dependencies','For each delayed article, name the missing source, approval, image, link, or technical check. Assign one owner and a next date.','If the premise has changed, write a new brief rather than forcing an outdated article through.'],
    ['Protect dates and originality','Never date-shift an old record to make the calendar look complete. A new route must be genuinely new, and an existing article keeps its truthful publication history.','Compare title, slug, thesis, structure, and conclusion before reusing an archived idea.'],
    ['Restart with a smaller promise','Choose a repeatable daily output that the team can review. Measure the share ready to publish, return reasons, and unresolved decisions instead of raw volume.','A recovered calendar is credible when each date corresponds to evidence, not optimism.']
  ]),
  'outsourced-labor-editorial-retrospective': article('Run an editorial retrospective for outsourced labor content','A practical retrospective for improving recurring article work while keeping decisions, evidence, and role boundaries visible.','/aug20-heroes/outsourced-labor-editorial-retrospective.webp',[
    ['Review the work system','Bring a small sample of briefs, source registers, drafts, corrections, and handoffs. Ask where work waited and why. Avoid evaluating a contributor from one unusual case.','Keep the discussion tied to the site’s purpose: useful guidance for planning and managing Philippines-based staffing.'],
    ['Separate signal from story','Count observed correction themes, queue age, missing inputs, source questions, and approval waits. Keep explanations labeled as hypotheses until evidence supports them.','This prevents a manager from blaming speed when the real problem is an incomplete brief or unclear owner.'],
    ['Choose one repair','A retrospective should produce one or two changes: an improved intake field, a clearer example, a source trigger, or an escalation rule. Too many changes make the next review impossible to interpret.','Assign an owner, test window, and success evidence.'],
    ['Protect what worked','Record practices worth keeping, such as a useful handoff format or a good exception example. Improvement does not mean replacing every routine.','Keep rejected ideas with their reason so they do not return as if they were new.'],
    ['Close the loop','At the next review, compare the chosen change with the observed baseline. If it did not help, explain why and adjust the experiment.','Do not claim better results without measured support. The retrospective is successful when the team makes clearer decisions with less repeated confusion.']
  ])
};

export function getAug20Metadata(slug: string) { const x = articles[slug]; const hero=x.hero.replace('.webp','.png'); return { title: x.title, description: x.description, alternates: { canonical: `/blog/${slug}` }, openGraph: { title: x.title, description: x.description, url: `${SITE}/blog/${slug}`, images: [hero] } }; }
export function renderAug20Article(slug: string) { const x = articles[slug]; const e = expansion[slug]; const hero=x.hero.replace('.webp','.png'); const url = `${SITE}/blog/${slug}`; const schema = { '@context':'https://schema.org', '@type':'Article', headline:x.title, description:x.description, datePublished:'2026-08-20', dateModified:'2026-08-20', mainEntityOfPage:url, image:`${SITE}${hero}` }; const extra = [
  `Use ${e.lens} as an operating record, not as a decorative step in a content calendar. The useful question is what another person can inspect after the work is complete. Start with ${e.input}. These details give a Philippines-based remote contributor enough context to prepare a careful draft while leaving consequential decisions visible.`,
  `The first durable output should be ${e.artifact}. It should be small enough to read during a handoff and precise enough to explain why the article took its shape. Include the reader decision, material sources, unresolved questions, and the point at which the next person must stop.`,
  `The main failure mode is ${e.risk}. Prevent it by comparing the proposed paragraph with the reader’s actual decision before polishing style. If it cannot say what action or judgment it supports, move it back to the brief.`,
  `A useful example is ${e.example}. Treat that scenario as an illustration, not evidence of a particular company’s history or result. Show the input, routine action, exception, and accountable owner. Conditional examples help Filipino writers explain a workflow without inventing claims.`,
  `Keep authority explicit. ${e.boundary} ${e.owner} decides whether a material public statement is accurate and within scope. That separation protects the reader and gives the contributor a clear answer when a review comment conflicts with available evidence.`,
  `Before handoff, run one claim-level check. Ask whether each important sentence has a source, is guidance, or is a conditional example. Check dates, links, role names, and the conclusion separately. ${e.check}.`,
  `The handoff should be written for a person who has not watched the work happen. ${e.handoff} Include the route, version, source limitations, open questions, and next action. Label missing dependencies as waiting instead of filling gaps with confident prose.`,
  `Measure the routine with evidence that matches its purpose: frequency of clarification, returned sections, unresolved source questions, queue age, and owner wait time. Raw article volume cannot show whether guidance is accurate or usable.`,
  `Do not let a nearby article decide this article’s structure. Compare title, thesis, reader question, scenarios, links, and conclusion with related Philippines staffing guidance. Originality prevents two routes from giving readers the same thin answer.`,
  `Close by recording one next action and one limitation. The next action may be to verify a source, clarify a role, or ask the owner to decide an exception. End with ${e.review}. That note turns a one-day article into a traceable routine.`
]; return <><Header/><main className="article-shell"><article><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><p className="eyebrow">Blog</p><h1>{x.title}</h1><p>{x.description}</p><p><time dateTime="2026-08-20">August 20, 2026</time></p><img src={hero} alt={`${x.title} editorial illustration`} width="1536" height="1024" style={{width:'100%',height:'auto',borderRadius:'18px'}}/><div className="article-body">{x.sections.map(([heading,first,second])=><section key={heading}><h2>{heading}</h2><p>{first}</p><p>{second}</p><p>Apply this check to the next article in the queue, record the evidence, and keep the decision boundary visible to the person who approves public copy. That small discipline makes outsourced work easier to inspect and safer to continue across working hours.</p></section>)}<section><h2>Make the routine inspectable</h2>{extra.map((paragraph,index)=><p key={index}>{paragraph}</p>)}</section></div></article><CTA/></main><Footer/></>; }
