export const aug23Posts = [
  {slug:'outsourced-labor-article-intake-triage',title:'Triage article requests before assigning outsourced labor',excerpt:'A decision-first method for sorting article requests so Philippines-based contributors receive clear questions, sources, and approval boundaries.',minutes:13},
  {slug:'philippines-outsourced-labor-role-scorecard',title:'Build a role scorecard for Philippines-based outsourced work',excerpt:'Use a role scorecard to make scope, quality, questions, and escalation visible before expanding a recurring work lane.',minutes:13},
  {slug:'outsourced-labor-source-register-for-articles',title:'Create a source register for outsourced labor articles',excerpt:'A practical source register for keeping recurring articles traceable, current, and within the evidence available to the editorial team.',minutes:13},
  {slug:'filipino-content-review-queue-design',title:'Design a review queue for Filipino content contributors',excerpt:'Design review states that help editors protect originality, evidence, and publication ownership in a daily article routine.',minutes:13},
  {slug:'philippines-outsourced-labor-briefing-rhythm',title:'Set a briefing rhythm for Philippines-based outsourced teams',excerpt:'A lightweight rhythm for turning recurring work into clear daily starts, useful questions, and dependable handoffs.',minutes:13},
  {slug:'outsourced-labor-article-originality-check',title:'Run an originality check for outsourced labor articles',excerpt:'A practical originality review that compares reader decisions, not just keywords, before a new article enters the Blog family.',minutes:13},
  {slug:'filipino-outsourced-work-handoff-acceptance',title:'Create an acceptance check for Filipino outsourced work handoffs',excerpt:'Use an acceptance check to show whether a handoff is ready for review, needs correction, or must pause for an owner decision.',minutes:13},
  {slug:'philippines-outsourced-labor-exception-aging',title:'Review exception aging in Philippines-based outsourced work',excerpt:'A practical way to distinguish a genuinely aging exception from a missing owner, weak source, or unclear role boundary.',minutes:13},
  {slug:'outsourced-labor-content-approval-boundaries',title:'Set approval boundaries for outsourced labor content',excerpt:'Separate drafting, editing, evidence review, and accountable approval so daily article production stays useful and truthful.',minutes:13},
  {slug:'filipino-outsourced-labor-absence-recovery',title:'Plan absence recovery for Filipino outsourced work',excerpt:'Protect recurring work when a Philippines-based contributor is unavailable without widening access or hiding unresolved decisions.',minutes:13},
  {slug:'philippines-outsourced-labor-work-queue-capacity',title:'Plan queue capacity for Philippines-based outsourced work',excerpt:'Separate arrivals, available attention, review effort, and exceptions before promising a safe workload for a remote work lane.',minutes:13},
  {slug:'outsourced-labor-editorial-claim-review',title:'Review claims before publishing outsourced labor guidance',excerpt:'A claim review method for keeping practical Philippines staffing advice accurate, conditional, and free of unsupported public assertions.',minutes:13}
] as const;
