export const fleetServices = [
  {
    "slug": "workforce-scheduling",
    "title": "Workforce Scheduling",
    "summary": "A Filipino workforce scheduling specialist can prepare shift drafts, track availability, and flag coverage gaps before schedules go live. Your manager keeps control of staffing levels, overtime, leave decisions, and last-minute exceptions.",
    "tasks": [
      "collect employee availability and approved leave",
      "prepare shift drafts from coverage rules",
      "flag open shifts, overlaps, and rest-time concerns",
      "record swaps and send approved schedule notices"
    ],
    "controls": [
      "A manager approves overtime, leave, and staffing changes",
      "The specialist uses named access limited to scheduling tools",
      "Every schedule draft includes a short list of gaps and exceptions"
    ],
    "launch": [
      "Share two recent schedules, availability records, and coverage rules",
      "Draft one schedule without publishing or messaging the team",
      "Review every exception together before the manager approves release"
    ]
  },
  {
    "slug": "sop-documentation",
    "title": "SOP Documentation",
    "summary": "SOP Documentation delivered by Philippines-based specialists with a documented scope, review path, and owner approval rules.",
    "tasks": [
      "sop documentation queue preparation",
      "source-record checks and updates",
      "exception logging for manager review",
      "daily handoff notes and follow-up"
    ],
    "controls": [
      "Named owner for approvals and exceptions",
      "Role-based access to required tools",
      "Sample review before the work lane expands"
    ],
    "launch": [
      "Share current examples and source records",
      "Document the finish line and escalation rule",
      "Review the first work batch together"
    ]
  },
  {
    "slug": "order-operations",
    "title": "Order Operations",
    "summary": "Order Operations delivered by Philippines-based specialists with a documented scope, review path, and owner approval rules.",
    "tasks": [
      "order operations queue preparation",
      "source-record checks and updates",
      "exception logging for manager review",
      "daily handoff notes and follow-up"
    ],
    "controls": [
      "Named owner for approvals and exceptions",
      "Role-based access to required tools",
      "Sample review before the work lane expands"
    ],
    "launch": [
      "Share current examples and source records",
      "Document the finish line and escalation rule",
      "Review the first work batch together"
    ]
  },
  {
    "slug": "vendor-coordination",
    "title": "Vendor Coordination",
    "summary": "Vendor Coordination delivered by Philippines-based specialists with a documented scope, review path, and owner approval rules.",
    "tasks": [
      "vendor coordination queue preparation",
      "source-record checks and updates",
      "exception logging for manager review",
      "daily handoff notes and follow-up"
    ],
    "controls": [
      "Named owner for approvals and exceptions",
      "Role-based access to required tools",
      "Sample review before the work lane expands"
    ],
    "launch": [
      "Share current examples and source records",
      "Document the finish line and escalation rule",
      "Review the first work batch together"
    ]
  },
  {
    "slug": "inventory-administration",
    "title": "Inventory Administration",
    "summary": "Inventory Administration delivered by Philippines-based specialists with a documented scope, review path, and owner approval rules.",
    "tasks": [
      "inventory administration queue preparation",
      "source-record checks and updates",
      "exception logging for manager review",
      "daily handoff notes and follow-up"
    ],
    "controls": [
      "Named owner for approvals and exceptions",
      "Role-based access to required tools",
      "Sample review before the work lane expands"
    ],
    "launch": [
      "Share current examples and source records",
      "Document the finish line and escalation rule",
      "Review the first work batch together"
    ]
  },
  {
    "slug": "crm-data-stewardship",
    "title": "CRM Data Stewardship",
    "summary": "CRM Data Stewardship delivered by Philippines-based specialists with a documented scope, review path, and owner approval rules.",
    "tasks": [
      "crm data stewardship queue preparation",
      "source-record checks and updates",
      "exception logging for manager review",
      "daily handoff notes and follow-up"
    ],
    "controls": [
      "Named owner for approvals and exceptions",
      "Role-based access to required tools",
      "Sample review before the work lane expands"
    ],
    "launch": [
      "Share current examples and source records",
      "Document the finish line and escalation rule",
      "Review the first work batch together"
    ]
  },
  {
    "slug": "procurement-follow-up",
    "title": "Procurement Follow-Up",
    "summary": "Procurement Follow-Up delivered by Philippines-based specialists with a documented scope, review path, and owner approval rules.",
    "tasks": [
      "procurement follow-up queue preparation",
      "source-record checks and updates",
      "exception logging for manager review",
      "daily handoff notes and follow-up"
    ],
    "controls": [
      "Named owner for approvals and exceptions",
      "Role-based access to required tools",
      "Sample review before the work lane expands"
    ],
    "launch": [
      "Share current examples and source records",
      "Document the finish line and escalation rule",
      "Review the first work batch together"
    ]
  },
  {
    "slug": "quality-audit-support",
    "title": "Quality Audit Support",
    "summary": "Quality Audit Support delivered by Philippines-based specialists with a documented scope, review path, and owner approval rules.",
    "tasks": [
      "quality audit support queue preparation",
      "source-record checks and updates",
      "exception logging for manager review",
      "daily handoff notes and follow-up"
    ],
    "controls": [
      "Named owner for approvals and exceptions",
      "Role-based access to required tools",
      "Sample review before the work lane expands"
    ],
    "launch": [
      "Share current examples and source records",
      "Document the finish line and escalation rule",
      "Review the first work batch together"
    ]
  },
  {
    "slug": "workforce-reporting",
    "title": "Workforce Reporting",
    "summary": "Workforce Reporting delivered by Philippines-based specialists with a documented scope, review path, and owner approval rules.",
    "tasks": [
      "workforce reporting queue preparation",
      "source-record checks and updates",
      "exception logging for manager review",
      "daily handoff notes and follow-up"
    ],
    "controls": [
      "Named owner for approvals and exceptions",
      "Role-based access to required tools",
      "Sample review before the work lane expands"
    ],
    "launch": [
      "Share current examples and source records",
      "Document the finish line and escalation rule",
      "Review the first work batch together"
    ]
  },
  {
    "slug": "operations-dispatch",
    "title": "Operations Dispatch",
    "summary": "Operations Dispatch delivered by Philippines-based specialists with a documented scope, review path, and owner approval rules.",
    "tasks": [
      "operations dispatch queue preparation",
      "source-record checks and updates",
      "exception logging for manager review",
      "daily handoff notes and follow-up"
    ],
    "controls": [
      "Named owner for approvals and exceptions",
      "Role-based access to required tools",
      "Sample review before the work lane expands"
    ],
    "launch": [
      "Share current examples and source records",
      "Document the finish line and escalation rule",
      "Review the first work batch together"
    ]
  }
] as const;
type ResearchPost = {slug:string;title:string;excerpt:string;published:string;body:readonly string[];image?:string;sources?:readonly {name:string;url:string}[];related?:readonly string[];cta?:string;headlineStat?:string;keyStats?:readonly string[];takeaways?:readonly string[];faqs?:readonly {q:string;a:string}[]};
const baseResearchPosts: ReadonlyArray<ResearchPost> = [
  {
    slug: 'daily-research-workflow-for-outsourced-operations',
    title: 'A Daily Research Workflow for Outsourced Operations',
    excerpt: 'A repeatable evidence workflow helps a lean operations team turn research requests into reviewable decisions without losing source context.',
    published: '2026-08-07',
    image: '/research/daily-research-workflow.svg',
    sources: [{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},{name:'SBA: Hire and Manage Employees',url:'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees'}],
    related: ['research-brief-for-outsourced-operations','research-source-ledger-for-daily-decisions'],
    cta: 'Need a repeatable publishing routine? Map the work lane with our team.',
    body: [
      'Daily research is easiest to maintain when every request has a named question, a decision it supports, and a clear owner for the final review. Start by writing the question in one sentence and recording the audience, time period, geography, and definition of any metric before opening a search tab.',
      'Keep an evidence ledger while you work. For each useful source, record the publisher, page title, publication or update date, URL, the exact claim it supports, and any limitations. This makes a handoff auditable and prevents a source list from becoming a collection of links with no connection to the article’s statements.',
      'Separate source facts from interpretation. A research draft can summarize what a source says, explain why it matters to the operating decision, and identify an assumption that still needs owner approval. Keeping those layers distinct makes it easier to correct a weak claim without rewriting the entire recommendation.',
      'Use a short review gate before publication: verify that every headline statistic has a source, that dates and units match, that links resolve, and that the conclusion does not claim more than the evidence supports. Flag unresolved gaps instead of filling them with confident-sounding generalities.',
      'A practical daily handoff should include the question, a one-paragraph finding, the source ledger, open uncertainties, and the recommended next action. The business owner can then approve, request a focused follow-up, or defer the decision while preserving the work for the next research cycle.'
    ]
  },
  {
    slug: 'research-brief-for-outsourced-operations', title: 'How to Write a Research Brief for Outsourced Operations', excerpt: 'A concise brief gives a research assistant the question, evidence standard, and decision context needed for useful daily work.', published: '2026-08-07', image: '/research/research-brief.svg', sources: [{name:'SBA: Hire and Manage Employees',url:'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees'}], related: ['research-source-ledger-for-daily-decisions','research-quality-checklist-for-publishing'], cta: 'Turn recurring research into a reviewable daily queue.', body: ['A good brief names the decision first. State what the owner needs to choose, the audience for the answer, and the date by which the finding is useful. A topic alone is not a research question.', 'Specify scope before searching: geography, time period, definitions, acceptable source types, and excluded claims. This prevents a short deadline from turning into an unbounded reading list.', 'Define the output contract. Ask for a concise finding, an evidence ledger, uncertainties, and a recommended next step. Require the writer to distinguish sourced facts from interpretation.', 'Review the first few briefs against the same checklist. Repair ambiguous questions early, then preserve the approved format as a reusable template.']
  },
  {
    slug: 'research-source-ledger-for-daily-decisions', title: 'Build a Source Ledger for Daily Research Decisions', excerpt: 'A source ledger preserves the link between each published claim and the evidence that supports it.', published: '2026-08-07', image: '/research/source-ledger.svg', sources: [{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'}], related: ['research-quality-checklist-for-publishing','research-citation-review-for-content-teams'], cta: 'Make every published research claim easier to review.', body: ['Record the publisher, page title, URL, publication or update date, and the claim supported by each source. Add a short limitation so a later editor knows what the source does not establish.', 'Keep one row per claim when a source supports several statements. This makes broken links, changed pages, and overstated conclusions visible during review.', 'Use primary and authoritative sources for important figures, and label estimates, surveys, and commentary accurately. A source list without claim mapping is not an evidence trail.', 'Archive the ledger with the article record. The next editor should be able to reproduce the reasoning without guessing which paragraph came from which page.']
  },
  {
    slug: 'research-quality-checklist-for-publishing', title: 'A Quality Checklist for Publishing Research Articles', excerpt: 'A practical preflight catches unsupported claims, stale links, missing context, and weak calls to action before an article goes live.', published: '2026-08-07', image: '/research/research-quality-checklist.svg', sources: [{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'}], related: ['research-citation-review-for-content-teams','research-metadata-for-daily-articles'], cta: 'Use a quality gate that keeps daily publishing dependable.', body: ['Start with the reader promise. Confirm that the title, introduction, headings, and conclusion answer the same question and that the article does not quietly change scope.', 'Check each factual claim for a nearby citation, matching date and unit, and a source that actually supports the wording. Downgrade or remove claims that the evidence cannot carry.', 'Test every internal and external link, image path, canonical route, metadata field, and CTA. A production build should succeed with the same content that passed editorial review.', 'Record the checks and the reviewer. A short dated preflight creates a useful audit trail and makes recurring defects easier to fix in the publishing routine.']
  },
  {
    slug: 'research-citation-review-for-content-teams', title: 'How to Review Citations in a Daily Content Team', excerpt: 'Citation review is a judgment task: verify relevance, freshness, context, and whether the article says more than the source.', published: '2026-08-07', image: '/research/citation-review.svg', sources: [{name:'SBA: Hire and Manage Employees',url:'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees'}], related: ['research-metadata-for-daily-articles','research-external-link-maintenance'], cta: 'Give editors a simple path for resolving citation questions.', body: ['Read the claim before opening the link. Identify the exact proposition, then check whether the source contains that proposition rather than merely discussing the same topic.', 'Check timing and context. A current article may rely on an older statistic, a different population, or a changed definition. Preserve the original date and explain why it remains useful.', 'Flag interpretation as interpretation. Editors can keep a reasoned implication, but should not present a source’s observation as proof of a broader business outcome.', 'When a citation fails review, narrow the sentence, find a stronger source, or remove the claim. Record the decision so the same question is not reopened without new evidence.']
  },
  {
    slug: 'research-metadata-for-daily-articles', title: 'Metadata Controls for Daily Research Articles', excerpt: 'Consistent metadata helps search engines, readers, editors, and deployment checks understand each research article.', published: '2026-08-07', image: '/research/research-metadata.svg', sources: [{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'}], related: ['research-external-link-maintenance','research-image-and-og-checks'], cta: 'Build metadata checks into the daily article handoff.', body: ['Give every article one stable slug, a descriptive title, a specific description, a published date, and a canonical URL. Keep the values aligned with the visible headline and the article question.', 'Use structured data only for information present on the page. Do not invent authorship, reviews, ratings, or dates that the editorial record cannot support.', 'Check index and sitemap inclusion after adding the route. A healthy page that is absent from navigation or the sitemap is still an incomplete publication.', 'Treat metadata as part of the content record, not a last-minute SEO patch. Validate it in the build and sample the rendered HTML before deployment.']
  },
  {
    slug: 'research-external-link-maintenance', title: 'Maintain External Links in a Research Library', excerpt: 'A small link-maintenance routine protects trust when source pages move, change, or disappear after publication.', published: '2026-08-07', image: '/research/external-link-maintenance.svg', sources: [{name:'CISA: Require Multifactor Authentication',url:'https://www.cisa.gov/audiences/small-and-medium-businesses/secure-your-business/require-multifactor-authentication'}], related: ['research-image-and-og-checks','research-daily-publishing-handoff'], cta: 'Keep source links useful after the article is published.', body: ['Store the full source URL and the page title when the article is drafted. A title alone is not enough for an editor to find the evidence again.', 'Check links during publication and on a scheduled maintenance pass. Treat redirects, access blocks, removed pages, and changed content as review signals rather than silently replacing evidence.', 'Prefer stable pages from authoritative organizations for foundational claims. If a source is time-sensitive, record the retrieval context and explain its date in the article.', 'When a link must change, verify the replacement supports the same claim. Update the ledger and article together so the public page and internal record do not diverge.']
  },
  {
    slug: 'research-image-and-og-checks', title: 'Image and Open Graph Checks for Research Pages', excerpt: 'A research page needs a reliable visual asset and share metadata as well as accurate prose and citations.', published: '2026-08-07', image: '/research/image-and-og-checks.svg', sources: [{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'}], related: ['research-daily-publishing-handoff','research-article-cta-design'], cta: 'Make article previews and page assets part of the definition of done.', body: ['Assign a purposeful image path to each article and verify that the file is committed, served from the expected public route, and readable at the target size. A missing image is a publication defect, not decoration.', 'Set the page title, description, canonical URL, and social preview values from the same article record. Keep the headline legible in a small preview and avoid implying evidence the page does not contain.', 'Sample the deployed route with an image request and inspect the rendered head tags. This catches path casing, stale builds, and incorrect host mappings that local checks can miss.', 'Use a shared visual system so the library feels coherent while each article remains identifiable. Document the asset check in the daily handoff.']
  },
  {
    slug: 'research-daily-publishing-handoff', title: 'Design a Daily Research Publishing Handoff', excerpt: 'A clear handoff connects research, editorial review, build validation, and production verification without losing ownership.', published: '2026-08-07', image: '/research/daily-publishing-handoff.svg', sources: [{name:'SBA: Hire and Manage Employees',url:'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees'}], related: ['research-article-cta-design','research-content-audit-trail'], cta: 'Make the next publishing cycle easier to run and verify.', body: ['Name one owner for the research question, one reviewer for evidence and copy, and one release owner for the production check. Shared responsibility without a named handoff creates silent gaps.', 'Pass a compact packet: slug, title, date, body, image path, source ledger, internal links, CTA, and validation notes. The packet should be sufficient for another person to reproduce the release.', 'Run content checks before the build, then route checks after deployment. Confirm both the exact commit and representative public pages so a successful build is not mistaken for a live release.', 'Capture exceptions in the next-action list. A blocked source or route should have an owner and deadline instead of disappearing into a status message.']
  },
  {
    slug: 'research-article-cta-design', title: 'Design Useful CTAs for Research Articles', excerpt: 'A good research CTA follows the reader’s decision and offers a concrete next step without overstating what the evidence proves.', published: '2026-08-07', image: '/research/article-cta-design.svg', sources: [{name:'SBA: Hire and Manage Employees',url:'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees'}], related: ['research-content-audit-trail','research-brief-for-outsourced-operations'], cta: 'Connect evidence to a practical next action for your reader.', body: ['Place the CTA after the article has answered its question. The next step should relate to the decision the reader came to make, such as defining a work lane, reviewing a source ledger, or planning a staffing conversation.', 'Use specific language that says what happens next. Avoid vague promises, urgency, or claims that the research guarantees a business result.', 'Keep the CTA within the site’s internal navigation and make the destination useful on its own. Test the link and confirm it works on mobile as well as desktop.', 'Review CTAs for fit during the same preflight as citations and metadata. A relevant, honest next step improves the article without changing the evidence.']
  },
  {
    slug: 'research-content-audit-trail', title: 'Keep an Audit Trail for Daily Research Content', excerpt: 'A lightweight audit trail makes content corrections, source decisions, and deployment evidence recoverable for the next review.', published: '2026-08-07', image: '/research/content-audit-trail.svg', sources: [{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'}], related: ['research-brief-for-outsourced-operations','daily-research-workflow-for-outsourced-operations'], cta: 'Make daily content operations easier to inspect and improve.', body: ['Record the question, owner, reviewer, source ledger, article slug, and publication date. These fields explain why the article exists and who can resolve a question about it.', 'Keep validation evidence close to the release record: the build result, exact commit, representative routes, and any known exceptions. Do not rely on an empty index or an older library as proof of a new batch.', 'When content changes, note what changed and why. A narrow correction should not erase the source context or make the original decision impossible to understand.', 'Use the audit trail to improve the routine. Repeated missing images, weak internal links, or late metadata fixes are process signals worth addressing in the next batch.']
  }
] as const;
const batchSources = [
  {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},
  {name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'},
  {name:'CISA Cybersecurity Performance Goals',url:'https://www.cisa.gov/cybersecurity-performance-goals'},
  {name:'SBA Hire and manage employees',url:'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees'},
  {name:'SBA Write your business plan',url:'https://www.sba.gov/business-guide/plan-your-business/write-your-business-plan'},
  {name:'Google Search Central SEO starter guide',url:'https://developers.google.com/search/docs/fundamentals/seo-starter-guide'},
  {name:'Google structured data introduction',url:'https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data'},
  {name:'OWASP ASVS',url:'https://owasp.org/www-project-application-security-verification-standard/'},
  {name:'World Bank Data for Better Lives',url:'https://www.worldbank.org/en/publication/wdr2021'},
  {name:'ILO Decent Work and the 2030 Agenda',url:'https://www.ilo.org/global/topics/sdg-2030/lang--en/index.htm'}
] as const;
const replacementSources = [
  {name:'ILO Decent Work and the 2030 Agenda',url:'https://www.ilo.org/global/topics/sdg-2030/lang--en/index.htm'},
  {name:'World Bank Data for Better Lives',url:'https://www.worldbank.org/en/publication/wdr2021'},
  {name:'SBA Hire and manage employees',url:'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees'},
  {name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'}
] as const;
const replacementResearchTopics = [
  {slug:'research-aug13-workload-variability', title:'Measure workload variability before delegating recurring support', excerpt:'Variation in arrivals and case difficulty matters as much as average volume when an owner evaluates a recurring support lane.', focus:'workload variability', unit:'cases per business day', period:'an eight-week observation period', finding:'Average arrivals conceal the operational effect of peaks, long-tail cases, and incomplete requests.', limitation:'A short observation cannot represent seasonal demand or an unusual event, so it should be treated as a bounded baseline.', decision:'whether the work can be described by a stable unit, a range, and an exception rule'},
  {slug:'research-aug13-role-authority', title:'Separate preparation from decision authority in outsourced support', excerpt:'A clear authority boundary protects service quality when a support contributor handles records but an owner retains consequential decisions.', focus:'role authority', unit:'decision classes', period:'the first 30 completed cases', finding:'Preparation, recommendation, approval, and escalation are different responsibilities even when they touch the same record.', limitation:'A written boundary cannot predict every novel case; the unresolved examples must be reviewed by the accountable owner.', decision:'which actions may be prepared, which require approval, and which must stop for clarification'},
  {slug:'research-aug13-onboarding-learning', title:'Evaluate learning transfer in a new outsourced support lane', excerpt:'Learning transfer is visible when a qualified contributor can apply a rule, recognize an exception, and explain the next owner decision.', focus:'learning transfer', unit:'representative cases', period:'a two-week supervised learning period', finding:'Attendance or explanation alone does not show that a work rule is understood in practice.', limitation:'A small case set may overrepresent ordinary work and underrepresent rare but consequential exceptions.', decision:'whether the lane is ready for independent handling, narrower scope, or more supervised practice'},
  {slug:'research-aug13-context-continuity', title:'Protect customer context across delegated service handoffs', excerpt:'Continuity depends on preserving the facts and next decision a customer case needs, not on preserving every line of conversation.', focus:'context continuity', unit:'handoff records', period:'three consecutive handoff cycles', finding:'A compact, structured record can be more useful than a long transcript when ownership changes across hours or locations.', limitation:'The right fields depend on the service and the sensitivity of the information, so a universal handoff form is unsafe.', decision:'which facts, deadlines, owners, and unresolved questions must travel with each case'},
  {slug:'research-aug13-knowledge-dependence', title:'Find knowledge dependencies before expanding delegated work', excerpt:'A support lane is more resilient when its source records, definitions, and exception rules are discoverable by more than one person.', focus:'knowledge dependence', unit:'critical work steps', period:'one complete monthly work cycle', finding:'Repeated clarification often signals a missing source or ambiguous rule rather than an individual performance problem.', limitation:'The assessment shows dependency in the sampled work and does not prove that every future case will follow the same pattern.', decision:'which knowledge must be documented, who owns it, and what happens when the source is unavailable'},
  {slug:'research-aug13-error-consequence', title:'Assess error consequence instead of counting every mistake alike', excerpt:'A useful quality study distinguishes harmless corrections from errors that expose information, delay a customer, or change a decision.', focus:'error consequence', unit:'reviewed records', period:'a defined sample from one reporting month', finding:'Activity totals and raw error counts do not show which failure modes deserve the fastest response.', limitation:'Consequence scoring contains judgment and should be calibrated with the accountable service owner.', decision:'which error classes require correction, escalation, permission change, or a narrower work boundary'},
  {slug:'research-aug13-acceptance-evidence', title:'Use evidence-based acceptance for outsourced administrative work', excerpt:'Acceptance criteria are strongest when they describe the observable result, the required evidence, and the owner who resolves an exception.', focus:'acceptance evidence', unit:'completed work items', period:'the next four review cycles', finding:'A request is not complete merely because activity occurred; completion depends on the intended outcome and its evidence.', limitation:'Evidence requirements that are too broad can create unnecessary handling and obscure the decision that matters.', decision:'what counts as complete, pending, rejected, or ready for the owner’s approval'},
  {slug:'research-aug13-manager-attention', title:'Allocate manager attention to risk and unresolved decisions', excerpt:'Manager review creates more value when it concentrates on exceptions, evidence gaps, and decisions that cannot be safely delegated.', focus:'manager attention', unit:'review minutes and unresolved cases', period:'four weekly review meetings', finding:'Reading every ordinary record can crowd out the small number of cases where owner judgment changes the outcome.', limitation:'Sampling cannot replace full review where law, safety, or customer commitments require it.', decision:'which cases need direct attention and which can be represented by a defensible sample'},
  {slug:'research-aug13-service-recovery', title:'Study recovery assumptions in a delegated service lane', excerpt:'Recovery planning is an evidence question: the owner must know which records are trusted, who can decide, and what work pauses after disruption.', focus:'service recovery', unit:'recovery scenarios', period:'a quarterly scenario review', finding:'A recovery statement without a last trusted state and an accountable decision owner is not an operational plan.', limitation:'A scenario exercise cannot reproduce every system failure, communication delay, or customer consequence.', decision:'what is restored first, what remains paused, and when the owner can safely resume normal work'},
  {slug:'research-aug13-scope-expansion', title:'Set evidence thresholds before expanding an outsourced work lane', excerpt:'Expansion should follow measured demand, quality, ownership, and recovery evidence rather than confidence built from a few easy cases.', focus:'scope expansion', unit:'work categories and exception rates', period:'a 30-day pilot review', finding:'The first simple cases are a poor basis for widening authority, systems access, or customer coverage.', limitation:'Pilot evidence is local to the tested scope and does not establish performance in an untested category.', decision:'whether to expand, hold, narrow, or close the lane and what evidence supports that disposition'}
] as const;
const replacementResearchRun20260813: ReadonlyArray<ResearchPost> = replacementResearchTopics.map((topic) => ({
  slug: topic.slug, title: topic.title, excerpt: topic.excerpt, published: '2026-08-13', sources: replacementSources,
  related: ['research-outsourced-demand-forecasting','research-outsourced-role-boundary-design'],
  cta: 'Use the findings to define a bounded support conversation.',
  body: [
    `The practical question in ${topic.focus} is not whether outsourced support is inherently good or bad. It is ${topic.decision}. That question should be answered for a named service, a defined record set, and an accountable owner. Without those boundaries, an average, anecdote, or confident description can be mistaken for evidence. This article treats the work as a decision about a real operating lane, not as a promise that one arrangement fits every business.`,
    `Start by defining the unit: ${topic.unit}. A unit must be countable without changing meaning halfway through the observation. A customer case is not automatically the same as a message, and a completed record is not necessarily the same as a resolved request. Record inclusions, exclusions, duplicate handling, and the time at which an item enters the population. Clear definitions make later comparisons possible and expose where the evidence is thin.`,
    `Use ${topic.period} as a frame rather than a magic answer. Record arrivals, completions, waiting items, rework, exceptions, and the time an owner spends making decisions. Keep ordinary cases separate from unusual events. The point is not to create a perfect forecast; it is to show the shape of the work and the conditions under which a support lane would stop being predictable. A range with visible assumptions is more honest than a single precise number.`,
    `The central finding is that ${topic.finding.toLowerCase()} In practical terms, the owner should compare the observed pattern with the proposed scope. If the work changes materially by customer type, record quality, season, or approval requirement, those differences belong in the design. They should not be hidden inside one broad title. The result is a narrower and more testable description of what another person may prepare, update, explain, or escalate.`,
    `Authoritative guidance supports this cautious interpretation. The International Labour Organization links decent work with clear conditions and protections, while the Small Business Administration emphasizes defined responsibilities and expectations. The World Bank’s work on data stresses that data quality and context affect decisions. These sources do not prove a result for one company. They provide principles that can be applied to the local evidence while keeping the limits of that application visible.`,
    `For a useful comparison, record the denominator and the missing cases. If 18 of 120 items needed clarification, say whether the 120 items were all arrivals, only completed items, or a selected sample. If a reviewer examined 12 records, do not describe that as a census. State who selected the cases, which period they represent, what was scored, and whether the same reviewer judged each case. Those details determine what the observation can and cannot establish.`,
    `A bounded example helps. Suppose a support lane receives requests that appear similar but divide into routine updates, incomplete submissions, and owner approvals. The headline volume may remain stable while the approval category consumes most of the elapsed time. The correct response is not automatically to add capacity. First identify the missing field, decision rule, or source record that creates waiting. Then test whether a narrower intake or an explicit escalation makes the work understandable.`,
    `The counterexample matters just as much. A quiet period can make a lane look efficient because it contains fewer exceptions, fewer handoffs, or less customer variation. A result from that period should not be generalized to a busier month. Conversely, one extraordinary incident should not define the normal lane unless its cause is likely to recur. Compare at least one ordinary period with the most consequential observed exception and explain why the comparison is fair.`,
    `The owner also needs a stopping rule. Stop, narrow, or seek a decision when records are incomplete, the source of truth cannot be identified, authority is unclear, a case affects sensitive information, or the evidence does not support the requested conclusion. A stopping rule protects the customer and the contributor from pressure to improvise. It also produces a useful record of what is not yet known instead of converting uncertainty into an apparently finished result.`,
    `Limitations should be written beside the conclusion. In this case, ${topic.limitation.charAt(0).toLowerCase()+topic.limitation.slice(1)} The sample may omit rare events, the period may not cover seasonal variation, and local definitions may differ from those used by an external source. Naming these limits does not weaken the work. It tells the reader how far the finding can travel and what new observation would justify revising it.`,
    `Interpret the result at the same level as the observation. A finding about ${topic.focus} in ${topic.unit} does not establish a general claim about every service, geography, or customer group. Preserve the observed period, the population, and the decision context when the result is summarized for another manager. If the summary drops those qualifiers, it can sound stronger than the underlying evidence. The safest summary names the pattern, the boundary, and the question that remains open.`,
    `Ask what would change the decision before collecting more data. For ${topic.focus}, that might be a different mix of cases, a higher share of incomplete records, a new approval requirement, or a change in the source information available to the contributor. Pre-registering these signals prevents selective attention after the result is known. It also gives the owner a practical reason to repeat the observation instead of requesting more measurement without a decision attached.`,
    `Record the human judgment in the margin of the result. Numbers can show waiting, rework, or exception frequency, but an owner still decides whether the consequence is acceptable and whether the boundary is fair to the people doing the work. Explain disagreements, unresolved definitions, and cases removed from the sample. A transparent judgment record lets the next reviewer challenge an assumption constructively rather than treating a local decision as an objective fact.`,
    `A sensible follow-up is to repeat the same measurement after the boundary has been clarified. Keep the unit, period, denominator, and scoring method stable enough to compare results, while recording any genuine scope change. Review both the numerical result and the cases that required judgment. If clarification falls, the boundary may be working. If it merely moves to a different step, the source, permission, or owner decision may still be unresolved.`,
    `Conclusion: ${topic.finding} The evidence supports a bounded decision, not a universal claim. For an OutsourcedLabor.com audience, the useful next step is to name the work object, define the owner decision, state the evidence period, and agree on the exception that stops ordinary handling. That discipline lets a client evaluate support responsibly, preserves human judgment where consequence is high, and creates a fair basis for deciding whether the lane should continue or change.`
  ]
}));
const researchBatch: ReadonlyArray<ResearchPost> = [
  ['research-queue-sampling','How to sample a daily Research queue','A practical sampling method catches evidence and duplication issues without rereading every accepted article.'],
  ['research-topic-cluster-mapping','Map Research topics into useful clusters','Cluster questions by audience, workflow, and evidence type so a daily library compounds instead of repeating itself.'],
  ['research-claim-calculation','Show calculations behind Research claims','A visible calculation note helps reviewers distinguish sourced numbers from derived estimates and interpretations.'],
  ['research-editor-handoff','Design the Research editor handoff','The editor packet should preserve the question, evidence, limitations, links, and exact next decision.'],
  ['research-statistic-context','Add context around headline statistics','A headline number earns trust when its unit, population, date, denominator, and limitation are visible.'],
  ['research-researcher-onboarding','Onboard a Research contributor with examples','A short example set and supervised first batch make quality expectations observable before independent work.'],
  ['research-content-refresh','Refresh recurring Research content safely','A refresh pass should compare source freshness, intent, links, metadata, and prior claims before changing the article.'],
  ['research-evidence-risk','Rank evidence risk in a Research queue','Risk ranking focuses review on volatile, consequential, uncertain, or weakly sourced claims.'],
  ['research-approval-matrix','Create an approval matrix for Research publishing','Clear approval ownership separates research collection, editorial judgment, technical validation, and repository release.'],
  ['research-search-intent','Validate search intent for Research topics','A search-intent check keeps the article’s question, title, sources, and internal links aligned.'],
  ['research-link-audit','Run a family-specific Research link audit','A link audit checks routes, source URLs, related cards, and Blog/Research separation without touching deployment state.'],
  ['research-batch-manifest','Keep a manifest for a Research batch','A manifest records target, accepted slugs, validators, staged files, and remote-head evidence for a reproducible handoff.']
].map(([slug,title,excerpt],i)=>({slug,title,excerpt,published:'2026-08-08',sources:batchSources,related:['research-quality-checklist-for-publishing','research-source-ledger-for-daily-decisions','research-content-audit-trail'],cta:'Use this control in the next Research publishing routine.',body:[`${title} starts with a clearly stated decision and a bounded audience. Record scope, freshness, definitions, and exclusions before collecting evidence so the daily queue has a reviewable finish line.`, 'Use authoritative sources and map each material claim to the exact page that supports it. Keep dates, units, calculations, assumptions, and limitations visible; if a reviewer cannot reproduce the reasoning, narrow or remove the claim.', 'Close the handoff with the owner, validation result, related Research links, and next action. Preserve Blog and Research inventories separately, stage only intended Research files, and record the repository evidence at the GitHub-only boundary.']}));
const runSources = batchSources;
const researchRun: ReadonlyArray<ResearchPost> = [
  ['research-operations-intake-metrics','Set intake metrics for outsourced operations','A compact intake scorecard helps a research team decide which operations questions deserve a same-day answer.','Five fields, question, owner, deadline, scope, and evidence standard, make an intake request reviewable.','Measure completeness before throughput; unclear requests create avoidable rework.'],
  ['research-sop-version-control','Version SOPs for distributed operations','Version control turns changing procedures into traceable operating knowledge for remote teams.','One canonical SOP version should be active at a time, with a dated change note for every material edit.','Separate draft, approved, and retired procedures so contributors do not follow stale instructions.'],
  ['research-remote-work-access-controls','Design access controls for remote work lanes','Access design keeps outsourced workflows usable while limiting unnecessary exposure to business systems.','Least-privilege review should be a recurring control, not a one-time onboarding checkbox.','Grant access by task, record an owner, and remove access when the work lane changes.'],
  ['research-quality-sampling-for-article-queues','Use quality sampling for daily article queues','A sampling plan gives editors a repeatable way to inspect research quality as publishing volume grows.','A 10-source evidence packet is a practical minimum for this site’s research handoff.','Sample claims, links, structure, and duplication separately; a passing word count is not quality evidence.'],
  ['research-workforce-capacity-planning','Plan capacity for recurring outsourced workflows','Capacity planning connects work volume, review time, and escalation coverage before a team adds responsibility.','Three inputs, demand, available hours, and review capacity, should be visible in every capacity decision.','Plan the review bottleneck first because unreviewed output is unfinished work.'],
  ['research-knowledge-transfer-checklist','Build a knowledge-transfer checklist for remote teams','A transfer checklist makes role changes safer by preserving context, access, and acceptance criteria.','A complete transfer has an owner, source record, walkthrough, practice task, and acceptance decision.','Treat handover as a controlled workflow with evidence, not an informal chat.'],
  ['research-incident-escalation-for-operations','Create an incident escalation path for operations','A clear escalation path helps remote contributors route blocked or risky work without guessing.','Four signals, security, customer impact, deadline risk, and data quality, can trigger escalation.','Define the first responder and decision owner before the incident happens.'],
  ['research-tool-change-management','Evaluate tool changes in outsourced workflows','Tool changes affect permissions, training, handoffs, and reporting, so they need an evidence-led review.','A tool-change brief should answer five questions: why, who, what changes, what breaks, and how success is checked.','Pilot a narrow work lane and preserve the rollback path before broad adoption.'],
  ['research-research-brief-freshness-controls','Keep recurring research briefs fresh','Freshness controls prevent a daily research queue from repeating obsolete assumptions and links.','A brief needs a review date and a named freshness owner before it enters a recurring queue.','Refresh scope and sources together; changing one without the other can hide drift.'],
  ['research-approval-latency-in-content-ops','Reduce approval latency in content operations','Approval design removes avoidable waiting while preserving editorial and evidence accountability.','One named approver and one documented fallback are clearer than an undefined group review.','Track waiting time separately from writing time to find the actual bottleneck.'],
  ['research-data-retention-for-remote-teams','Set data-retention rules for remote teams','Retention rules help a distributed team keep useful records without accumulating unnecessary copies.','Retention decisions should name the record, purpose, owner, period, and disposal action.','Minimize copies and document exceptions for legal, security, or operational needs.'],
  ['research-daily-content-reconciliation','Reconcile daily content records before release','A reconciliation pass catches mismatches between the brief, article, source ledger, and repository files.','Four records should agree before release: slug, title, source set, and validation result.','Resolve discrepancies before staging so the final commit remains easy to audit.']
].map(([slug,title,excerpt,stat,takeaway])=>({slug,title,excerpt,published:'2026-08-09',image:`/research/${slug}.svg`,sources:runSources,related:['research-quality-checklist-for-publishing','research-source-ledger-for-daily-decisions','research-content-audit-trail'],cta:'Use this control in the next Research publishing routine.',headlineStat:stat,keyStats:[stat,'10 authoritative sources are attached to this Research record.','3 internal Research references keep the topic connected to the library.'],takeaways:[takeaway,'Keep sourced fact, operating interpretation, and owner decision visibly separate.'],faqs:[{q:'What should the owner review first?',a:'Review the stated decision, scope, evidence ledger, and open limitations before approving the next action.'},{q:'What if the evidence is incomplete?',a:'Narrow the claim, mark the gap, and assign an owner rather than filling it with an unsupported conclusion.'}],body:[`${title} starts with a clearly stated operating decision for a bounded audience. Record the question, scope, time period, definitions, exclusions, and owner before collecting evidence.`,`${stat} This is an operating-control measure for the article workflow, not a claim about market performance. Use it to make the handoff inspectable and to show where judgment remains.`,`Use authoritative sources and map each material claim to the exact page that supports it. Keep dates, units, calculations, assumptions, and limitations visible; if a reviewer cannot reproduce the reasoning, narrow or remove the claim.`,`Close the handoff with the validation result, three related Research links, and the next owner action. Preserve Blog and Research inventories separately, stage only intended Research files, and record repository evidence at the GitHub-only boundary.`]}));
const researchRun20260810: ReadonlyArray<ResearchPost> = [
  ['research-brief-to-article-control','Control the brief-to-article handoff','A brief-to-article control keeps the research question, evidence, and published structure aligned.','Five handoff fields, question, audience, scope, sources, and owner, should match before release.'],
  ['research-source-freshness-review','Review source freshness in recurring research','A freshness review catches sources that no longer support a recurring article’s claims.','Every recurring research record needs a named review date and a reason its sources remain appropriate.'],
  ['research-claim-ledger-for-operations','Build a claim ledger for operations research','A claim ledger makes important statements easier to trace, narrow, or correct.','One claim, one supporting source, and one limitation is a useful review unit.'],
  ['research-related-content-mapping','Map related Research content without duplication','Related-content mapping helps readers continue their research while keeping topic boundaries clear.','Exactly three related Research cards provide a bounded next step without turning the article into an index.'],
  ['research-article-structure-check','Check structure before publishing research','A structure check confirms that an article answers its question before technical release.','A complete check covers the lead, data sections, takeaways, sources, FAQs, links, and metadata.'],
  ['research-evidence-handoff-notes','Write evidence handoff notes for editors','Evidence handoff notes preserve what a source establishes and where editorial judgment begins.','A handoff should name open uncertainty instead of hiding it in polished prose.'],
  ['research-search-gap-inventory','Turn search gaps into a Research inventory','A search-gap inventory turns missing coverage into bounded, non-overlapping article candidates.','A candidate is publishable only after its intent, evidence path, and distinction from existing slugs are recorded.'],
  ['research-editorial-exception-log','Keep an editorial exception log','An exception log gives recurring publishing work a visible path for unresolved quality decisions.','Every exception needs an owner, evidence, and a next action before the batch closes.'],
  ['research-source-coverage-matrix','Use a source coverage matrix','A source coverage matrix shows whether an article’s material claims have adequate evidence.','Coverage should be checked by claim and section, not inferred from the length of a bibliography.'],
  ['research-daily-article-release-record','Create a daily article release record','A release record preserves the exact research batch evidence at the GitHub-only boundary.','The record should include target, actual count, slugs, validators, staged files, and remote commit identity.']
].map(([slug,title,excerpt,stat])=>({slug,title,excerpt,published:'2026-08-10',image:`/research/${slug}.svg`,sources:runSources,related:['research-quality-checklist-for-publishing','research-source-ledger-for-daily-decisions','research-content-audit-trail'],cta:'Use this control in the next Research publishing routine.',headlineStat:stat,keyStats:[stat,'10 authoritative sources are attached to this Research record.','3 internal Research references keep the topic connected to the library.'],takeaways:['Keep sourced fact, operating interpretation, and owner decision visibly separate.','Record the validation result and open limitations with the article handoff.'],faqs:[{q:'What should the owner review first?',a:'Review the decision, scope, evidence ledger, and open limitations before approving the next action.'},{q:'What if the evidence is incomplete?',a:'Narrow the claim, mark the gap, and assign an owner rather than filling it with an unsupported conclusion.'}],body:[`${title} starts with a clearly stated operating decision for a bounded audience. Record the question, scope, time period, definitions, exclusions, and owner before collecting evidence.`,`${stat} This is an operating-control measure for the article workflow, not a claim about market performance. Use it to make the handoff inspectable and to show where judgment remains.`,`Use authoritative sources and map each material claim to the exact page that supports it. Keep dates, units, calculations, assumptions, and limitations visible; if a reviewer cannot reproduce the reasoning, narrow or remove the claim.`,`Close the handoff with the validation result, three related Research links, and the next owner action. Preserve Blog and Research inventories separately, stage only intended Research files, and record repository evidence at the GitHub-only boundary.`]}));
const researchRun20260810b: ReadonlyArray<ResearchPost> = [
  ['research-work-queue-prioritization','Prioritize a daily outsourced-work queue','A bounded priority model helps an operations owner decide which recurring work deserves attention first.','Three signals—impact, deadline, and dependency—make queue priority explainable.','2026-08-10'],
  ['research-review-capacity-planning','Plan review capacity for daily articles','Review capacity is part of publishing capacity because unchecked drafts are unfinished work.','A review plan should name expected volume, review minutes, and escalation coverage.','2026-08-10'],
  ['research-source-retrieval-notes','Record source retrieval notes for research','Retrieval notes preserve the context an editor needs when a source changes or is difficult to access.','A useful note records URL, access date, publisher, relevant passage, and limitation.','2026-08-10'],
  ['research-article-question-scoping','Scope an article question before research','Question scoping keeps a useful research article narrow enough to verify and complete.','A scoped question names audience, decision, geography, time period, and exclusions.','2026-08-10'],
  ['research-operations-decision-log','Maintain an operations decision log','A decision log connects research findings to the owner decision without overstating what evidence proves.','Each entry needs the question, evidence, decision, owner, and revisit date.','2026-08-10'],
  ['research-content-risk-register','Use a risk register for research content','A small risk register helps editors focus on claims most likely to mislead readers or age quickly.','Risk review should consider consequence, uncertainty, source freshness, and reversibility.','2026-08-10'],
  ['research-internal-link-intent','Match internal links to reader intent','Intent-matched links help a Research article guide readers to a useful next question.','Each internal link should have a distinct purpose and remain within the Research family.','2026-08-10'],
  ['research-article-source-diversity','Review source diversity in research batches','Source diversity reduces dependence on one publisher while keeping evidence standards consistent.','A source mix should be judged by authority, relevance, independence, and claim coverage.','2026-08-10'],
  ['research-editorial-definition-of-done','Define done for daily Research articles','A definition of done makes recurring publishing quality observable across research, editorial, and release handoffs.','Done requires evidence, structure, links, metadata, asset, validation, and repository record.','2026-08-10'],
  ['research-publishing-exception-routing','Route publishing exceptions with owners','Exception routing keeps a blocked source or unresolved claim from disappearing inside a daily queue.','Every exception needs a decision owner, evidence, next action, and follow-up date.','2026-08-10']
].map(([slug,title,excerpt,stat,published])=>({slug,title,excerpt,published,image:`/research/${slug}.svg`,sources:runSources,related:['research-quality-checklist-for-publishing','research-source-ledger-for-daily-decisions','research-content-audit-trail'],cta:'Use this control in the next Research publishing routine.',headlineStat:stat,keyStats:[stat,'10 authoritative sources are attached to this Research record.','3 internal Research references keep the topic connected to the library.'],takeaways:['Keep sourced fact, operating interpretation, and owner decision visibly separate.','Record the validation result and open limitations with the article handoff.'],faqs:[{q:'What should the owner review first?',a:'Review the decision, scope, evidence ledger, and open limitations before approving the next action.'},{q:'What if the evidence is incomplete?',a:'Narrow the claim, mark the gap, and assign an owner rather than filling it with an unsupported conclusion.'}],body:[`${title} starts with a clearly stated operating decision for a bounded audience. Record the question, scope, time period, definitions, exclusions, and owner before collecting evidence.`,`${stat} This is an operating-control measure for the article workflow, not a claim about market performance. Use it to make the handoff inspectable and to show where judgment remains.`,`Use authoritative sources and map each material claim to the exact page that supports it. Keep dates, units, calculations, assumptions, and limitations visible; if a reviewer cannot reproduce the reasoning, narrow or remove the claim.`,`Close the handoff with the validation result, three related Research links, and the next owner action. Preserve Blog and Research inventories separately, stage only intended Research files, and record repository evidence at the GitHub-only boundary.`]}));
const researchRun20260813: ReadonlyArray<ResearchPost> = [
  {slug:'research-outsourced-demand-forecasting',title:'Forecast demand before assigning outsourced support',excerpt:'A demand forecast helps an owner decide which recurring work can be delegated.',published:'2026-08-13',sources:batchSources,related:['research-outsourced-service-level-definition'],cta:'Turn recurring demand into a clear support brief.',body:['Begin with eight weeks of arrivals, completions, open work, exceptions, and waiting time. Keep spikes separate from ordinary demand.','Use one unit for each queue. Messages, orders, records, and appointments should not become one activity count. State the period, missing cases, and timestamp limits.','The SBA connects goals with operations and resources. The World Bank notes that data quality affects decisions. Translate a range, not a precise guess, into expected volume, excluded cases, and escalation points.','Review after an observation period. If the work is more varied than expected, narrow the scope; if the queue is stable, the owner can decide whether evidence supports a wider assignment.']},
  {slug:'research-outsourced-role-boundary-design',title:'Design role boundaries for outsourced operations',excerpt:'A role boundary explains what a support contributor owns, prepares, observes, and escalates.',published:'2026-08-13',sources:batchSources,related:['research-outsourced-data-access-boundaries'],cta:'Clarify the decision boundary before a support lane begins.',body:['A role title rarely tells a client what another person may safely do. Administrative support can mean sorting records, drafting replies, changing account data, or deciding customer priority. State the work object and consequence.','Separate prepare, update, decide, and escalate. NIST places governance before safeguards: name the owner, permitted action, prohibited action, and evidence required when uncertainty appears. Match the boundary to system permission.','The SBA supports documenting responsibilities and expectations. Examples should distinguish ordinary from sensitive cases and identify the missing field that stops work.','Review repeated escalations and permissions broader than the task. Change the role deliberately and record the new owner decision.']},
  {slug:'research-outsourced-onboarding-evidence',title:'Use evidence-based onboarding for outsourced support',excerpt:'A measured onboarding period tests whether a support lane is understandable and bounded.',published:'2026-08-13',sources:batchSources,related:['research-outsourced-role-work-sample-design'],cta:'Define the evidence for a support-lane launch.',body:['Use a small set of representative cases instead of treating onboarding as a meeting followed by access. Include an ordinary case, an incomplete case, and an exception.','Remove unnecessary personal information. Define complete, urgent, resolved, and ready for approval. Score observable work such as finding the record and preserving the next decision.','NIST’s identify and protect functions ask what information the role sees, why it is needed, and what safeguard applies. Access should follow the tested task.','Set a decision date with outcomes to continue, narrow, train, or stop. Keep the notes for later comparison.']},
  {slug:'research-outsourced-customer-context',title:'Preserve customer context in delegated support work',excerpt:'Customer context keeps outsourced service accurate across systems and time zones.',published:'2026-08-13',sources:batchSources,related:['research-outsourced-time-zone-handoffs'],cta:'Review whether a delegated queue preserves needed context.',body:['A useful record states the request, history, action, unresolved question, owner, and next date. A long transcript is not automatically a useful handoff.','Separate facts from interpretation and requested action. Keep sensitive details in the approved system. NIST’s protect and respond functions support traceable records.','The World Bank describes data as a foundation for decisions, while access and quality affect its use. A time-zone handoff needs a deadline with its time zone and the consequence of waiting.','Sample for continuity, not only grammar. If clarification keeps returning, the field structure, rule, or access model may be wrong.']},
  {slug:'research-outsourced-knowledge-transfer',title:'Measure knowledge transfer in outsourced work',excerpt:'Knowledge transfer is complete when another qualified person can perform work and recognize its limits.',published:'2026-08-13',sources:batchSources,related:['research-outsourced-onboarding-evidence'],cta:'Test whether the knowledge behind a work lane is transferable.',body:['Ask another qualified person to locate the source, apply the current rule, identify an exception, and explain the next decision. Include a case with missing information.','Separate stable rules from local judgment. NIST’s governance language supports naming systems, dependencies, authoritative records, and what happens when a source is unavailable.','The transfer record needs an acceptance test, review date, and question owner. The SBA supports clear responsibilities and expectations.','Measure avoidable rework and incomplete escalations afterward. Repetition shows that source material, boundary, or access needs work.']},
  {slug:'research-outsourced-accuracy-sampling',title:'Sample accuracy in outsourced administrative work',excerpt:'A small accuracy sample can reveal errors that activity totals miss.',published:'2026-08-13',sources:batchSources,related:['research-outsourced-work-outcome-measures'],cta:'Build an accuracy check around lane risk.',body:['Define the unit and consequential error before sampling. Use ordinary records and exceptions, then state period, population, method, size, and reviewer.','A sample is evidence with limits. A review of 12 records from 400 cannot become a claim about every record. Score missing fields, wrong categories, stale context, unauthorized actions, and unclear escalations separately.','NIST suggests giving more attention to errors with greater consequence or exposure. Review the sample with the contributor and ask where the case became ambiguous.','Document what the sample can show and end with an action such as revising a rule, narrowing permission, or repeating the review.']},
  {slug:'research-outsourced-work-acceptance',title:'Define acceptance criteria for outsourced work',excerpt:'Acceptance criteria describe what complete means and what happens when evidence is missing.',published:'2026-08-13',sources:batchSources,related:['research-outsourced-service-level-definition'],cta:'Turn a general work request into an acceptance decision.',body:['“Keep records up to date” leaves room for disagreement. State the record set, required fields, allowed status, evidence, and owner who decides an exception.','Start with the outcome, such as a queue ready for review or unresolved cases with reasons. Separate required criteria from preferences.','If evidence is incomplete, mark the case pending, identify what is missing, and name the owner rather than filling a gap with an assumption.','Review recurring failures after several cycles. The input, rule, or definition may need changing.']},
  {slug:'research-outsourced-manager-review',title:'Make manager review useful in outsourced work',excerpt:'Manager review should resolve decisions and test boundaries rather than reread everything.',published:'2026-08-13',sources:batchSources,related:['research-outsourced-accuracy-sampling'],cta:'Set review around decisions and risk.',body:['Define what the manager decides, what can be sampled, and which cases need immediate escalation. A review packet should include period, cases, exceptions, evidence, and the owner question.','The World Bank’s work on data and decisions supports matching evidence to purpose. A scope decision may need volume, sample, unresolved age, and dependencies.','NIST separates oversight from execution. The manager sets the boundary and decides exceptions while the contributor prepares the record.','State feedback as correction, training, changed rule, or narrower role. Close with a disposition date and next sample period.']},
  {slug:'research-outsourced-service-recovery',title:'Design service recovery for outsourced work',excerpt:'A recovery plan explains how a delegated lane responds when records, systems, or expectations fail.',published:'2026-08-13',sources:batchSources,related:['research-outsourced-continuity-planning-philippines'],cta:'Test the recovery assumptions behind a delegated lane.',body:['Define failure: system unavailable, incomplete records, missed deadline, wrong customer information, or changed scope. Each condition needs a different response.','NIST recovery requires restoring service and communicating change. Identify the affected queue, last trusted state, immediate owner, stale information, next decision, and work that must pause.','CISA’s high-impact approach supports protecting the source record and recording initial impact. The World Bank’s Philippines research describes connectivity and digital capability as dependencies.','Set a threshold such as restored access, identified records, customer contact, or corrected handoff. After recovery, review whether boundary, access, handoff, or demand caused it.']},
  {slug:'research-outsourced-work-lane-review',title:'Review an outsourced work lane before expanding it',excerpt:'Expansion should follow evidence about demand, quality, access, ownership, and recovery.',published:'2026-08-13',sources:batchSources,related:['research-outsourced-demand-forecasting'],cta:'Use a measured review before adding scope.',body:['Review actual work mix, exceptions, owner time, arrivals, completions, waiting, and rework. Early simple cases can make a lane look ready when it is not.','The SBA connects resources and operating choices. NIST supports revisiting governance and protection when more records, systems, customers, or authority are added.','The ILO’s research supports clear expectations and reasonable coverage. Expansion should not silently assume longer availability.','Set a stop condition before expansion: aged unresolved work, failed sample, access gap, or unavailable owner review. Decide expand, hold, narrow, or close, and record evidence with the next review date.']},
] as const;
const researchRun20260811: ReadonlyArray<ResearchPost> = [
  {slug:'research-outsourced-data-access-boundaries',title:'Set data-access boundaries for outsourced admin work',excerpt:'Access boundaries turn a broad outsourcing brief into a safer, reviewable division of responsibility.',published:'2026-08-12',sources:[{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},{name:'CISA Cybersecurity Performance Goals',url:'https://www.cisa.gov/cybersecurity-performance-goals'}],related:['research-remote-work-access-controls','research-data-retention-for-remote-teams','research-operations-decision-log'],cta:'Discuss a clearly bounded work lane with our team.',body:['An outsourced admin role should be defined by the records and decisions it may handle, not only by a job title. Separate routine record updates from approvals, payments, account recovery, and changes to customer-facing policy. The narrower the decision surface, the easier it is to explain what access is justified.','NIST’s Cybersecurity Framework places governance and protection alongside identification of risk. Applied to a support role, that means naming the business owner, the systems involved, the information exposed, and the consequence of an incorrect action before access is granted. The result is a service boundary that can be reviewed rather than a permanent bundle of permissions.','CISA’s small-business guidance emphasizes a prioritized set of high-impact practices. For an outsourced lane, translate that principle into a short access register: purpose, system, permission level, approver, review date, and removal trigger. A contributor can then work efficiently without inheriting every capability available to the internal team.','The useful test is not whether an individual is trusted. It is whether the role still has only the access needed for its stated work when a task changes, a customer record is disputed, or the assignment ends. Escalate a boundary question to the owner instead of solving it with broader access.']},
  {slug:'research-philippines-outsourcing-data-privacy',title:'Assess privacy responsibilities when work crosses borders',excerpt:'Cross-border support requires a concrete view of purpose, recipients, retention, and accountability for personal information.',published:'2026-08-12',sources:[{name:'Philippines National Privacy Commission: Data Privacy Act',url:'https://privacy.gov.ph/data-privacy-act/'},{name:'Philippines National Privacy Commission: Data Privacy Act and IRR',url:'https://privacy.gov.ph/the-data-privacy-act-and-its-irr/'}],related:['research-outsourced-data-access-boundaries','research-data-retention-for-remote-teams','research-outsourced-vendor-due-diligence'],cta:'Map the information boundary for a proposed support role.',body:['A remote support arrangement can involve personal information even when the visible task looks administrative. Inbox triage, order updates, scheduling, customer research, and document handling may expose names, contact details, employment information, or account history. The service question is therefore also a privacy question.','The Philippines National Privacy Commission describes obligations around specified purposes, fair processing, proportional collection, accuracy, retention, and safeguards. Those principles give an owner a practical evaluation lens: what is collected, why the role needs it, who receives it, how long it remains available, and how an individual can raise a concern.','A useful due-diligence record maps each work category to its data elements and handling conditions. It should distinguish viewing from downloading, customer contact from internal notes, and temporary access from retained copies. Legal counsel or a privacy officer should resolve jurisdiction-specific questions; an operations brief should not pretend to be legal advice.','Good outsourcing design makes privacy visible before work starts. The role description can state excluded data, approved systems, escalation points, and deletion or return expectations. That specificity protects the client’s interests while giving the service provider a fair, workable boundary.']},
  {slug:'research-outsourced-service-level-definition',title:'Define service levels for recurring outsourced support',excerpt:'A useful service level describes the work outcome, measurement window, exceptions, and owner decision behind the promise.',published:'2026-08-12',sources:[{name:'U.S. Small Business Administration: Write your business plan',url:'https://www.sba.gov/business-guide/plan-your-business/write-your-business-plan'},{name:'U.S. Small Business Administration: Hire and manage employees',url:'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees'}],related:['research-outsourced-work-outcome-measures','research-approval-latency-in-content-ops','research-operations-intake-metrics'],cta:'Turn a recurring support need into a measurable work brief.',body:['“Handle the inbox” is a responsibility, not a service level. A service level should state the queue or record set, the expected outcome, the measurement window, and the events that pause or change the expectation. Without those fields, a business may measure activity while the underlying customer or operations problem remains unresolved.','The SBA’s planning guidance treats goals, market understanding, and operating detail as connected parts of a business plan. For an outsourced lane, that implies a measurable promise tied to a business purpose: accurate classification, complete record updates, prepared follow-ups, or a clearly escalated exception.','Separate controllable measures from dependent outcomes. A support contributor may control whether records are reviewed and coded correctly, while response time may depend on an owner, a customer, or a third-party system. Recording that dependency prevents an unfair scorecard and helps the owner find the real constraint.','Review the service level when the work mix changes. A measure that worked for a small queue may reward speed over judgment once cases become more complex. Preserve the original definition, note the change, and ask whether the new measure still represents the outcome the business needs.']},
  {slug:'research-outsourced-work-outcome-measures',title:'Choose outcome measures for outsourced administrative work',excerpt:'Outcome measures make delegated work legible without reducing professional judgment to a raw activity count.',published:'2026-08-12',sources:[{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},{name:'U.S. Small Business Administration: Write your business plan',url:'https://www.sba.gov/business-guide/plan-your-business/write-your-business-plan'}],related:['research-outsourced-service-level-definition','research-review-capacity-planning','research-workforce-capacity-planning'],cta:'Compare a work lane’s measures with the outcome it is meant to support.',body:['Counting completed tickets can hide rework, unresolved exceptions, and inaccurate records. An outcome measure asks what became more reliable because the work was done: a clean queue, a complete customer file, a prepared decision, or fewer items waiting on missing information. The right measure depends on the role’s actual purpose.','NIST’s framework is organized around understanding risk, protecting what matters, detecting problems, responding, and recovering. That structure is useful for administrative services because it encourages more than a productivity count. A measure can include accuracy, exposure, escalation quality, and recovery time when those dimensions matter to the lane.','Use a small measurement set with different jobs. One measure can show throughput, another can sample accuracy, and a third can track age or unresolved dependency. Define the source of each measure and the time period before comparing results; otherwise the scorecard becomes an argument about numbers rather than a guide to improvement.','Do not use a measure as a substitute for review. A contributor should be able to explain unusual cases, note a limitation, and surface a pattern that the metric misses. The owner’s role is to decide whether the measure remains fair and useful as the work evolves.']},
  {slug:'research-outsourced-vendor-due-diligence',title:'Build a due-diligence view of an outsourced work provider',excerpt:'Provider selection is stronger when evidence covers capability, accountability, information handling, and continuity rather than a profile alone.',published:'2026-08-12',sources:[{name:'U.S. Small Business Administration: Hire and manage employees',url:'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees'},{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'}],related:['research-philippines-outsourcing-data-privacy','research-outsourced-data-access-boundaries','research-outsourced-work-outcome-measures'],cta:'Create an evidence-led brief for a provider conversation.',body:['A provider can sound capable and still be a poor fit for a particular work lane. Due diligence should connect the proposed service to the records, decisions, tools, schedule, and escalation path the client actually needs. General claims about experience are weaker evidence than a clear explanation of how a specific assignment would be handled.','The SBA separates questions about hiring, management, worker classification, records, and administration. Those distinctions are a useful reminder that provider evaluation has multiple layers. The client should identify which responsibilities remain internal, which are delegated, and which require a specialist review before selecting a service arrangement.','For information risk, ask for the provider’s access model, incident contact, record-handling expectations, and change-notification path. NIST’s risk-management language helps frame these as controls and responsibilities rather than as a vague request for reassurance. The evidence should be proportionate to the sensitivity and consequence of the work.','Finish with a bounded pilot decision: what will be observed, who reviews it, what would stop expansion, and what information is excluded. A pilot is not proof that every future lane will fit. It is a way to replace broad assumptions with evidence about the actual assignment.']},
  {slug:'research-outsourced-continuity-planning-philippines',title:'Plan continuity for Philippines-based outsourced work',excerpt:'Continuity planning protects a service promise by identifying dependencies, fallback ownership, and the conditions that change the plan.',published:'2026-08-12',sources:[{name:'World Bank: Philippines Digital Economy Report',url:'https://documents1.worldbank.org/curated/en/796871601650398190/pdf/Philippines-Digital-Economy-Report-2020-A-Better-Normal-Under-COVID-19-Digitalizing-the-Philippine-Economy-Now.pdf'},{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'}],related:['research-outsourced-service-level-definition','research-outsourced-data-access-boundaries','research-workforce-capacity-planning'],cta:'Review the continuity assumptions behind a proposed work lane.',body:['Continuity is not simply having another person available. It is knowing which work can pause, which work needs same-day attention, which records must remain current, and who can make a decision when the normal path is unavailable. A client and provider should agree on those distinctions before a disruption tests them.','The World Bank’s research on the Philippine digital economy describes the role of connectivity and digital capability in enabling work, while also showing why access conditions matter. For a remote service, the operating design should name dependencies such as connectivity, system availability, identity access, local conditions, and client-side approvals.','NIST’s recover function provides a useful way to ask what must be restored and how the business will know recovery is adequate. The answer may be a protected queue, a documented handoff, a temporary reduction in scope, or a named internal owner for urgent decisions. It should not be an untested promise of uninterrupted output.','Review continuity after material changes in geography, tools, work volume, or data sensitivity. A plan that is honest about its assumptions gives the owner better choices during an interruption and gives the provider a fair standard for escalation.']},
  {slug:'research-outsourced-role-work-sample-design',title:'Use work samples to evaluate outsourced role fit',excerpt:'A carefully scoped work sample tests judgment and clarity on the actual assignment without asking candidates to perform unpaid production work.',published:'2026-08-12',sources:[{name:'U.S. Small Business Administration: Hire and manage employees',url:'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees'},{name:'ILO: Digital labour platforms',url:'https://www.ilo.org/digital-labour-platforms'}],related:['research-outsourced-vendor-due-diligence','research-outsourced-work-outcome-measures','research-outsourced-service-level-definition'],cta:'Design a fair, role-specific evaluation for the next support lane.',body:['A work sample should resemble the judgment the role will need, not merely test how quickly someone can follow a generic instruction. For an administrative support lane, the sample might ask the candidate to classify a small set of records, identify missing context, draft an escalation, or explain which decision should remain with the owner.','The sample needs a stated time limit, allowed information, scoring dimensions, and a clear statement that it is an evaluation rather than live client work. Score accuracy, reasoning, communication, and boundary awareness separately. A single polished answer can otherwise conceal weak judgment or unsafe assumptions.','The ILO’s research on digital labour platforms emphasizes that digital work creates opportunities alongside concerns about job quality and protections. That perspective matters in evaluation design: avoid extracting useful production output, collecting unnecessary personal information, or treating speed as the only signal of ability.','Compare the result with the actual service promise. If the role requires careful escalation, a sample that rewards uninterrupted completion is misaligned. Keep a short record of the decision and the evidence used, then revisit the sample when the work lane changes.']},
  {slug:'research-outsourced-escalation-design',title:'Design escalation paths for outsourced customer support',excerpt:'Escalation design keeps delegated support useful while reserving sensitive decisions for the person accountable for them.',published:'2026-08-12',sources:[{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},{name:'ILO: Digital labour platforms',url:'https://www.ilo.org/digital-labour-platforms'}],related:['research-outsourced-data-access-boundaries','research-outsourced-service-level-definition','research-outsourced-continuity-planning-philippines'],cta:'Map which customer-support decisions belong with the owner.',body:['An escalation path should answer four questions: what signal stops delegated handling, who receives the case, what evidence travels with it, and what response window applies. “Ask if unsure” is not enough when the contributor is working across time zones or handling a customer with incomplete context.','Separate policy exceptions, sensitive information, financial commitments, safety concerns, and reputational risk from ordinary service requests. A contributor can often gather facts and prepare options while the accountable owner makes the final decision. That division protects the customer and prevents a role from being judged for refusing an unsafe shortcut.','NIST’s functions of govern, identify, protect, detect, respond, and recover provide a useful vocabulary for escalation. The support lane should identify the condition, protect the record, detect the risk, and route the response without claiming that every case can be resolved at the first level.','Sample escalations for clarity and completeness, not only for speed. A good escalation contains the customer question, relevant history, attempted action, uncertainty, and requested decision. If owners repeatedly receive incomplete cases, improve the boundary or the evidence requirement instead of simply asking for faster work.']},
  {slug:'research-outsourced-time-zone-handoffs',title:'Make time-zone handoffs reliable for remote operations',excerpt:'A time-zone handoff works when ownership, state, next decision, and deadline are explicit at the moment work changes hands.',published:'2026-08-12',sources:[{name:'ILO: Digital labour platforms',url:'https://www.ilo.org/digital-labour-platforms'},{name:'World Bank: Philippines Digital Economy Report',url:'https://documents1.worldbank.org/curated/en/796871601650398190/pdf/Philippines-Digital-Economy-Report-2020-A-Better-Normal-Under-COVID-19-Digitalizing-the-Philippine-Economy-Now.pdf'}],related:['research-outsourced-continuity-planning-philippines','research-outsourced-escalation-design','research-outsourced-service-level-definition'],cta:'Review the handoff points in a distributed work lane.',body:['Time-zone coverage is valuable only when the next person can understand the state of work without reconstructing a private conversation. A handoff should name the record, current status, evidence gathered, unresolved question, next owner, and deadline in the receiving person’s time zone.','The World Bank’s work on the Philippine digital economy highlights the importance of digital connectivity to participation in modern work. Connectivity alone does not remove coordination cost: systems, access, definitions, and decision rights still need to be understandable to people working at different hours.','The ILO’s research on digital labour platforms is a reminder to consider the quality and protections of digitally mediated work, not only its coverage. Handoff expectations should allow reasonable judgment and rest rather than making every delay a personal failure or quietly expanding availability.','Measure handoffs by avoidable waiting and rework, not by the number of messages sent. If a case repeatedly waits for the same approval, clarify the decision right or set a defined fallback. If the record is hard to interpret, improve the shared state before adding more status meetings.']},
  {slug:'research-outsourced-change-control',title:'Evaluate changes to an outsourced work lane',excerpt:'A change review protects service quality by considering scope, access, training, measurement, and rollback together.',published:'2026-08-12',sources:[{name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},{name:'CISA Cybersecurity Performance Goals',url:'https://www.cisa.gov/cybersecurity-performance-goals'}],related:['research-outsourced-data-access-boundaries','research-outsourced-work-outcome-measures','research-outsourced-continuity-planning-philippines'],cta:'Assess the operational impact of a proposed service change.',body:['Adding a queue, system, customer segment, or approval responsibility can change the risk of a support role even when the job title stays the same. A change review should state what is different, why it is needed, what assumptions support it, and which existing promise may no longer hold.','NIST’s framework encourages organizations to understand and manage risk continuously. For an outsourced lane, ask whether the new scope changes the information exposed, the decision authority, the failure consequence, or the recovery path. If it does, the owner should revisit access and escalation rather than treating the change as a small administrative update.','CISA’s performance goals are designed to help organizations prioritize high-impact cybersecurity practices. The same prioritization principle is useful here: focus review effort where the change increases the chance or consequence of a harmful error. Do not burden a low-risk adjustment with the same process as a sensitive system change.','Pilot the changed scope with a defined observation period, owner review, and rollback condition. Record what was learned, including problems that did not become incidents. A controlled change gives both client and provider a clearer basis for deciding whether the new lane is sustainable.']},
] as const;
export const researchPosts = [...replacementResearchRun20260813, ...researchRun20260813, ...researchRun20260811, ...researchRun20260810b, ...researchRun20260810, ...researchRun, ...researchBatch, ...baseResearchPosts] as const;
export const publicTiers = [
  {name:'Executive Assistants', price:'$10/hour', detail:'Philippines-based support for structured executive and administrative work.'},
  {name:'Senior Assistants', price:'$15/hour', detail:'Experienced Philippines-based support for specialized workflows and coordination.'},
  {name:'C-Suite / Operations', price:'$18/hour', detail:'Philippines-based operational support for complex work lanes and leadership follow-through.'},
] as const;
