export const sep10BlogTopics = [
  ['philippines-content-operations-publish-readiness-check', 'A Publish-Readiness Check for a Philippines Content Operations Team', 'publish readiness', 'publish-readiness card', 'assigned brief, draft version, fact-check result, link check, image path, approver, and release status'],
  ['outsourced-labor-customer-data-correction-queue', 'Design a Safe Customer Data Correction Queue for Outsourced Staff', 'customer data corrections', 'correction request record', 'requester, record identifier, authoritative source, proposed change, risk flag, approver, and completion evidence'],
  ['filipino-virtual-assistant-calendar-buffer-rules', 'Set Calendar Buffer Rules a Filipino Virtual Assistant Can Apply', 'calendar buffer rules', 'calendar-rule sheet', 'meeting type, minimum buffer, travel need, preparation owner, exception trigger, and final approver'],
  ['philippines-ecommerce-catalog-change-verification', 'Verify Ecommerce Catalog Changes Before They Reach Customers', 'catalog change verification', 'catalog verification log', 'product identifier, approved source, fields changed, preview link, discrepancy, reviewer, and publish decision'],
  ['outsourced-labor-shared-inbox-ownership-map', 'Map Ownership in a Shared Inbox Before Adding Outsourced Support', 'shared inbox ownership', 'inbox ownership map', 'message class, first action, decision owner, response target, escalation condition, and closure rule'],
  ['filipino-operations-specialist-recurring-report-proof', 'Require Proof Behind Every Recurring Operations Report', 'recurring report evidence', 'report proof sheet', 'metric definition, source query, extraction time, period, exception note, reviewer, and approved output'],
  ['philippines-vendor-onboarding-document-gap-check', 'Find Document Gaps in Vendor Onboarding Without Making the Decision', 'vendor onboarding document checks', 'document-gap checklist', 'vendor identifier, required document, received version, validity check, missing item, decision owner, and next contact date'],
  ['outsourced-labor-knowledge-base-stale-answer-review', 'Review Stale Knowledge-Base Answers Before They Create Rework', 'knowledge-base freshness', 'stale-answer review', 'article owner, last verified date, linked policy, changed fact, affected replies, and approval status'],
  ['filipino-customer-support-case-linking-rules', 'Give Filipino Support Staff Clear Rules for Linking Related Cases', 'support case linking', 'case-link note', 'primary case, related case, matching evidence, privacy boundary, proposed relationship, and reviewer decision'],
  ['philippines-admin-recurring-task-missed-run-check', 'Catch Missed Runs in a Recurring Admin Task Schedule', 'recurring task completion', 'missed-run register', 'task name, expected run, completion proof, failure reason, service effect, recovery owner, and next check'],
  ['outsourced-labor-document-version-retirement-routine', 'Retire Superseded Documents Without Losing the Audit Trail', 'document version retirement', 'version-retirement record', 'document owner, current version, superseded version, effective date, replacement link, archive location, and approval'],
  ['filipino-research-assistant-source-claim-matrix', 'Use a Source-Claim Matrix for Filipino Research Assignments', 'claim verification', 'source-claim matrix', 'draft claim, primary source, supporting passage, publication date, conflict note, confidence boundary, and reviewer'],
] as const;

export const sep10BlogPosts = sep10BlogTopics.map(([slug, title, focus]) => ({ slug, title, excerpt: `A practical guide to ${focus} in a bounded Philippines-based work lane.`, minutes: 10 }));
