import type { Metadata } from 'next';
import { CTA, Footer, Header, JsonLd } from './components';
import { sep10BlogTopics } from './sep10-records';

const published = '2026-09-10', visible = 'September 10, 2026', site = 'https://outsourcedlabor.com';
const hero = '/illustrations/getillustrations/goodle-team/operations-review.svg';
const articles = sep10BlogTopics.map(([slug, title, focus, artifact, fields]) => ({ slug, title, description: `A practical guide to ${focus} in a bounded Philippines-based work lane.`, sections: [
  [`Start with the decision the record supports`, `A useful ${artifact} begins with one decision or handoff. Write down the event that opens the record, the person allowed to act, and the condition that closes it. This keeps ${focus} tied to real work instead of a broad job description.`, `Capture ${fields}. A reviewer should understand the saved state without searching private messages or asking the original operator to reconstruct it.`],
  ['Separate preparation from authority', 'List the routine steps a specialist may finish and the cases that need an accountable owner. Preparation can include collecting records, comparing fields, drafting a note, and flagging a mismatch. Approval stays with the person who owns the policy, money, access, deletion, or customer commitment.', 'Give each stop condition a named route. The handoff should include the source, unresolved point, deadline, and specific decision requested. A clear stop is part of good work, not a failure to finish.'],
  ['Check the source before changing the record', 'Name the authoritative system, policy, or approved instruction for each field that matters. Record the version or access time when the source can change. If two approved sources disagree, preserve both and pause only the affected action.', 'Copies used for coordination should link back to the source. They should not quietly become a second authority. Restrict sensitive details to the approved system and use individual accounts with the smallest useful permission.'],
  ['Pilot with cases that expose weak rules', 'Test an ordinary item, an incomplete item, a conflicting-source item, and a case that crosses an approval boundary. Ask another authorized person to resume from the saved record. Note every question that the record failed to answer.', `Revise the ${artifact} when those questions reveal a missing definition or owner. Do not solve ambiguity by adding optional fields that nobody reviews. Each field should change an action, support a check, or preserve evidence.`],
  ['Review evidence and close the loop', 'Sample completed and waiting items. Check whether the source supports the action, the boundary was respected, the exception reached the right owner, and the closure evidence matches the stated result.', `Close the ${artifact} when the acceptance condition is visible. If work remains, record the next owner and check date. Repeated problems should lead to a specific change in the source, example, permission, or rule, followed by another bounded test.`],
]}));
export const sep10BlogArticles = Object.fromEntries(articles.map((article) => [article.slug, article]));
export function getSep10BlogMetadata(slug: string): Metadata { const a = sep10BlogArticles[slug], canonical = `${site}/blog/${slug}`; return { title: a.title, description: a.description, alternates: { canonical }, openGraph: { title: a.title, description: a.description, url: canonical, type: 'article', publishedTime: published, images: [hero] } }; }
export function renderSep10BlogArticle(slug: string) { const a = sep10BlogArticles[slug], canonical = `${site}/blog/${slug}`, schema = { '@context': 'https://schema.org', '@type': 'Article', headline: a.title, description: a.description, datePublished: published, dateModified: published, mainEntityOfPage: canonical, image: `${site}${hero}`, author: { '@type': 'Organization', name: 'Outsourced Labor' }, publisher: { '@type': 'Organization', name: 'Outsourced Labor' } }; return <><Header/><main className="article-page"><JsonLd data={schema}/><article className="container article-shell"><header className="article-header"><p className="eyebrow">Operations field guide</p><h1>{a.title}</h1><p className="lead">{a.description}</p><div className="article-meta"><span>10 min read</span><time dateTime={published}>{visible}</time></div><img src={hero} alt="Operations teammates checking a shared work record" width="1200" height="630"/></header><div className="article-body">{a.sections.map(([h, p1, p2]: string[]) => <section key={h}><h2>{h}</h2><p>{p1}</p><p>{p2}</p></section>)}</div><section className="source-list"><h2>Operational references</h2><ol><li><a href="https://www.nist.gov/cyberframework">NIST Cybersecurity Framework 2.0</a></li><li><a href="https://www.gao.gov/products/gao-14-704g">GAO Standards for Internal Control</a></li></ol></section></article><CTA/></main><Footer/></>; }
