export const sep18BlogTopics = [
  ['outsourced-labor-vendor-invoice-follow-up', 'How to Hand Off Vendor Invoice Follow-Up Without Handing Off Payment Approval', 'vendor invoice follow-up', 'invoice follow-up register', 'invoice number, purchase order, receipt evidence, discrepancy, vendor contact, approver, and next check', 'a matched invoice awaiting approval', 'an invoice with changed bank details or an unexplained amount', 'procurement-follow-up'],
  ['philippines-ecommerce-order-exception-queue', 'Build an Ecommerce Order Exception Queue for Philippines Operations Support', 'ecommerce order exceptions', 'order exception queue', 'order ID, verified status, exception type, customer impact, permitted update, decision owner, and review time', 'a carrier delay covered by an approved reply', 'a refund, replacement, or promise outside the published policy', 'order-operations'],
  ['filipino-crm-data-cleanup-acceptance-test', 'Set an Acceptance Test for CRM Data Cleanup by Filipino Staff', 'CRM data cleanup', 'CRM cleanup test sheet', 'record ID, source, proposed edit, duplicate signal, protected field, reviewer, and result', 'standardizing a state name from an authoritative address', 'merging contacts with conflicting account or consent history', 'crm-data-stewardship'],
  ['outsourced-labor-sop-handoff-test', 'Test an SOP Before Outsourced Labor Uses It on Live Work', 'SOP handoff readiness', 'SOP handoff test', 'task trigger, approved input, ordered steps, stop condition, example, owner, and revision date', 'a routine status update with a complete example', 'a step that changes access, money, policy, or a customer commitment', 'sop-documentation'],
  ['philippines-workforce-schedule-demand-check', 'Check Demand Before Building a Philippines Workforce Schedule', 'schedule demand planning', 'demand and coverage sheet', 'interval, demand signal, required skill, available coverage, break, backup, and planning owner', 'a recurring queue with stable hourly arrival patterns', 'a forecast gap that would require overtime or a service-level change', 'workforce-scheduling'],
  ['filipino-vendor-master-data-verification', 'Verify Vendor Master Data With a Filipino Operations Specialist', 'vendor master data verification', 'vendor verification packet', 'vendor ID, submitted field, authoritative evidence, existing value, conflict, requester, and approver', 'confirming a business address from an approved record', 'changing bank, tax, ownership, or payment-routing information', 'vendor-coordination'],
  ['outsourced-labor-inventory-discrepancy-research', 'Research Inventory Discrepancies Before an Owner Adjusts Stock', 'inventory discrepancy research', 'inventory discrepancy packet', 'SKU, location, system quantity, count evidence, movement history, variance, and adjustment owner', 'finding an unposted transfer supported by a scan record', 'writing off stock or changing the official quantity without approval', 'inventory-administration'],
  ['philippines-weekly-kpi-source-reconciliation', 'Reconcile Weekly KPI Sources With Philippines Reporting Support', 'weekly KPI reconciliation', 'KPI reconciliation worksheet', 'metric, definition, period, source query, extracted value, variance, reviewer, and release state', 're-running an approved report for the same period', 'changing a metric definition to make two reports agree', 'workforce-reporting'],
  ['filipino-quality-audit-sample-design', 'Choose a Useful Quality Audit Sample for Filipino Support Work', 'quality audit sampling', 'quality sample plan', 'population, period, risk group, selection rule, exclusions, reviewer, and corrective owner', 'selecting routine and returned cases with a documented rule', 'removing difficult cases after results are known', 'quality-audit-support'],
  ['outsourced-labor-operations-dispatch-priority-rules', 'Write Dispatch Priority Rules for an Outsourced Operations Queue', 'operations dispatch priorities', 'dispatch priority card', 'work class, impact, deadline, dependency, authorized action, escalation owner, and tie-break rule', 'routing a documented service interruption to the named responder', 'reordering work based on an unverified claim of urgency', 'operations-dispatch'],
  ['philippines-shared-inbox-coverage-plan', 'Plan Shared Inbox Coverage for a Philippines Admin Team', 'shared inbox coverage', 'inbox coverage map', 'mailbox, coverage window, message class, response boundary, backup, escalation owner, and handoff time', 'tagging and drafting a routine scheduling reply', 'sending legal, payment, personnel, or policy commitments', 'workforce-scheduling'],
  ['outsourced-labor-first-lane-readiness-review', 'Which Work Should You Outsource First? Run a Lane Readiness Review', 'first-lane selection', 'lane readiness scorecard', 'volume, repeatability, approved source, example quality, access risk, review capacity, and decision owner', 'a repeated update with stable inputs and a clear finish condition', 'a changing process that depends on undocumented executive judgment', 'quality-audit-support'],
] as const;

export const sep18BlogPosts = sep18BlogTopics.map(([slug, title, focus]) => ({
  slug,
  title,
  excerpt: `A practical buyer guide to ${focus} with Filipino outsourced staff, clear approval boundaries, and a reviewable handoff.`,
  minutes: 12,
}));
