import type { Metadata } from 'next';
import { CTA, Footer, Header, JsonLd } from './components';
import { sep18BlogTopics } from './sep18-records';

const published = '2026-09-18';
const visible = 'Published: September 18, 2026';
const site = 'https://outsourcedlabor.com';
const sources = [
  { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Use the Govern and Protect functions when access, records, or accountability affect the work lane.' },
  { name: 'GAO Standards for Internal Control in the Federal Government', url: 'https://www.gao.gov/products/gao-14-704g', note: 'A useful reference for control activities, documentation, information, and monitoring concepts.' },
  { name: 'Philippines National Privacy Commission: Data Privacy Act of 2012', url: 'https://privacy.gov.ph/data-privacy-act/', note: 'Confirm current privacy duties with qualified counsel and the organization responsible for the data.' },
];

const articles = sep18BlogTopics.map(([slug, title, focus, artifact, fields, ordinary, edge, service], index) => ({
  slug, title, service,
  description: `A practical buyer guide to ${focus} with Filipino outsourced staff, clear approval boundaries, and a reviewable handoff.`,
  image: `/sep18-heroes/${slug}`,
  alt: `Illustrated ${artifact} for an outsourced operations team`,
  sections: [
    ['Begin with the buyer decision', `The first question is not whether a remote worker can perform ${focus}. It is whether your business can define a stable slice of the work, provide an approved source, and review the result without moving consequential authority into the queue. A useful handoff starts with one decision: what outcome should the manager be able to accept, return, or escalate after reading the ${artifact}? That keeps staffing discussions tied to a real operating need instead of a broad job title.`, `Choose one queue, one system of record, and one accountable owner for the pilot. Write down what arrives, how often it arrives, and what a finished item looks like. If the owner cannot show two recent examples and explain why each was accepted, the lane is not ready to scale. The preparatory work may still be outsourced, but the first assignment should be documenting examples and open questions rather than processing live exceptions.`],
    [`Build the ${artifact}`, `Create the ${artifact} with ${fields}. Each field should help the specialist act, help the reviewer check the action, or help the next person recover the state. Avoid decorative status fields and private shorthand. A status such as “waiting” is useful only when it also names what is missing, who owns the response, the last safe action, and when the item will be checked again.`, `Use a real recent case to test the layout. For this article's example ${index + 1}, imagine ${ordinary}. The specialist should be able to identify the approved evidence, complete the permitted step, save a link to the result, and state the finish condition. Ask a second person to resume from that saved record. Every avoidable question reveals a missing field, unclear label, or hidden dependency.`],
    ['Draw the authority boundary beside the work', `Separate actions into three columns: may complete, may prepare for review, and must stop. Routine verification, structured data entry, draft summaries, and evidence collection may fit the first two columns when the source and acceptance rule are clear. Decisions about money, permissions, deletion, policy exceptions, staffing consequences, legal meaning, or promises to a customer normally remain with the accountable client owner.`, `Put the hard case next to the ordinary case. Here the stop example is ${edge}. The specialist should preserve the source material, state the exact conflict, avoid the consequential action, and route a narrow question to the named owner. A deadline does not expand authority, and silence is not approval. If safe work can continue, state which part; if it cannot, preserve the item in a recoverable holding state.`],
    ['Use approved sources and minimum access', `Name the authoritative source for every field that could change. A dashboard may summarize the work, but the underlying order, customer, vendor, workforce, or policy record may still control. Record the source version or retrieval time when freshness matters. When two approved sources disagree, show both values and pause only the affected action instead of quietly choosing the more convenient answer.`, `Grant access for the narrow lane, not for the person's possible future duties. Keep personal and sensitive data in the approved system and link to it rather than copying it into chat or a convenience spreadsheet. Review exports, shared folders, service accounts, and temporary permissions. The National Privacy Commission reference below is a starting point for privacy awareness, not a substitute for legal advice or your own documented policy.`],
    ['Set an acceptance test before volume', `Define the checks a reviewer will perform before the first live item is assigned. An acceptance test can confirm the correct record, current source, permitted action, required fields, escalation behavior, and saved evidence. It should also say what happens after a failed check. “Be more careful” is not a repair instruction; the return should identify the failed condition, point to an approved example, and name the next review.`, `Test at least four cases: one ordinary item, one incomplete item, one conflicting-source item, and one item near the authority boundary. Do not remove difficult cases after seeing the result. Track exclusions openly so a clean score cannot be manufactured from easy work. Review correctness and recoverability before speed. A fast result that another reviewer cannot reproduce is not ready for a larger queue.`],
    ['Plan the handoff across working hours', `For Philippines-based support, define the overlap window in both local time zones and identify which decisions require the client owner to be available. State the final handoff time, the receiving owner, and the safe state for work that misses the window. A good handoff preserves the request, verified facts, action already taken, open question, deadline, and next check without requiring a call with the original specialist.`, `Different working hours can create useful coverage, but they do not by themselves create continuity. Test an absence and a delayed owner response. The backup should use the same approved sources and should not receive broader access merely for convenience. When the primary worker returns, restore ownership deliberately and remove temporary permissions according to their approved end condition.`],
    ['Measure the lane without inventing a productivity promise', `Use counts that explain the system: arrivals, completed items, returned items, waiting reasons, exception classes, review time, and age of unresolved work. Separate specialist preparation time from owner decision time. Otherwise an approval bottleneck may be mislabeled as low worker productivity, or risky guessing may look efficient because it avoids visible waits.`, `Treat a small pilot as evidence about the tested lane, not proof of universal quality, savings, or speed. Compare results with the written acceptance rule and retain the original submission when corrections occur. If the same error repeats, inspect the source, example, permission, field definition, and review capacity before blaming an individual. The useful outcome is a more inspectable process and a clearer staffing decision.`],
    ['Connect the article to a service decision', `If the pilot is stable, compare its needs with the site's ${service.replaceAll('-', ' ')} scope. The service page can help a buyer translate the record into a bounded support lane, but the client still owns policy, approvals, system administration, and business outcomes. Bring the ${artifact}, two accepted examples, one failed example, expected weekly volume, and the name of the reviewer to that conversation.`, `If those materials do not exist, the next step is readiness work rather than headcount. Document the authoritative source, create the acceptance test, and measure how much reviewer time real cases require. This may reveal that the process needs simplification, that only preparation should be delegated, or that a different lane is a safer first assignment. Any of those is a useful decision.`],
    ['Run a bounded two-week pilot', `Start with a capped queue and a named reviewer. On day one, walk through the ordinary and stop cases. During the first week, review every item that affects a consequential boundary and a defined sample of routine items. Hold short correction reviews against the written criteria. Do not silently widen the task list because the worker has unused time; unused capacity is safer than an undocumented change in role.`, `At the end of the pilot, decide whether to keep, repair, expand, or stop the lane. Expansion requires consistent acceptance, recoverable handoffs, manageable review time, and clear treatment of exceptions. Repair means changing the source, example, form, permission, or owner and then retesting. Stop if the process remains unstable or authority cannot be separated from preparation.`],
    ['Use a copy-ready kickoff brief', `A concise kickoff can read: “For the next two weeks, prepare ${artifact} entries for this queue only. Use the linked system record as the source of truth. Complete the permitted routine steps, save evidence, and stop when a source conflicts or an owner decision is required. The client reviewer accepts or returns each item against the attached checklist.” Replace every placeholder with a real system, person, and time.`, `Add the ordinary example and the stop example from this guide, then include your own recent accepted case. State the overlap window, review cutoff, backup route, data-handling rule, and how temporary access ends. This brief does not replace an employment agreement, service agreement, security policy, or legal review. It gives the operating lane a testable beginning so both the client and the Filipino specialist can see what good work means.`],
  ],
}));

export const sep18BlogArticles = Object.fromEntries(articles.map((article) => [article.slug, article]));

export function getSep18BlogMetadata(slug: string): Metadata {
  const article = sep18BlogArticles[slug]; const canonical = `${site}/blog/${slug}`;
  return { title: article.title, description: article.description, alternates: { canonical }, openGraph: { title: article.title, description: article.description, url: canonical, type: 'article', publishedTime: published, images: [{ url: article.image, width: 1200, height: 630, alt: article.alt }] } };
}

export function renderSep18BlogArticle(slug: string) {
  const article = sep18BlogArticles[slug]; const canonical = `${site}/blog/${slug}`;
  const schema = { '@context': 'https://schema.org', '@type': 'Article', headline: article.title, description: article.description, datePublished: published, dateModified: published, mainEntityOfPage: canonical, image: `${site}${article.image}`, author: { '@type': 'Organization', name: 'Outsourced Labor', url: site }, publisher: { '@type': 'Organization', name: 'Outsourced Labor', url: site }, citation: sources.map((source) => source.url) };
  return <><Header /><main className="article-page"><JsonLd data={schema} /><article className="container article-shell"><header className="article-header"><p className="eyebrow">Outsourced operations buyer guide</p><h1>{article.title}</h1><p className="lead">{article.description}</p><div className="article-meta"><span>12 min read</span><time dateTime={published}>{visible}</time></div><img src={article.image} alt={article.alt} width="1200" height="630" /></header><div className="article-body">{article.sections.map(([heading, first, second]: string[]) => <section key={heading}><h2>{heading}</h2><p>{first}</p><p>{second}</p></section>)}<p>If you want help turning this tested lane into a managed workflow, review <a href={`/services/${article.service}`}>{article.service.replaceAll('-', ' ')}</a>. Keep consequential approvals with the accountable client owner.</p></div><section className="source-list"><h2>Authoritative references</h2><ol>{sources.map((source) => <li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.name}</a><p>{source.note}</p></li>)}</ol></section></article><CTA /></main><Footer /></>;
}
