export const sep23BlogTopics = [
['philippines-procurement-quote-comparison-packet','Build a Quote Comparison Packet With Philippines Procurement Support','supplier quote comparison','procurement-follow-up','quote packet','three supplier offers with different units, freight, tax, and validity dates','approved request, specification, quantity, delivery point, original quotes, currency, tax, freight, and validity date','the specification differs, a substitution appears, a commercial choice is needed, or payment details change'],
['filipino-crm-lead-source-normalization','Normalize CRM Lead Sources With a Filipino Data Steward','CRM lead-source normalization','crm-data-stewardship','source decision table','one campaign recorded as LinkedIn, LI Ads, linkedin-paid, and blank across separate imports','CRM export, protected raw values, approved channel dictionary, campaign records, import history, and duplicate rules','two sources are plausible, attribution would be overwritten, records must merge, or a new category is needed'],
['outsourced-inventory-reorder-alert-handoff','Design a Reorder Alert Handoff for Outsourced Inventory Support','inventory reorder alerts','inventory-administration','reorder alert handoff','a fast-moving SKU crossing its threshold while delayed receipts make availability uncertain','SKU master, on-hand and committed quantities, open orders, receipts, lead time, threshold rule, and source timestamps','counts disagree, lead time is missing, demand is exceptional, a substitute is proposed, or a purchase must be approved'],
['philippines-support-severity-matrix','Create a Support Severity Matrix for a Philippines Customer Service Team','customer support severity','customer-support','severity matrix','a login problem, a possible data exposure, and a delayed feature request arriving in the same hour','severity definitions, impact fields, security triggers, commitments, escalation contacts, and approved reply language','security, privacy, safety, legal threat, widespread outage, compensation, or facts fitting multiple levels'],
['filipino-workforce-attendance-exception-workflow','Route Attendance Exceptions With Filipino Workforce Support','attendance exception routing','workforce-scheduling','attendance exception record','an unexpected absence before a shift containing routine work and manager-only decisions','approved schedule, notice channel, coverage map, queue priorities, leave policy, contacts, and privacy limits','policy interpretation, medical detail, payroll change, discipline, overtime, or access outside the backup role'],
['outsourced-order-cancellation-request-triage','Triage Order Cancellation Requests With Outsourced Support','order cancellation triage','order-operations','cancellation decision packet','a cancellation request after payment when storefront, warehouse, and carrier show different states','order, payment, warehouse and carrier events, cancellation policy, risk flags, and approved customer language','a refund is required, goods may have shipped, policy exception is requested, fraud is suspected, or sources conflict'],
['philippines-sop-screenshot-review-cadence','Keep SOP Screenshots Current With Philippines Documentation Support','SOP screenshot maintenance','sop-documentation','screenshot review register','an application update moving a button and renaming a permission while the sequence stays the same','SOP owner, application, process version, screenshot inventory, text instructions, trigger, and verified date','the workflow changed, permissions are unsuitable, data cannot be masked, capture is restricted, or no owner exists'],
['filipino-vendor-certificate-expiry-tracker','Track Vendor Certificate Expiry With Filipino Operations Support','vendor certificate expiry','vendor-coordination','certificate expiry tracker','an insurance certificate nearing expiry while the contract and portal disagree on the required period','vendor list, certificate, issuer, covered entity, effective and expiry dates, requirement, contact, and review owner','coverage adequacy needs judgment, a file appears altered, legal interpretation is needed, or identity differs'],
['outsourced-quality-defect-taxonomy-calibration','Calibrate a Defect Taxonomy for Outsourced Quality Reviews','quality defect classification','quality-audit-support','defect calibration sheet','two reviewers calling the same incomplete record an accuracy, completeness, and process defect','acceptance criteria, definitions, severity rules, representative work, appeal route, and taxonomy version','the standard conflicts with policy, a label affects employment, bias may influence scoring, or evidence is absent'],
['philippines-recurring-report-input-map','Map Inputs for Recurring Reports With Philippines-Based Staff','recurring report inputs','workforce-reporting','report input map','a Monday report combining CRM, order, staffing, and finance extracts refreshed at different times','report purpose, decision owner, fields, source systems and owners, refresh times, transformations, cutoffs, and fallbacks','sources disagree, a definition changed, finance approval is required, data exceeds purpose, or an override lacks evidence'],
['filipino-meeting-action-closure-register','Close Meeting Actions With a Filipino Operations Specialist','meeting action follow-through','operations-support','action closure register','a meeting producing six apparent actions that actually include decisions, questions, and tasks','meeting notes, exact action, owner, contributor, due date, dependency, decision needed, and acceptance evidence','no owner accepts the task, scope expands, money or customer commitments change, or closure cannot be demonstrated'],
['outsourced-access-request-scope-review','Review Access Request Scope Before Outsourced Staff Start Work','access request scoping','operations-support','access request worksheet','an order-status role that also exposes refunds, exports, user administration, and unrelated customer records','approved tasks, system owner, role catalog, data class, required actions, environment, dates, and approver','the available role is too broad, credentials would be shared, privilege is requested, or approval and removal ownership are missing'],
] as const;
export const sep23BlogPosts=sep23BlogTopics.map(([slug,title,focus])=>({slug,title,excerpt:`A practical guide to ${focus} for Philippines-based support, with a concrete workflow, approval limits, and review checks.`,minutes:10}));
