export const sep25BlogTopics = [
['philippines-support-escalation-response-clock','Set an Escalation Response Clock for Philippines Customer Support','support escalation response timing','customer-support','escalation response clock','a high-impact ticket reaching a manager after the first response target but before the resolution deadline','ticket ID, severity, received time, response target, escalation trigger, current owner, customer impact, and next-update time','severity is disputed, a promise is requested, privacy or security is involved, or no authorized decision owner is available'],
['filipino-admin-contract-renewal-calendar','Maintain a Contract Renewal Calendar With Filipino Admin Support','contract renewal calendar administration','admin-support','contract renewal calendar','a software agreement approaching notice deadline while usage and owner records are incomplete','contract record, renewal date, notice period, business owner, approved terms, usage source, and decision deadline','terms need interpretation, price or scope changes, cancellation authority is unclear, or the authoritative agreement is missing'],
['outsourced-customer-support-macro-change-review','Review Support Macro Changes With an Outsourced Team','customer support macro change control','customer-support','macro change review sheet','a frequently used reply containing an obsolete troubleshooting step after a product release','approved product guidance, current macro, ticket examples, policy owner, affected queues, reviewer, and effective date','policy meaning changes, legal language appears, compensation is offered, or the authoritative product behavior is uncertain'],
['philippines-order-address-change-triage','Triage Order Address Changes With Philippines Ecommerce Support','order address change triage','order-operations','address change triage checklist','a customer requesting an address correction after a warehouse pick event but before carrier acceptance','order ID, authenticated request, fulfillment state, carrier event, address fields, cutoff rule, and approved reply','identity is uncertain, shipment control is lost, extra cost is required, fraud signals appear, or policy exception is requested'],
['filipino-procurement-delivery-date-follow-up','Track Supplier Delivery Dates With Filipino Procurement Support','supplier delivery date follow-up','procurement-follow-up','delivery-date follow-up register','a supplier missing an acknowledgment date while production depends on one line item','approved purchase order, item, quantity, promised date, acknowledgment history, dependency, buyer, and escalation threshold','commercial terms change, an expedite fee is proposed, specification differs, or a customer commitment must be made'],
['outsourced-crm-field-completeness-audit','Run a CRM Field Completeness Audit With Outsourced Data Support','CRM field completeness auditing','crm-data-stewardship','field completeness audit','a pipeline report showing many blank next-step dates across otherwise active opportunities','approved field dictionary, record population, required-field rules, source system, owner, sampling method, and audit cutoff','a value would need to be inferred, consent is unclear, ownership is disputed, or records require deletion or merging'],
['philippines-workforce-schedule-coverage-gap','Identify Schedule Coverage Gaps With Philippines Workforce Support','workforce schedule coverage analysis','workforce-scheduling','coverage gap worksheet','a recurring queue having enough scheduled hours overall but no trained coverage during one handoff window','demand interval, approved schedule, attendance status, skill requirement, queue target, time zone, and backup roster','overtime, leave, discipline, schedule changes, or service tradeoffs require approval'],
['filipino-invoice-receipt-matching-queue','Build an Invoice-to-Receipt Matching Queue With Filipino Finance Support','invoice and receipt matching','finance-operations-support','matching queue','an invoice listing two deliveries while one receipt remains open and the other has a quantity variance','invoice, approved purchase order, receipt records, supplier identity, quantities, amounts, currency, and exception owner','payment, coding judgment, tax treatment, bank details, approval, or unexplained variance is involved'],
['outsourced-knowledge-base-search-gap-review','Find Knowledge Base Search Gaps With Outsourced Documentation Support','knowledge base search-gap review','sop-documentation','search gap register','agents repeatedly searching a customer phrase that does not match the approved article terminology','search terms, result set, ticket examples, current article, content owner, product source, and review date','new policy is needed, product behavior is unverified, regulated wording appears, or removal affects active support'],
['philippines-quality-review-disagreement-log','Use a Review Disagreement Log With Philippines QA Support','quality review disagreement tracking','reporting-and-qa','review disagreement log','two reviewers scoring the same support reply differently because the rubric lacks an edge-case example','sample ID, rubric version, reviewer scores, cited evidence, disagreement category, calibration owner, and resolution date','the standard must change, personnel action is considered, sensitive data is exposed, or no accountable owner can decide'],
['filipino-vendor-contact-verification-review','Verify Vendor Contacts With Filipino Operations Support','vendor contact verification','vendor-coordination','vendor contact verification record','a payment-status request arriving from a new address that resembles an existing supplier contact','approved vendor master, known contact channels, request history, callback method, verification result, owner, and timestamp','banking data changes, identity cannot be confirmed, credentials are requested, or fraud indicators appear'],
['outsourced-operations-backlog-aging-brief','Prepare a Backlog Aging Brief With Outsourced Operations Support','operations backlog aging analysis','operations-support','backlog aging brief','a queue total remaining stable while older cases accumulate behind newer easy work','case ID, received time, status events, priority rule, dependency, current owner, due time, and exception reason','priority must change, customer or financial commitments are needed, policy conflicts, or ownership remains disputed'],
] as const;
export const sep25BlogPosts=sep25BlogTopics.map(([slug,title,focus])=>({slug,title,excerpt:`A practical guide to ${focus} for Philippines-based support, with evidence fields, approval boundaries, and review checks.`,minutes:10}));
