export const sep24BlogTopics = [
['philippines-customer-refund-evidence-packet','Prepare a Refund Evidence Packet With Philippines Customer Support','refund evidence preparation','customer-support','refund evidence packet','a customer reporting a duplicate charge while the order, gateway, and help desk show different timestamps','order ID, payment events, customer messages, refund policy, fulfillment status, and approved response language','money must move, fraud is suspected, policy is unclear, or the systems disagree'],
['filipino-accounts-receivable-dispute-log','Maintain an Accounts Receivable Dispute Log With Filipino Support','accounts receivable dispute tracking','finance-operations-support','dispute log','a customer disputing part of an invoice while continuing to pay undisputed items','invoice, contract reference, delivery evidence, correspondence, aging report, owner, and next-action date','a credit, write-off, legal interpretation, bank change, or customer commitment is requested'],
['outsourced-purchase-order-acknowledgment-tracker','Track Purchase Order Acknowledgments With Outsourced Procurement Support','purchase order acknowledgment tracking','procurement-follow-up','PO acknowledgment tracker','a supplier acknowledging quantity but changing the promised ship date','approved purchase order, supplier acknowledgment, item, quantity, price, ship date, delivery point, and buyer contact','price, specification, quantity, payment terms, or approved delivery date changes'],
['philippines-ecommerce-return-intake-checklist','Build a Return Intake Checklist for Philippines Ecommerce Support','ecommerce return intake','order-operations','return intake checklist','a return request with photos but no order identifier and an approaching policy deadline','order record, customer message, item, delivery event, return policy, photos, and approved reply','eligibility requires judgment, safety is involved, fraud appears possible, or a refund must be approved'],
['filipino-crm-consent-status-review','Review CRM Consent Status With a Filipino Data Steward','CRM consent-status review','crm-data-stewardship','consent review worksheet','a contact appearing in two lists with different subscription states and dates','protected source records, consent event, capture method, purpose, suppression list, timestamp, and policy owner','consent cannot be proven, deletion is requested, records conflict, or legal interpretation is needed'],
['outsourced-vendor-onboarding-document-check','Check Vendor Onboarding Documents With Outsourced Operations Support','vendor onboarding document checks','vendor-coordination','vendor document checklist','a new supplier submitting a tax form and insurance file under slightly different legal names','approved vendor request, legal name, required-document list, submitted files, expiry dates, and owner','identity differs, banking details change, a document looks altered, or approval is missing'],
['philippines-support-ticket-reopen-analysis','Analyze Reopened Tickets With Philippines Customer Support','reopened support ticket analysis','customer-support','reopen review sheet','a resolved ticket reopening because the answer addressed the symptom but not the account setting','ticket history, customer replies, category rules, resolution code, linked product record, and quality standard','security, privacy, compensation, policy exception, or an unverified product defect appears'],
['filipino-inventory-cycle-count-exception-log','Keep a Cycle Count Exception Log With Filipino Inventory Support','cycle count exception logging','inventory-administration','count exception log','a physical count differing from the system while an open receipt and transfer are still pending','SKU, location, count evidence, system quantity, open receipts, transfers, adjustments, and cutoff time','an inventory adjustment, write-off, ownership decision, or investigation beyond the approved scope is required'],
['outsourced-sla-breach-warning-queue','Run an SLA Breach Warning Queue With Outsourced Support','SLA breach warning queues','operations-support','breach warning queue','several cases nearing different response deadlines while two wait on customer information','case ID, SLA definition, start and pause events, priority, owner, dependency, and approved notice','the SLA calculation is disputed, priority must change, a promise is needed, or a contractual exception appears'],
['philippines-catalog-change-proof-sheet','Create a Catalog Change Proof Sheet With Philippines Ecommerce Support','catalog change proofing','order-operations','catalog proof sheet','a product update changing dimensions and images while price remains pending approval','approved change request, source specification, current listing, proposed copy, assets, affected channels, and owner','price, regulated claim, compatibility, warranty, or unapproved source information changes'],
['filipino-knowledge-base-expiry-review','Review Knowledge Base Expiry With Filipino Documentation Support','knowledge base expiry review','sop-documentation','article expiry register','a support article still ranking well even though its screenshots and account steps may be outdated','article URL, owner, product area, last verification, source procedure, traffic signal, and review date','the product behavior changed, no authoritative owner exists, legal language is involved, or removal is proposed'],
['outsourced-shift-capacity-variance-report','Prepare a Shift Capacity Variance Report With Outsourced Workforce Support','shift capacity variance reporting','workforce-reporting','capacity variance report','a support shift receiving more work than forecast while absences reduce available handling time','forecast, arrivals, staffing schedule, attendance status, productive hours, queue age, and cutoff','overtime, leave, discipline, staffing commitments, or customer-service tradeoffs require a manager decision'],
] as const;
export const sep24BlogPosts=sep24BlogTopics.map(([slug,title,focus])=>({slug,title,excerpt:`A practical guide to ${focus} for Philippines-based support, with evidence fields, approval boundaries, and review checks.`,minutes:10}));
