export const sep3BlogTopics = [
  ['philippines-operations-request-clarity-review','Review Request Clarity Before Assigning Philippines Operations Work','request clarity','a request card','purpose, source records, expected output, deadline, and decision owner','ambiguous requests entering active work','2026-09-03'],
  ['outsourced-labor-evidence-retention-map','Build an Evidence Retention Map for Outsourced Labor','evidence retention','an evidence map','record type, business purpose, system location, access owner, and review trigger','proof becoming detached from the work it supports','2026-09-03'],
  ['filipino-specialist-correction-reason-codes','Use Correction Reason Codes With a Filipino Specialist','correction reasons','a correction register','failed condition, supporting example, repair owner, due state, and follow-up sample','vague feedback creating repeated rework','2026-09-03'],
  ['philippines-team-backlog-recovery-sequence','Sequence Backlog Recovery for a Philippines Team','backlog recovery','a recovery board','work age, consequence, readiness, dependency, and accountable owner','old work being rushed without source or authority checks','2026-09-03'],
  ['outsourced-labor-access-request-handoff','Design an Access Request Handoff for Outsourced Labor','access requests','an access handoff','task need, minimum permission, approving owner, expiry, and verification evidence','availability being mistaken for permission','2026-09-03'],
  ['filipino-specialist-review-ready-definition','Define Review Ready for a Filipino Specialist','review readiness','a review-ready checklist','artifact identity, source links, completed checks, known exceptions, and requested decision','unfinished work entering editorial or manager review','2026-09-03'],
  ['philippines-operations-record-conflict-triage','Triage Record Conflicts in Philippines Operations','record conflicts','a conflict packet','competing records, timestamps, source authority, safe holding action, and resolver','contributors silently choosing between inconsistent sources','2026-09-03'],
  ['outsourced-labor-recurring-task-sunset-review','Run a Recurring Task Sunset Review for Outsourced Labor','task retirement','a sunset record','current purpose, recent demand, downstream dependency, record owner, and retirement decision','obsolete routines continuing because they are familiar','2026-09-03'],
  ['filipino-team-manager-question-batch','Batch Manager Questions From a Filipino Team','manager questions','a decision brief','question class, verified context, consequence, safe work completed, and response owner','scattered questions losing context across time zones','2026-09-03'],
  ['philippines-support-work-acceptance-sample','Sample Work Acceptance in Philippines Support','acceptance sampling','an acceptance sample','selection rule, required evidence, reviewer decision, return reason, and trend limit','completion counts masking weak handoffs','2026-09-03'],
  ['outsourced-labor-process-owner-directory','Create a Process Owner Directory for Outsourced Labor','process ownership','an owner directory','work lane, authoritative source, ordinary reviewer, exception owner, and backup route','work waiting because responsibility is assumed but unnamed','2026-09-03'],
  ['filipino-specialist-change-acknowledgement-log','Keep a Change Acknowledgement Log With Filipino Specialists','instruction changes','a change log','changed rule, effective date, affected examples, acknowledgement, and verification sample','old and new instructions remaining active together','2026-09-03'],
] as const;

export const sep3BlogPosts = sep3BlogTopics.map(([slug,title,focus])=>({slug,title,excerpt:`A practical guide to ${focus} in Philippines-based outsourced operations.`,minutes:14}));
