import type {Metadata} from 'next';import {CTA,Footer,Header,JsonLd} from './components';import {sep7BlogTopics} from './sep7-records';
const published='2026-09-07',visible='September 7, 2026',site='https://outsourcedlabor.com',hero='/illustrations/getillustrations/goodle-team/operations-review.svg';
const articles=sep7BlogTopics.map(([slug,title,focus,artifact,fields],index)=>({slug,title,description:`A practical ${focus} routine for recurring work handled with a Philippines-based team.`,sections:[
['Start with the moment the routine is needed',`Use ${artifact} when ${focus} can no longer live safely in chat or memory. Name the recurring work lane and the event that opens the record. The goal is a dependable handoff, not another status document.`,`For this routine, capture ${fields}. Keep the record beside the work so a contributor can update it without rebuilding the story from several tools.`],
['Give every field a job','A field belongs only when it helps someone act, review, or escalate. Write short entries that point to source evidence. If a fact is unknown, label the gap and its owner instead of filling it with a plausible guess.','The accountable manager should define which decisions remain reserved, especially changes involving money, policy, customer commitments, access, personal data, or deletion.'],
['Review a small real sample','Test the routine on a narrow batch before applying it to the full queue. Review one ordinary item, one exception, and one item that waits on another person. Those examples reveal whether the record survives the awkward parts of the work.','Ask the next owner to continue from the record alone. If they must search private messages or ask what a label means, repair the handoff while the examples are still fresh.'],
['Keep the daily check lightweight','At the opening check, confirm the current owner, next action, source link, and time-sensitive risk. At closeout, record the actual state and any decision still outstanding. This makes the routine useful across the working-day overlap without implying round-the-clock availability.','A manager can sample completed records for accuracy and clarity rather than reading every keystroke. Repeated omissions should lead to a clearer example or instruction, not a vague request to be more careful.'],
['Set boundaries before expanding the lane','The routine supports preparation and coordination; it does not transfer the owner’s authority. Document when a specialist must pause and who can answer. Avoid measuring speed where a correct wait protects the business or customer.',`After a short pilot, keep, revise, or retire the routine based on observed rework, waiting, and review effort. Article ${index+1} in this release addresses ${focus}; its checklist should not be copied into a different work lane without checking the actual risks.`],
]}));
export const sep7BlogArticles=Object.fromEntries(articles.map(a=>[a.slug,a]));
export function getSep7BlogMetadata(slug:string):Metadata{const a=sep7BlogArticles[slug],canonical=`${site}/blog/${slug}`;return{title:a.title,description:a.description,alternates:{canonical},openGraph:{title:a.title,description:a.description,url:canonical,type:'article',publishedTime:published,images:[hero]}}}
export function renderSep7BlogArticle(slug:string){const a=sep7BlogArticles[slug],canonical=`${site}/blog/${slug}`;const schema={'@context':'https://schema.org','@type':'Article',headline:a.title,description:a.description,datePublished:published,dateModified:published,mainEntityOfPage:canonical,image:`${site}${hero}`,author:{'@type':'Organization',name:'Outsourced Labor'},publisher:{'@type':'Organization',name:'Outsourced Labor'}};return <><Header/><main className="article-page"><JsonLd data={schema}/><article className="container article-shell"><header className="article-header"><p className="eyebrow">Operations field guide</p><h1>{a.title}</h1><p className="lead">{a.description}</p><div className="article-meta"><span>12 min read</span><time dateTime={published}>{visible}</time></div><img src={hero} alt="Operations team reviewing a shared workflow" width="1200" height="630"/></header><div className="article-body">{a.sections.map(([h,p1,p2]:string[])=><section key={h}><h2>{h}</h2><p>{p1}</p><p>{p2}</p></section>)}</div><section className="source-list"><h2>Planning references</h2><ol><li><a href="https://www.nist.gov/cyberframework">NIST Cybersecurity Framework 2.0</a></li><li><a href="https://www.gao.gov/products/gao-14-704g">GAO Standards for Internal Control</a></li></ol></section></article><CTA/></main><Footer/></>}
