import type {Metadata} from 'next';
import {CTA,Footer,Header,JsonLd} from './components';
import {sep8BlogTopics} from './sep8-records';

const published='2026-09-08';
const visible='September 8, 2026';
const site='https://outsourcedlabor.com';
const hero='/illustrations/getillustrations/goodle-team/operations-review.svg';

const articles=sep8BlogTopics.map(([slug,title,focus,artifact,fields],index)=>({slug,title,description:`A practical ${focus} routine for recurring work handled with a Philippines-based team.`,sections:[
  [`Recognize when ${focus} needs a record`,`Use ${artifact} at the point where ${focus} would otherwise depend on memory, a private message, or an assumption. Tie it to one recurring work lane and one observable trigger so the team knows exactly when the routine begins.`,`Record ${fields}. Each entry should help the next person verify a fact, take a permitted action, or route a decision. Unknown information stays visibly unknown until its owner resolves it.`],
  ['Connect the routine to authoritative evidence','Link the current source rather than pasting an unexplained value. Note the version, effective date, or retrieval time when a source can change. That small trace helps a reviewer distinguish a contributor mistake from a changed instruction.','If two sources conflict, pause the affected step and identify the accountable source owner. Philippines-based support can assemble the conflict and its impact; it should not silently choose policy, financial, access, privacy, or customer-commitment rules.'],
  ['Test the awkward cases first','Pilot the record with one ordinary item, one incomplete item, and one consequential exception. Ask a second person to continue from the saved state without relying on chat history. Any question they cannot answer points to a missing field, unclear example, or hidden decision right.','Keep the sample small enough to review closely. The purpose is to expose ambiguity before volume makes it expensive, not to produce a flattering completion count from the easiest items.'],
  ['Make review proportionate to consequence','Check routine items by sample and review high-consequence exceptions individually. A useful review confirms the source, permitted action, unresolved uncertainty, and next owner. It does not reward speed when waiting protects a customer or the business.','Track repeated returns by reason. Repair the source, example, or boundary when the same misunderstanding recurs. Do not turn a process defect into a vague judgment about an individual contributor.'],
  ['Close with a usable handoff',`Close ${artifact} only when the stated acceptance condition is visible. Preserve the final state, reviewer decision, and any follow-up date so tomorrow’s queue does not begin by reconstructing yesterday.`,`This is guide ${index+1} in the September 8 release. Apply its ${focus} method only to a lane with comparable sources and risks; the accountable owner remains responsible for expansion, exceptions, and public or customer-facing decisions.`],
]}));

export const sep8BlogArticles=Object.fromEntries(articles.map(a=>[a.slug,a]));
export function getSep8BlogMetadata(slug:string):Metadata{const a=sep8BlogArticles[slug],canonical=`${site}/blog/${slug}`;return{title:a.title,description:a.description,alternates:{canonical},openGraph:{title:a.title,description:a.description,url:canonical,type:'article',publishedTime:published,images:[hero]}}}
export function renderSep8BlogArticle(slug:string){const a=sep8BlogArticles[slug],canonical=`${site}/blog/${slug}`;const schema={'@context':'https://schema.org','@type':'Article',headline:a.title,description:a.description,datePublished:published,dateModified:published,mainEntityOfPage:canonical,image:`${site}${hero}`,author:{'@type':'Organization',name:'Outsourced Labor'},publisher:{'@type':'Organization',name:'Outsourced Labor'}};return <><Header/><main className="article-page"><JsonLd data={schema}/><article className="container article-shell"><header className="article-header"><p className="eyebrow">Operations field guide</p><h1>{a.title}</h1><p className="lead">{a.description}</p><div className="article-meta"><span>12 min read</span><time dateTime={published}>{visible}</time></div><img src={hero} alt="Operations team reviewing a shared workflow" width="1200" height="630"/></header><div className="article-body">{a.sections.map(([h,p1,p2]:string[])=><section key={h}><h2>{h}</h2><p>{p1}</p><p>{p2}</p></section>)}</div><section className="source-list"><h2>Planning references</h2><ol><li><a href="https://www.nist.gov/cyberframework">NIST Cybersecurity Framework 2.0</a></li><li><a href="https://www.gao.gov/products/gao-14-704g">GAO Standards for Internal Control</a></li></ol></section></article><CTA/></main><Footer/></>}
