import type {Metadata} from 'next';import {CTA,Footer,Header,JsonLd} from './components';import {sep9BlogTopics} from './sep9-records';
const published='2026-09-09',visible='September 9, 2026',site='https://outsourcedlabor.com',hero='/illustrations/getillustrations/goodle-team/operations-review.svg';
const articles=sep9BlogTopics.map(([slug,title,focus,artifact,fields])=>({slug,title,description:`A practical guide to ${focus} in a clearly bounded Philippines-based work lane.`,sections:[
[`Start where ${focus} becomes ambiguous`,`Introduce the ${artifact} where a specialist first has to choose between continuing, waiting, or asking for a decision. Define one observable trigger and one work lane; “use judgment” does not explain which judgment belongs to the role.`,`Record ${fields}. Keep the entry short enough for real work and complete enough that a reviewer can recover the state without private chat.`],
['Draw the authority line','State what the specialist may complete, what may be prepared but not executed, and what must stop for approval. Pair an ordinary example with one consequential edge case.','Keep money, account authority, policy exceptions, sensitive data, and customer promises with the accountable owner. The remote role can assemble evidence without inheriting unapproved authority.'],
['Make evidence easy to verify','Link the current system record, policy, or approved instruction and note its effective date. When sources conflict, show both and pause only the affected step.','Do not reward quiet guessing. Preserve the unknown, route a specific question, and update the authoritative instruction after the owner resolves it.'],
['Test three real cases','Try one ordinary case, one incomplete case, and one exception. Ask a second person to resume from the saved record; every extra question reveals a missing field or unclear decision right.','Review accuracy and recoverability before speed. Then the owner can simplify the record, expand the lane, or retain individual review for consequential items.'],
['Close the record and improve the routine',`Close the ${artifact} only when its acceptance condition, reviewer, and final state are visible. Otherwise name the next owner and next check.`,`Repeated corrections should improve the source, example, or boundary—not produce a vague request to be more careful. Preserve the evidence and require owner approval for wider process changes.`]
]}));
export const sep9BlogArticles=Object.fromEntries(articles.map(a=>[a.slug,a]));
export function getSep9BlogMetadata(slug:string):Metadata{const a=sep9BlogArticles[slug],canonical=`${site}/blog/${slug}`;return{title:a.title,description:a.description,alternates:{canonical},openGraph:{title:a.title,description:a.description,url:canonical,type:'article',publishedTime:published,images:[hero]}}}
export function renderSep9BlogArticle(slug:string){const a=sep9BlogArticles[slug],canonical=`${site}/blog/${slug}`,schema={'@context':'https://schema.org','@type':'Article',headline:a.title,description:a.description,datePublished:published,dateModified:published,mainEntityOfPage:canonical,image:`${site}${hero}`,author:{'@type':'Organization',name:'Outsourced Labor'},publisher:{'@type':'Organization',name:'Outsourced Labor'}};return <><Header/><main className="article-page"><JsonLd data={schema}/><article className="container article-shell"><header className="article-header"><p className="eyebrow">Operations field guide</p><h1>{a.title}</h1><p className="lead">{a.description}</p><div className="article-meta"><span>11 min read</span><time dateTime={published}>{visible}</time></div><img src={hero} alt="Operations teammates reviewing a shared work queue" width="1200" height="630"/></header><div className="article-body">{a.sections.map(([h,p1,p2]:string[])=><section key={h}><h2>{h}</h2><p>{p1}</p><p>{p2}</p></section>)}</div><section className="source-list"><h2>Operational references</h2><ol><li><a href="https://www.nist.gov/cyberframework">NIST Cybersecurity Framework 2.0</a></li><li><a href="https://www.gao.gov/products/gao-14-704g">GAO Standards for Internal Control</a></li></ol></section></article><CTA/></main><Footer/></>}
