type ResearchSource = {name:string;url:string};
type ResearchRecord = {slug:string;title:string;excerpt:string;published:'2026-08-14';body:readonly string[];sources:readonly ResearchSource[];related:readonly string[];cta:string;service?:{href:string;heading:string;body:string;label:string};image?:string;headlineStat?:string;keyStats?:readonly string[];takeaways?:readonly string[];faqs?:readonly {q:string;a:string}[]};

const sources = [
  {name:'World Bank: World Development Report 2021 — Data for Better Lives',url:'https://www.worldbank.org/en/publication/wdr2021'},
  {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},
  {name:'U.S. Small Business Administration: Hire and manage employees',url:'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees'},
  {name:'International Labour Organization: Decent Work and the 2030 Agenda',url:'https://www.ilo.org/global/topics/sdg-2030/lang--en/index.htm'}
] as const;

const body = (focus:string, unit:string, period:string, finding:string, limitation:string, decision:string, specific:string) => [
  `This research examines ${focus} in a bounded outsourced operations setting. The question is whether the available evidence is strong enough to support ${decision}. It is not a promise about every company, customer, geography, or service lane. A useful study names the work object, the responsible owner, the observation window, and the consequence of getting the interpretation wrong. Those boundaries keep an operational finding from becoming an unsupported generalization.`,
  `Begin with a definition that another reviewer can apply. Here the unit is ${unit}. State whether the unit is counted when it arrives, when it is accepted, when it is completed, or when an owner confirms the result. Distinguish a request from a message, a record from a field, and a correction from a new piece of work. If the definition changes, mark the break in the record rather than presenting a smooth trend.`,
  `Use ${period} as a deliberately bounded observation frame. Preserve the source timestamp, work category, status, owner decision, and any exclusion reason. A period is not a magic threshold: it may capture ordinary demand, an unusual event, or a partial cycle. The reader needs to know what was available for review and what was outside the frame before accepting the finding.`,
  `The central finding is that ${finding} This is useful because averages can conceal the cases that consume judgment, create exposure, or delay a customer decision. Compare the pattern with the proposed scope, the quality of the incoming records, the approval requirements, and the fallback path. A stable average does not prove that every category is equally suitable for delegated handling.`,
  `The World Bank treats data as an asset whose value depends on quality, governance, and the context in which it is used. That principle applies here: a larger record set is not automatically better evidence. Preserve provenance, definitions, missingness, and changes in collection. The external framework supplies a way to think about evidence; it does not establish a result for this company or its readers.`,
  `NIST’s Cybersecurity Framework 2.0 emphasizes governance, identification, protection, detection, response, and recovery. For an outsourced work lane, that vocabulary helps connect an operational measure to its consequence. Ask what should be protected, what signal should be detected, who responds, and how the owner knows the situation is restored. Do not use a productivity count as a substitute for risk judgment.`,
  `The Small Business Administration’s guidance on managing employees stresses clear responsibilities and expectations. For delegated work, translate that principle into a written boundary: required input, ordinary action, acceptance condition, review sample, escalation signal, and accountable decision owner. A clear boundary is fairer than a broad instruction because it makes both successful handling and a justified pause visible.`,
  `The ILO’s decent-work framing is also relevant to how work is measured. A useful control should not quietly turn every pause into individual failure or treat constant availability as the only route to service. Record whether waiting came from missing information, an owner decision, a system dependency, or the person doing the work. That distinction improves the decision without erasing reasonable working conditions.`,
  `Report denominators and missing cases next to the result. If 24 of 160 records met a condition, say what the 160 records represent and how duplicates, cancelled cases, and incomplete records were handled. If only a sample was reviewed, name its selection rule. Precision without a visible denominator creates confidence without reproducibility, while a bounded estimate can still support a practical decision.`,
  `Use ${specific} as a topic-specific comparison rather than collapsing every observation into one score. Keep the category definitions stable and compare routine cases with exception cases, or complete inputs with incomplete inputs, using the same rule. Explain whether the difference is large enough to matter operationally and whether it changes the proposed boundary.`,
  `Check for mix changes before interpreting movement. A result can shift because the work contains more urgent cases, a different customer group, a new channel, or a changed definition. Preserve the composition of the population alongside the headline measure. If the mix is not comparable, describe the periods separately and avoid calling the difference an improvement or decline.`,
  `Test the source path for each material claim. The reviewer should be able to identify the originating record, the transformation applied, the period covered, the exclusions made, and the person who accepted the interpretation. A link to a general authority can give context, but it cannot replace the local evidence needed to support a statement about a particular work lane.`,
  `Set a stopping rule before the result becomes convenient. Pause or escalate when the source of truth is unclear, a required approval is absent, sensitive information is exposed unnecessarily, the work exceeds the stated authority, or the evidence cannot support the proposed conclusion. A stopping rule is a decision aid, not a failure condition; it makes uncertainty observable and gives the owner a fair route to resolve it.`,
  `Consider the strongest counterexample. A quiet period can make a lane appear dependable, while a single unusual event can make normal work look unsafe. Review at least one ordinary case and one consequential exception, explain why each belongs in the population, and state what the comparison cannot establish. The aim is not to eliminate uncertainty but to keep the recommendation proportionate to it.`,
  `Write the limitation beside the result: ${limitation} A short period can miss seasonality; a clean source can still omit an important category; and a local definition may not match an external statistic. State what new evidence would change the interpretation. Readers make better decisions when the conditions for revision are explicit rather than hidden in a generic disclaimer.`,
  `Interpret the finding at the same level as the observation. Evidence about ${focus}, measured in ${unit} during ${period}, does not establish a universal claim about all outsourced work. Preserve the population, period, denominator, and owner decision whenever the result is summarized. This is especially important when a concise dashboard or handoff removes the surrounding explanation.`,
  `Turn the conclusion into a reversible choice where possible. A narrow pilot can limit the record types, exclude sensitive cases, reserve consequential approvals for the owner, and set a review date. A pilot tests a stated boundary; it does not prove that a whole function is safe to delegate. Expansion should require named evidence, while a failed condition should trigger a pause, narrower scope, or a new source requirement.`,
  `Review the evidence with the people who will receive the work, not only with the person who collected it. Ask whether the record is understandable, whether the exception rule is actionable, and whether the receiving owner can locate the source without reconstructing a private conversation. If the answer is no, improve the record design before collecting more volume.`,
  `Keep a decision note with the question, population, method, result, uncertainty, owner, and next review date. This makes a later change legible: the team can distinguish a real change in demand from a changed definition, a new dependency, or a different consequence. It also prevents a prior interpretation from being reused after its evidence has gone stale.`,
  `Conclusion: ${finding} The defensible next step is to name the work object, preserve the evidence path, measure the stated unit over the stated period, and retain human ownership of exceptions and consequential decisions. That approach gives OutsourcedLabor.com readers a practical way to evaluate delegated work while keeping the limits of the evidence visible.`
];

export const august14ResearchRecords: readonly ResearchRecord[] = [
  {slug:'research-aug14-demand-seasonality',title:'Separate recurring demand from seasonal demand in outsourced work',excerpt:'Demand timing can look predictable in an average while seasonal peaks change the coverage and review a work lane actually needs.',published:'2026-08-14',body:body('demand seasonality','new work items received by day, category, and urgency','twelve complete calendar weeks','weekly averages should be separated from recurring peaks and category-specific surges.','twelve weeks may not include an annual cycle or an unusual business event.','whether a proposed coverage boundary fits ordinary demand and known peaks.','weekday and week-of-period comparisons, with urgent items kept separate from routine arrivals.'),sources,related:['research-aug13-queue-arrival-patterns','research-outsourced-demand-forecasting'],cta:'Use the evidence to set a bounded coverage assumption.'},
  {slug:'research-aug14-source-authority-mapping',title:'Map source authority before relying on outsourced research',excerpt:'A source map distinguishes primary evidence, interpretation, and context so a published finding does not outrun its strongest support.',published:'2026-08-14',body:body('source authority mapping','material claims classified by source type, relevance, and directness','one defined research batch and its cited sources','claim strength improves when primary evidence, authoritative context, and interpretation are labeled separately.','authority is domain-specific and a strong source may still be too broad for a local claim.','which claims can be published, narrowed, held, or sent back for stronger evidence.','primary records, official statistics, methodology notes, and commentary compared claim by claim.'),sources,related:['research-aug13-record-lineage-check','research-source-ledger-for-daily-decisions'],cta:'Use the map to keep claim strength proportional to evidence.'},
  {slug:'research-aug14-case-mix-drift',title:'Detect case-mix drift before comparing outsourced work results',excerpt:'Changes in category, urgency, or input quality can make a stable measure misleading when the underlying work mix has shifted.',published:'2026-08-14',body:body('case-mix drift','completed and waiting cases grouped by work type, urgency, and input condition','four consecutive weekly cohorts','trend comparisons are more trustworthy when changes in case composition are shown beside the result.','small cohorts can make composition changes look larger than they are.','whether a result reflects changed work, changed inputs, or changed measurement.','routine, urgent, incomplete, and owner-dependent cases reported as separate cohorts.'),sources,related:['research-aug13-exception-impact-mapping','research-outsourced-work-outcome-measures'],cta:'Use the cohort view before changing the work boundary.'},
  {slug:'research-aug14-accuracy-denominator',title:'Choose an accuracy denominator for outsourced administrative work',excerpt:'Accuracy claims need a stable denominator and a visible definition of correction, because accepted records alone can hide unresolved defects.',published:'2026-08-14',body:body('accuracy denominator design','records sampled, records accepted, and records requiring a material correction','three monthly samples with the same inclusion rule','an accuracy result is meaningful only when its denominator and correction threshold stay visible.','sampled work may not represent errors that were never detected or returned.','whether the measure supports a quality decision, a narrower scope, or a different review method.','accepted records, returned records, and later-discovered corrections kept as distinct outcomes.'),sources,related:['research-aug13-rework-source-analysis','research-outsourced-accuracy-sampling'],cta:'Use a stated denominator to make quality findings reviewable.'},
  {slug:'research-aug14-escalation-thresholds',title:'Set evidence-based escalation thresholds for outsourced work',excerpt:'Escalation is clearer when thresholds connect uncertainty and consequence to an owner decision instead of relying on vague instructions.',published:'2026-08-14',body:body('escalation threshold design','cases routed because of uncertainty, consequence, authority, or missing evidence','a bounded pilot with every escalation reason recorded','thresholds work when they identify the signal, preserve the evidence, and name the receiving decision owner.','rare high-consequence cases may not appear in a short pilot.','which conditions require a pause, a question, a transfer, or ordinary handling.','policy exceptions, sensitive records, irreversible actions, and unresolved customer commitments.'),sources,related:['research-aug13-exception-impact-mapping','research-outsourced-escalation-design'],cta:'Use the findings to define a fair escalation boundary.'},
  {slug:'research-aug14-customer-record-freshness',title:'Measure customer-record freshness before delegated follow-up',excerpt:'A record can be complete yet stale, so freshness checks should connect the last verified state to the action being considered.',published:'2026-08-14',body:body('customer-record freshness','records whose required fields were verified within the action-specific freshness window','one complete month of dated records','freshness should be defined by the decision the record supports, not by a universal age rule.','the appropriate freshness window can differ by record type and business context.','which records can proceed, which need verification, and which require owner review.','last-verified date, source system, changed fields, and action consequence compared together.'),sources,related:['research-aug13-intake-field-reliability','research-outsourced-customer-context'],cta:'Use freshness evidence to protect the quality of delegated follow-up.'},
  {slug:'research-aug14-review-sample-design',title:'Design review samples around risk in outsourced work',excerpt:'A risk-shaped sample gives owner review more value than a random completion count when exceptions and consequences are unevenly distributed.',published:'2026-08-14',body:body('risk-shaped review sampling','routine, exception, high-consequence, and corrected cases selected under one written rule','four weekly review cycles','review coverage is stronger when the sample includes both ordinary volume and the cases most likely to change the decision.','a sample cannot reveal errors that the selection rule systematically excludes.','whether review effort is proportionate to consequence and whether the boundary can expand.','random routine cases combined with every high-consequence exception and a fixed correction sample.'),sources,related:['research-aug13-review-capacity-ratio','research-quality-sampling-for-article-queues'],cta:'Use the sample design to focus review where judgment matters.'},
  {slug:'research-aug14-reversible-scope-pilot',title:'Test reversibility before expanding an outsourced work scope',excerpt:'A scope change is easier to govern when the owner can pause the lane, recover trusted records, and explain the evidence behind reversal.',published:'2026-08-14',body:body('reversible scope pilots','scope changes with a named pause condition, recovery state, and accountable approver','the first 30 days after a proposed change','reversibility is a property of the record and decision path, not just a promise to stop.','a short pilot cannot reproduce every failure mode or dependency.','whether to expand, hold, narrow, or reverse the proposed scope.','pause trigger, last trusted state, recovery owner, affected records, and review date.'),sources,related:['research-aug13-scope-reversal-readiness','research-outsourced-change-control'],cta:'Use a reversible pilot to make scope decisions safer.'},
  {slug:'research-aug14-continuity-dependency-map',title:'Map continuity dependencies in Philippines-based outsourced work',excerpt:'Continuity depends on access, connectivity, records, approvals, and fallback ownership, not simply on having another person available.',published:'2026-08-14',body:body('continuity dependency mapping','work items affected by a named dependency and the fallback path available to the owner','one normal cycle plus a documented dependency review','a continuity plan is more credible when it shows which dependencies can pause work and which have a tested fallback.','a dependency map is a point-in-time view and may miss correlated disruptions.','which work can pause, which needs fallback ownership, and which promise must be narrowed.','identity access, system availability, connectivity, source records, approvals, and urgent decisions.'),sources,related:['research-outsourced-continuity-planning-philippines','research-aug13-handoff-retrieval-test'],cta:'Use the map to review continuity assumptions before a disruption.'},
  {slug:'research-aug14-work-instruction-ambiguity',title:'Measure ambiguity in work instructions before adding outsourced capacity',excerpt:'Repeated clarification can signal an unclear rule or missing source rather than a need for more handling capacity.',published:'2026-08-14',body:body('work-instruction ambiguity','requests that require clarification, with the missing definition or decision recorded','six weeks of ordinary and exception requests','clarification patterns identify missing authority, source context, or definitions before volume is treated as the problem.','a visible clarification may undercount silent assumptions that were never questioned.','whether to revise the instruction, improve the source record, or narrow the work boundary.','clarification reason, affected step, source record, owner answer, and whether the answer becomes reusable.'),sources,related:['research-aug13-decision-waiting-time','research-outsourced-service-level-definition'],cta:'Use clarification evidence to improve the boundary before scaling it.',service:{href:'/services/sop-documentation',heading:'Turn repeated questions into a usable SOP',body:'When the same question keeps coming back, a Philippines-based specialist can turn approved answers into a short SOP. Your manager still decides the rule, exception, and final change.',label:'Plan SOP documentation'}}
] as const;
