type ResearchReplacement = {
  slug: string;
  title: string;
  excerpt: string;
  published: string;
  image?: string;
  body: readonly string[];
  sources: readonly { name: string; url: string }[];
  related: readonly string[];
  cta: string;
  headlineStat?: string;
  keyStats?: readonly string[];
  takeaways?: readonly string[];
  faqs?: readonly { q: string; a: string }[];
};

const sources = [
  { name: 'International Labour Organization — Decent work and the 2030 Agenda', url: 'https://www.ilo.org/global/topics/sdg-2030/lang--en/index.htm' },
  { name: 'World Bank — World Development Report 2021: Data for Better Lives', url: 'https://www.worldbank.org/en/publication/wdr2021' },
  { name: 'U.S. Small Business Administration — Hire and manage employees', url: 'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees' },
  { name: 'NIST — Privacy Framework', url: 'https://www.nist.gov/privacy-framework' },
] as const;

const topicSpecific: Record<string, readonly string[]> = {
  'case-mix stability': ['A useful stability test compares the share of routine, incomplete, and exception cases week by week. A lane that keeps the same total while its exception share doubles is not stable in the sense that matters for assignment decisions.', 'Use a transition matrix to show cases that stay open, return for clarification, or move to owner review. This exposes whether apparent volatility comes from arrivals or from work that cannot reach an accepted state.'],
  'input completeness': ['Completeness is best treated as a field-level result: present, valid, current, and authorized are different states. A request can contain every field and still point to an obsolete record or an authority the contributor cannot verify.', 'Compare clarification requests by source and field. If one intake channel repeatedly omits the same approval or deadline, the evidence supports changing that channel rather than treating every case as an isolated omission.'],
  'rework signals': ['Classify rework by trigger, such as source error, interpretation error, changed instruction, or missed check. The classification should be made at return, before the correction is silently absorbed into the next cycle.', 'A rising return rate with stable source quality suggests a different intervention from a stable return rate with increasingly consequential corrections. Preserve both the count and the consequence class when interpreting the trend.'],
  'owner decision latency': ['Age should be split into time awaiting a contributor, time awaiting a client owner, and time awaiting an external dependency. Combining those intervals makes an accountable decision look like an execution delay and weakens the next staffing choice.', 'Review the oldest cases separately from the median. A low median can coexist with a small group of consequential cases that need a named decision rule or an explicit fallback owner.'],
  'record provenance': ['Lineage should capture the source identifier, extraction period, transformation, and reviewer, while avoiding unnecessary personal data. A source link alone is insufficient when a filter or calculation materially changes the result.', 'Reconstruct a small sample from source to final record and record each point where a human interpretation entered. The exercise distinguishes a reproducible transformation from an undocumented judgment.'],
  'exception severity': ['A severity rubric should describe consequence, exposure, reversibility, and urgency in observable terms. Calibration examples matter because the same missing field may be trivial in one lane and consequential in another.', 'Plot frequency against consequence rather than ranking exceptions by volume alone. The rare high-consequence quadrant is often where escalation and access boundaries deserve the most attention.'],
  'supervision load': ['Count review time by purpose: acceptance, correction, decision, coaching, and investigation. These minutes answer different questions and should not be collapsed into one productivity penalty.', 'Compare owner review minutes with the work volume and exception share for the same period. If review expands faster than accepted output, a narrower scope or better evidence may be more useful than adding another queue.'],
  'access-scope fit': ['Map each permission to a task, record type, action, and owner, then test whether the action is read, prepare, update, approve, or delete. The mapping makes excess privilege visible without assuming that every role needs the same access.', 'Repeat the review after a scope change and at the end of a pilot. Removal evidence is as important as grant evidence because stale access can survive after the original work has stopped.'],
  'handoff retrievability': ['Test retrieval with a receiving owner who did not create the packet. Measure whether that person can identify current state, evidence, uncertainty, and next decision within the agreed review window.', 'A failed retrieval test should identify the missing element rather than request a longer narrative. Fixed fields and authoritative links often improve recovery more than additional status messages.'],
  'reversible scope change': ['A rollback condition should name the signal, decision owner, protected record state, and action that narrows or pauses the lane. “Revisit later” is not a reversible plan unless the trigger and authority are explicit.', 'Compare the proposed change with a baseline period and preserve the pre-change definitions. Without that baseline, a later improvement or failure cannot be attributed to the scope decision with confidence.'],
};

const body = (topic: string, unit: string, observation: string, finding: string, limitation: string, decision: string, example: string) => [
  `This research examines ${topic} in a bounded outsourced operations lane. The unit of analysis is ${unit}, and the observation frame is ${observation}. The purpose is to help an owner decide what evidence is sufficient before assigning a repeatable responsibility; it is not to claim that one arrangement works for every organization.`,
  `Start by defining the work object. ${example} A request, message, record, and resolved case can be related without being interchangeable. Write the inclusion rule, exclusion rule, duplicate rule, and timestamp before measuring anything. Without those definitions, a neat total can combine unlike events and create a false sense of comparability.`,
  `The evidence question is whether ${finding} The answer should be expressed with a denominator and a period. For example, report how many of the defined population met the condition, how many required clarification, and how many were held for an owner decision. A percentage without its population is an incomplete finding.`,
  `Separate ordinary handling from exceptions. A lane can have predictable arrivals while its exceptions consume most of the judgment. Record the reason for waiting, the source consulted, the person who owns the next decision, and the elapsed time. That distinction tells a manager whether the problem is missing information, ambiguous authority, poor source quality, or work capacity.`,
  `The World Bank's data guidance is useful context because decisions depend on data that is fit for purpose, not simply abundant. Apply that principle locally: preserve definitions, provenance, missingness, and changes in collection. External guidance supplies a frame for disciplined evidence; it does not establish a result for this company or for every service lane.`,
  `The ILO's decent-work framework also matters to delegated work because a productive lane still needs clear conditions, responsibilities, and protections. A contributor should know the ordinary boundary, the pause condition, and the person who can resolve an exception. The owner retains accountability for decisions involving sensitive information, commitments, policy exceptions, or consequences that the contributor cannot safely assess.`,
  `Use a sample that another reviewer could reproduce. State how records were selected, the number selected, the number available, and the number excluded. If 24 of 160 records were reviewed, explain whether 160 means arrivals, completions, or cases remaining after duplicates were removed. A sample can support a bounded decision without pretending to be a census.`,
  `Compare at least two meaningful categories rather than relying on one average. For ${topic}, compare routine cases with exception cases, or complete inputs with incomplete inputs, while keeping the same scoring rule. A difference is useful only when the categories, period, and denominator remain stable enough to explain what changed.`,
  `Record the cost of ambiguity separately from the result of the work. Repeated clarification may indicate that a source record is missing or a rule is unclear; it should not automatically be treated as individual failure. Conversely, a complete source and a clear rule do not remove the need to check accuracy. The categories should make that difference visible.`,
  `Set a stopping rule before the measurement begins. Stop or escalate when the source of truth cannot be identified, the request exceeds the stated authority, personal information is exposed unnecessarily, or the evidence cannot support the proposed conclusion. The stopping rule protects both the customer and the contributor by making uncertainty observable.`,
  `A practical result is a reversible decision. A narrow pilot can define the record set, reserve approval for the owner, exclude sensitive cases, and set a review date. The pilot tests a stated boundary; it does not prove that an entire function is safe to delegate. Expansion should require new evidence, while a failed condition should trigger a pause or narrower scope.`,
  `The SBA emphasizes clear responsibilities and expectations when managing employees. For outsourced support, translate that principle into a written handoff: the input, finished output, source record, ordinary path, review sample, escalation owner, and decision that remains with the client. This is more useful than a broad promise because it tells both sides what can be inspected.`,
  `Limitations should sit next to the conclusion. ${limitation} A short period can miss seasonality, an unusual event can distort the observed pattern, and local definitions can differ from external research. Say what new observation would change the decision instead of hiding uncertainty in a general disclaimer.`,
  `Interpret the result at the same level as the observation. Evidence about ${topic} measured in ${unit} during ${observation} does not establish a universal claim about every customer, geography, or service. Preserve the population and period whenever the finding is summarized for another manager, because context is part of the result.`,
  `Before expanding the lane, review accepted work and corrected work together. Ask whether the contributor followed the ordinary path, recognized the exception, preserved the evidence, and made the next owner decision clear. A high completion count is not enough if the cases that matter most are hidden in a separate queue.`,
  `Keep a short decision log for the observation. Record the question, population, method, result, uncertainty, and action owner. If the definition changes, mark the break instead of presenting a seamless trend. This record lets a later reviewer distinguish a genuine change in work from a change in how the work was counted.`,
  `Check the counterexample deliberately. A quiet period may make the lane look dependable, while a single unusual case may exaggerate its apparent risk. Review both an ordinary example and the most consequential observed exception, explain why each belongs in the population, and state what the comparison cannot establish.`,
  `Do not replace a missing decision with a larger number of instructions. If the same question returns repeatedly, ask whether the source, authority, or definition is absent. The most useful intervention may be a named owner or an authoritative record rather than additional handling capacity.`,
  ...(topicSpecific[topic] ?? []),
  `Conclusion: the evidence should be used to decide ${decision}. The defensible next step is to name the work object, define the boundary, measure the stated unit over the stated observation frame, and retain a human decision owner for exceptions. That approach supports responsible delegated work without converting a local observation into an unsupported assurance.`,
];

export const august13ResearchReplacements: readonly ResearchReplacement[] = [
  { slug: 'research-aug13-queue-volatility', title: 'Study queue volatility before expanding delegated operations', excerpt: 'A stable average can hide a changing mix of routine, incomplete, and exception cases.', published: '2026-08-13', body: body('case-mix stability', 'completed cases grouped by work type', 'six consecutive reporting weeks', 'the category mix remains understood as the lane changes', 'six weeks may not include seasonal or rare demand', 'whether the proposed scope is stable enough for a bounded pilot', 'A customer case with a complete source and a policy exception should not be counted as equivalent to a routine status update.'), sources, related: ['research-outsourced-demand-forecasting'], cta: 'Use the findings to define a measured scope.' },
  { slug: 'research-aug13-clarification-burden', title: 'Measure clarification burden in outsourced support requests', excerpt: 'Complete inputs reduce avoidable waiting, but the missing fields still reveal where a service boundary is unclear.', published: '2026-08-13', body: body('input completeness', 'requests assessed at first receipt', 'the first 120 requests in a defined month', 'missing information is distinguished from downstream execution errors', 'one month may overrepresent a particular requester group', 'which required fields belong at intake and which need owner review', 'A request may name a desired result but omit the source record, deadline, or approval owner needed to act safely.'), sources, related: ['research-outsourced-customer-context'], cta: 'Use the findings to improve request quality.' },
  { slug: 'research-aug13-correction-cause', title: 'Use correction causes to diagnose delegated work quality', excerpt: 'Rework is more informative when its cause is separated from simple correction and changing scope.', published: '2026-08-13', body: body('rework signals', 'records returned for correction or clarification', 'three monthly review samples', 'rework points to a repeatable boundary or source problem', 'reviewed samples may omit work accepted without review', 'whether the remedy is better input, clearer authority, training, or narrower scope', 'A corrected date field, a missing approval, and an incorrect customer promise should not share one undifferentiated error label.'), sources, related: ['research-outsourced-accuracy-sampling'], cta: 'Use the findings to focus improvement.' },
  { slug: 'research-aug13-approval-aging', title: 'Examine owner decision latency in support lanes', excerpt: 'Waiting for an accountable decision can look like low productivity when it is actually a boundary or information issue.', published: '2026-08-13', body: body('owner decision latency', 'cases waiting for a named owner decision', 'four weekly decision reviews', 'elapsed time is attributed to the correct dependency', 'the review frame may not capture urgent out-of-cycle decisions', 'whether the next action is better evidence, a clearer approval rule, or a different queue', 'A contributor can prepare a complete exception packet while the final decision remains intentionally with the client owner.'), sources, related: ['research-outsourced-review-capacity'], cta: 'Use the findings to clarify decision ownership.' },
  { slug: 'research-aug13-source-lineage', title: 'Assess record provenance in outsourced administrative work', excerpt: 'A result is easier to trust when the source, transformation, and responsible reviewer remain visible.', published: '2026-08-13', body: body('record provenance', 'completed records with a traceable source', 'one complete monthly work cycle', 'a reviewer can reconstruct how a record reached its final state', 'provenance checks may favor structured work over unusual cases', 'which source fields must be retained and which transformations need review', 'A report total should point to its source system, filters, period, calculation, and known exclusions instead of relying on an unexplained number.'), sources, related: ['research-outsourced-source-dependency'], cta: 'Use the findings to strengthen traceability.' },
  { slug: 'research-aug13-risk-consequence', title: 'Separate exception frequency from exception severity', excerpt: 'Rare events may deserve more attention than frequent, easily corrected exceptions.', published: '2026-08-13', body: body('exception severity', 'exceptions scored by consequence class', 'a defined sample from one reporting month', 'frequency and consequence are reviewed as separate dimensions', 'severity scoring requires owner calibration and may change with context', 'which exceptions require correction, escalation, or a narrower boundary', 'A missing noncritical field and an unauthorized customer commitment can both interrupt work but do not carry the same consequence.'), sources, related: ['research-outsourced-error-impact'], cta: 'Use the findings to prioritize responsible review.' },
  { slug: 'research-aug13-review-minutes', title: 'Estimate supervision load before delegating a new lane', excerpt: 'A work lane is not sustainable if the review burden consumes the owner capacity it was meant to protect.', published: '2026-08-13', body: body('supervision load', 'owner review minutes by case category', 'four weekly review meetings', 'review effort is matched to risk and unresolved judgment', 'meeting samples may omit asynchronous decisions', 'whether the lane needs narrower scope, better evidence, or a different review sample', 'Reading every routine record can crowd out the cases where owner judgment changes the outcome.'), sources, related: ['research-outsourced-review-capacity'], cta: 'Use the findings to design proportionate review.' },
  { slug: 'research-aug13-permission-alignment', title: 'Test whether access matches delegated work scope', excerpt: 'Permissions should follow the live work boundary and be removable when the assignment changes.', published: '2026-08-13', body: body('access-scope fit', 'permissions mapped to live tasks', 'one access review at the start and end of a pilot', 'each permission has a current task and accountable owner', 'a point-in-time review cannot reveal every future scope change', 'which access should remain, be narrowed, or be removed', 'A contributor who prepares a record may not need permission to approve payment, change policy, or delete history.'), sources, related: ['research-outsourced-data-access-boundaries'], cta: 'Use the findings to review least-necessary access.' },
  { slug: 'research-aug13-handoff-recovery', title: 'Test whether delegated handoffs are retrievable', excerpt: 'A handoff succeeds when the receiving owner can find the relevant facts without reconstructing a private conversation.', published: '2026-08-13', body: body('handoff retrievability', 'handoff packets sampled at receipt', 'three consecutive handoff cycles', 'the receiving owner can identify facts, uncertainty, and next decision', 'the test may not represent urgent or unusual handoffs', 'whether the record needs a fixed field, clearer source link, or named owner', 'A useful packet keeps the verified state, customer wording, action taken, unresolved question, and deadline together.'), sources, related: ['research-outsourced-customer-context'], cta: 'Use the findings to make ownership transfer reviewable.' },
  { slug: 'research-aug13-scope-rollback', title: 'Evaluate reversibility before changing an outsourced work lane', excerpt: 'A scope change is safer when the owner can pause it, restore a trusted state, and review the evidence.', published: '2026-08-13', body: body('reversible scope change', 'scope changes with a stated rollback condition', 'the first 30 days after a proposed change', 'the lane can be paused without losing accountable record state', 'a pilot cannot reproduce every failure mode', 'whether to expand, hold, narrow, or reverse the change', 'Adding a customer segment or approval responsibility can alter information exposure and consequence even when the role name stays the same.'), sources, related: ['research-outsourced-service-recovery'], cta: 'Use the findings to make scope changes reversible.' },
];
