type Source = {name:string;url:string};
type Record = {slug:string;title:string;excerpt:string;published:'2026-08-17';body:readonly string[];sources:readonly Source[];related:readonly string[];cta:string;image?:string;headlineStat?:string;keyStats?:readonly string[];takeaways?:readonly string[];faqs?:readonly {q:string;a:string}[];service?:{href:string;heading:string;body:string;label:string}};

const worldBank = {name:'World Bank: World Development Report 2021 — Data for Better Lives',url:'https://www.worldbank.org/en/publication/wdr2021'};
const nist = {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'};
const ilo = {name:'International Labour Organization: Decent Work and the 2030 Agenda',url:'https://www.ilo.org/global/topics/sdg-2030/lang--en/index.htm'};
const sba = {name:'U.S. Small Business Administration: Hire and manage employees',url:'https://www.sba.gov/business-guide/manage-your-business/hire-manage-employees'};

export const august17ResearchRecords: readonly Record[] = [
 {slug:'research-aug17-queue-coverage-fit',title:'Test queue coverage before assigning Philippines-based support',excerpt:'Coverage is a service-design question: the right evidence shows whether a Filipino specialist can receive, progress, and hand off a queue without hiding owner decisions.',published:'2026-08-17',body:[
  'Research question: can a defined recurring queue be covered by Philippines-based support without creating silent waiting, unsafe decisions, or an unrealistic promise? The unit of analysis is one work item from receipt through accepted handoff. A message, order, customer record, or research request must not be blended into one count merely because all appear in an inbox.',
  'Use four complete weeks of timestamped arrivals, completions, waiting reasons, escalations, and owner decisions. Separate ordinary items from urgent or sensitive cases. This evidence scope can show the shape of one lane; it cannot establish annual seasonality, a universal staffing ratio, or the performance of an unnamed provider.',
  'Coverage should be tested at the points where work changes state. An item that is technically answered but waits for approval is not equivalent to an item ready for the next owner. For a Philippines-based specialist, record the receiving time zone, the source system, the next decision, and whether the item can safely wait through the next overlap period.',
  'The World Bank treats data quality and governance as conditions for useful decisions. Applied here, an arrival count without definitions is weak evidence. Preserve excluded duplicates, cancelled requests, missing timestamps, and items returned for clarification. A clean denominator is more useful than a large but ambiguous queue.',
  'Compare coverage by category, not only by daily average. Administrative records with stable fields may have a different handoff burden from customer cases or vendor dependencies. Examine the oldest item in each category and ask whether the delay came from capacity, missing context, access, or a manager decision.',
  'NIST’s governance and identify functions support naming the owner, systems, dependencies, and consequences before protection or response is designed. The Filipino specialist can prepare and progress bounded work while the manager retains decisions involving policy, money, access, or an unusual customer commitment.',
  'A credible conclusion is conditional: coverage fits only the observed categories, hours, access, and review capacity. It does not prove uninterrupted output. Re-test after a material change in queue mix, source system, approval rule, or promised response window. If an exception is frequent, narrow the role or redesign the handoff rather than hiding it in an average.',
  'Conclusion: measure state changes and waiting causes over a complete, defined period before assigning a queue. Evidence supports a bounded Philippines-based support lane when ordinary work is separable, exceptions have an owner, and the service promise includes the real approval and dependency path.'
 ],sources:[worldBank,nist],related:['research-aug14-case-mix-drift','research-outsourced-demand-forecasting'],cta:'Use the queue evidence to set a bounded coverage assumption.'},
 {slug:'research-aug17-input-completeness-boundary',title:'Measure input completeness before delegating Philippines admin work',excerpt:'Incomplete inputs can turn a simple administrative lane into repeated clarification and hidden owner work.',published:'2026-08-17',body:[
  'Research question: how much of a proposed Philippines-based administrative queue arrives with enough context to be handled safely? Define one input as the record available at assignment, not the eventual thread after several questions. The result should distinguish missing fields from ambiguous instructions and from unavailable systems.',
  'Review a fixed sample of at least four weekly cohorts, retaining the work type, required fields, source, deadline, and consequence of delay. Report the number eligible at first receipt, the number needing clarification, and the number that could not proceed. This is an input study, not a claim about worker quality.',
  'Completeness is purpose-specific. A calendar request may need participants, time zone, duration, and authority to invite; an order update may need the order identifier, current status, and approved response boundary. Do not mark a record complete because it contains many words or because a familiar person can infer the missing decision.',
  'The SBA emphasizes clear responsibilities and expectations. For delegated work, the expectation must include what arrives before handling begins and who supplies a missing fact. If the specialist is repeatedly asked to reconstruct context from private messages, the process is transferring decision risk rather than making work repeatable.',
  'Compare clarification by source and category. A high clarification rate may indicate a weak intake channel, a changing rule, or an owner who has not stated the finish line. It does not automatically justify adding capacity. Record the answer that resolved each case and whether that answer should become a reusable field or instruction.',
  'NIST’s identify and protect functions make data minimization relevant: completeness does not mean collecting every possible detail. Ask only for fields necessary for the permitted action. Sensitive information that is unnecessary for the task is a control failure even when the record is otherwise complete.',
  'Limitations matter. A sample may undercount silent assumptions because some staff never ask and simply choose a default. It also cannot show whether the final decision was correct unless the outcome is reviewed. Repeat the test after changing the intake form or source-of-truth rule, and keep the definitions stable enough to compare cohorts.',
  'Conclusion: delegate the work only when the minimum input is observable, the missing-information route is owned, and the specialist can stop without guessing. Input completeness is a boundary condition for Philippines-based admin support, not a score attached to an individual.'
 ],sources:[sba,nist,worldBank],related:['research-aug14-work-instruction-ambiguity','research-aug14-source-authority-mapping'],cta:'Use the findings to improve the intake boundary before adding capacity.'},
 {slug:'research-aug17-owner-decision-latency',title:'Separate owner decision latency from Philippines support handling time',excerpt:'A delegated queue can look slow when the real waiting point is an approval or missing decision held by the client.',published:'2026-08-17',body:[
  'Research question: where does elapsed time accumulate in a Philippines-based support lane, and which portion is actually handling time? Define handling as time while the assigned specialist can act, waiting as time blocked by a source, approval, access, or owner decision, and rework as time spent correcting a returned item.',
  'Use timestamped cases from one complete month. For each case, preserve assignment, first action, pause reason, owner response, completion, and final acceptance. Report medians and ranges by category; an average alone can be dominated by one exceptional customer or vendor case.',
  'This distinction matters for time-zone work. A Filipino specialist may complete the permitted preparation during their shift but cannot authorize a policy exception or make a promise to a customer. Treating the approval interval as worker handling time encourages the wrong intervention and can quietly pressure people to act beyond authority.',
  'NIST’s govern and respond functions support explicit decision ownership. Name the person who can answer the blocked question, the evidence they need, and the point at which the case is escalated. A route that says “follow up” without a decision owner records activity but does not reduce latency.',
  'Compare cases with complete inputs to cases needing clarification, and ordinary cases to exceptions. If handling time is stable but waiting time rises, investigate decision capacity or source availability. If rework rises, inspect the acceptance rule and examples before concluding that more coverage is needed.',
  'The ILO’s decent-work framing cautions against treating constant availability as the measure of a digitally mediated role. A fair operating design records waiting causes and gives the specialist a defined stop condition. The goal is a clearer service promise, not an expectation that someone remains online until another owner answers.',
  'The evidence cannot establish causation from timestamps alone. A new tool, changed priority, or unusual demand mix may affect all intervals. Keep the work category and period visible, and revisit the interpretation after one controlled change rather than comparing incomparable months.',
  'Conclusion: publish a latency view with handling, waiting, and rework separated. A Philippines-based lane is easier to govern when the manager sees the decisions they own and the specialist is evaluated on the portion they can actually control.'
 ],sources:[nist,ilo],related:['research-aug14-escalation-thresholds','research-aug14-case-mix-drift'],cta:'Use the latency breakdown to clarify the real owner decision path.'},
 {slug:'research-aug17-access-scope-fit',title:'Match system access to the actual Philippines support task',excerpt:'Access should follow the narrowest action a Filipino specialist needs, with evidence for exceptions and recovery.',published:'2026-08-17',body:[
  'Research question: does a proposed Philippines-based support role require the access requested, or can the same outcome be produced with narrower permissions? Examine one concrete task, its source records, permitted actions, and consequence of error. A job title is not an access justification.',
  'Map the task from input to handoff. Record which system is read, which field is prepared or changed, whether export is necessary, and who approves an irreversible action. Test with representative ordinary and exception cases while excluding unnecessary personal information from the sample.',
  'NIST CSF 2.0 places governance and identification before protection. That sequence is useful for outsourced work: the client must first name the accountable owner and understand the information flow, then choose authentication, role permissions, logging, and review. A broad shared login is not evidence of efficient collaboration.',
  'For a Filipino administrative or customer-support specialist, a practical boundary may allow record lookup, draft preparation, status updates, and an escalation note while reserving refunds, policy changes, access grants, and unusual commitments for the manager. The boundary should be visible in examples, not implied by trust.',
  'Review access events or a small set of work records for actions outside the expected path. Separate a permission that was technically available from an action that was actually taken. If the role cannot be performed without a broad permission, redesign the task or accept the risk explicitly rather than granting access by habit.',
  'The World Bank’s data-governance framing supports preserving provenance and purpose. Keep a record of why a field is needed, where it came from, and who may rely on it. Data minimization can improve both security and work quality by reducing the number of conflicting fields a specialist must interpret.',
  'Limitations: a point-in-time review cannot prove that permissions remain appropriate after a tool or scope change. It also cannot replace the system owner’s security assessment. Recheck when the work lane adds a system, customer segment, export, or decision authority.',
  'Conclusion: access fit is demonstrated when each permission has a task-level reason, a named owner, and a stop or recovery path. Narrow, reviewable access gives Philippines-based support a fair operating boundary and the client a clearer risk decision.'
 ],sources:[nist,worldBank],related:['research-outsourced-data-access-boundaries','research-aug14-reversible-scope-pilot'],cta:'Use the task map to review access before a support lane begins.'},
 {slug:'research-aug17-escalation-load',title:'Estimate escalation load before expanding Philippines-based support',excerpt:'The number and consequence of escalations determine the manager time a delegated lane really requires.',published:'2026-08-17',body:[
  'Research question: what escalation load would a proposed Philippines-based work lane create for its manager? Count each case routed for a decision, not each message sent. Classify the reason as missing information, authority boundary, sensitive data, policy exception, dependency, or consequence.',
  'Use a complete observation period and preserve the population: arrivals, ordinary completions, escalations, unresolved cases, and owner response. Report escalation rate by work type and show the highest-consequence cases separately. Rare cases matter even when they barely affect a percentage.',
  'Escalations are not necessarily a defect. A Filipino specialist who stops at a clear authority boundary may be operating correctly. The useful question is whether the escalation contains the source record, what was checked, the uncertainty, and the exact decision requested. Incomplete escalations add manager work without improving safety.',
  'NIST’s govern, detect, and respond functions give a vocabulary for connecting signals to action. The owner should define which condition triggers a pause, who receives it, and what evidence is retained. “Use judgment” is not a substitute for an example of the decision that remains internal.',
  'Analyze repeated reasons. If most escalations ask the same definitional question, improve the SOP or source record. If they cluster around permissions, redesign access. If they concern customer promises or money, preserve the owner boundary instead of optimizing the rate downward.',
  'The SBA’s emphasis on responsibilities supports separating preparation from authorization. A support contributor can collect facts, draft options, and update a permitted status while the manager decides the exception. This division is especially important when the client and Filipino specialist work in different time zones.',
  'A short period can miss low-frequency high-impact cases, and recorded escalations can undercount unsafe silent decisions. Review a small sample of ordinary completions for missed triggers. State what the evidence does not prove before using the rate to plan manager capacity.',
  'Conclusion: expansion is plausible only when the owner can absorb the observed escalation load, the highest-consequence triggers are explicit, and repeated low-value escalations are converted into clearer inputs or boundaries.'
 ],sources:[nist,sba],related:['research-aug14-escalation-thresholds','research-outsourced-escalation-design'],cta:'Use escalation reasons to size review capacity and improve the role boundary.'},
 {slug:'research-aug17-correction-cost',title:'Measure correction cost in Philippines-based administrative work',excerpt:'A correction is more than a defect count: it shows where a source, rule, access boundary, or review step failed.',published:'2026-08-17',body:[
  'Research question: what kind of correction occurs after Philippines-based administrative work is marked complete, and what does it cost the operating lane? Define a material correction as a change needed to make the record or handoff usable, then separate missing evidence, wrong value, wrong status, unauthorized action, and unclear escalation.',
  'Review accepted work and later returns from three comparable monthly samples. Keep the original input, action, reviewer finding, correction time, and downstream consequence. Do not count every edit as an error; a manager preference differs from a factual or control failure.',
  'A correction rate without a stable denominator is easy to misuse. State whether the denominator is all completed records, reviewed records, or only records returned by a downstream owner. If the sample is risk-shaped, say so. The result supports a targeted decision, not a universal quality claim.',
  'The World Bank’s data perspective makes provenance central. When a field is corrected, preserve what source was authoritative and whether the original record was ambiguous. A repeated wrong value may be an input or source-of-truth problem rather than a training issue for the Filipino specialist.',
  'Compare correction type with work category and input condition. If incomplete cases drive returns, improve intake. If exceptions drive them, adjust escalation examples. If routine cases fail because the system is difficult to interpret, review access and interface design before increasing review volume.',
  'NIST’s detect and recover functions suggest treating corrections as signals that should lead to a response and a restored trusted state. The correction should identify who accepted the fix, what related records were checked, and whether a customer or vendor promise was affected.',
  'Limitations include undetected errors, corrections made outside the tracked system, and samples that exclude sensitive cases. A low observed rate is not proof of low risk. Pair the result with a targeted audit of consequential cases and revisit the rule after any process change.',
  'Conclusion: use correction cost to improve the system around the work. A bounded Philippines-based lane becomes more reliable when the client can distinguish individual handling mistakes from unclear inputs, sources, permissions, and review rules.'
 ],sources:[worldBank,nist],related:['research-aug14-accuracy-denominator','research-outsourced-accuracy-sampling'],cta:'Use correction evidence to improve the work lane rather than chase a single score.'},
 {slug:'research-aug17-continuity-recovery-state',title:'Define the last trusted state for Philippines remote-work continuity',excerpt:'Continuity depends on knowing what can safely resume after connectivity, system, access, or approval disruption.',published:'2026-08-17',body:[
  'Research question: after a disruption, what evidence lets a Philippines-based remote support lane resume without duplicating work or making stale decisions? Define the last trusted state as the latest record whose owner, status, source, and next action have been verified.',
  'Examine one ordinary cycle and one dependency review. Map connectivity, identity access, source systems, approvals, customer promises, and fallback ownership. Record which work can pause, which needs an internal decision, and which can resume from a protected queue.',
  'Continuity is not a promise that all output continues. It is a bounded decision about what remains safe, what is delayed, and what changes in the service promise. For Filipino staff working remotely, the design should avoid asking a person to improvise around an unavailable system or to remain continuously available without a clear recovery rule.',
  'NIST’s recover function asks how an organization restores capability and communicates the result. Applied to delegated work, recovery needs a named owner, a source of truth, a duplicate-prevention check, and a criterion for reopening ordinary handling. A backup person is not a recovery state by itself.',
  'The World Bank’s research on data and digital capability supports treating connectivity and information access as operating dependencies. Keep a dependency map with the task, not as a generic emergency document. The relevant fallback for a customer promise may differ from the fallback for an internal report.',
  'Test the handoff with a small set of cases. Can the receiving owner identify what was done, what remains, what evidence is current, and what must not be repeated? If not, the lane is not recoverable enough to expand, even if ordinary throughput looks strong.',
  'This evidence cannot predict every correlated disruption or prove that a recovery plan will work under stress. It shows whether the stated assumptions are visible and testable. Revisit after a system change, access change, geography change, or material shift in work sensitivity.',
  'Conclusion: a Philippines-based remote lane has credible continuity when its last trusted state, fallback owner, pause rule, and resumption evidence are explicit. Honest narrowing is part of continuity, not evidence of failure.'
 ],sources:[nist,worldBank,ilo],related:['research-aug14-continuity-dependency-map','research-outsourced-continuity-planning-philippines'],cta:'Use a recovery-state test to review continuity assumptions.'},
 {slug:'research-aug17-case-mix-delegation',title:'Compare case mix before widening a Philippines support role',excerpt:'A role that handles routine records may not fit urgent, incomplete, or consequence-heavy cases in the same queue.',published:'2026-08-17',body:[
  'Research question: does the observed case mix support widening a Philippines-based support role, or would the new categories change judgment, access, or review requirements? Define cohorts before reviewing outcomes: routine, urgent, incomplete, sensitive, owner-dependent, and corrected cases.',
  'Use at least four consecutive weekly cohorts and report counts plus proportions. Retain the rule used to classify each case. If the classification changes mid-period, mark the break; otherwise a better-looking result may simply reflect a new definition.',
  'A stable completion measure can conceal a shift toward harder work. A Filipino specialist may complete routine status updates consistently while urgent customer exceptions increasingly require the manager. Treat the mix as a service-design variable, not a footnote to productivity.',
  'The SBA’s role and expectation guidance supports reviewing the proposed scope against actual responsibilities. Ask whether the added category requires a new tool, new evidence, a new approval, or a different response window. If yes, it is a scope change even when the queue name remains the same.',
  'Compare each cohort’s waiting, correction, escalation, and acceptance pattern. Avoid ranking categories by one score. An exception category with low volume may still need a stronger boundary because its consequence is higher than a routine record’s.',
  'NIST’s identify and govern functions support documenting information exposure, decision authority, and dependency before expanding. The manager should approve the boundary and retain decisions that can change policy, money, identity, or customer commitments.',
  'Limitations: four weeks may be too short for seasonal or event-driven work, and cohort labels may miss latent complexity. Use the result to decide what to test next, not to claim that the role is permanently suitable or unsuitable.',
  'Conclusion: widen a Philippines support role only when the new case mix is separately understood, the evidence and access still fit, and manager review capacity covers the changed consequence profile.'
 ],sources:[sba,nist],related:['research-aug14-case-mix-drift','research-aug14-review-sample-design'],cta:'Use cohort evidence before adding a new category to the role.'},
 {slug:'research-aug17-source-freshness',title:'Test source freshness before delegating customer follow-up in the Philippines',excerpt:'A complete customer record can still be too old for the action a Filipino specialist is being asked to prepare.',published:'2026-08-17',body:[
  'Research question: how fresh must a source record be for a Philippines-based specialist to prepare a safe follow-up? Define freshness by action and consequence, not by one universal age rule. A scheduling confirmation, order update, and sensitive account decision may need different evidence windows.',
  'Review one month of dated records and compare last verification, changed fields, source system, action taken, and outcome. Separate records that were fresh enough, records that required re-verification, and records that should have stopped. Preserve the source timestamp rather than inferring freshness from a message date.',
  'Freshness is not the same as completeness. A record with every field can be stale, while a newer record can be incomplete. For delegated customer work, state which fields matter to the action and who is allowed to verify or change them.',
  'The World Bank’s data framing supports matching data quality to the decision that uses it. A general customer database may be useful context but not authority for a consequential commitment. The specialist should be able to identify the source of truth and escalate when it is unavailable or contradictory.',
  'Compare freshness failures by action type and source. If one system routinely lags, improve the dependency or narrow the action. If owners change fields without a trace, the problem is provenance. Do not solve stale evidence by asking the specialist to guess what is probably current.',
  'NIST’s protect and detect functions make access and monitoring part of the boundary. Limit the fields visible to what the task needs, preserve a verification note, and route contradictory or sensitive information to the accountable owner.',
  'The observation window cannot establish the correct freshness period for every future event. Seasonal demand, policy changes, and customer risk may alter it. State the chosen window, its reason, and the evidence that would cause review.',
  'Conclusion: customer follow-up is suitable for Philippines-based support when action-specific freshness rules are visible, verification is possible within authority, and stale or conflicting records have a clear stop path.'
 ],sources:[worldBank,nist],related:['research-aug14-customer-record-freshness','research-aug17-input-completeness-boundary'],cta:'Use action-specific freshness evidence to protect delegated follow-up.'},
 {slug:'research-aug17-scope-reversal-readiness',title:'Test reversal readiness before expanding Philippines-based outsourced work',excerpt:'A reversible scope has a trusted record, a pause trigger, and an owner who can narrow the lane without losing control.',published:'2026-08-17',body:[
  'Research question: if a proposed Philippines-based work lane proves unsafe or unsuitable, can the client pause or narrow it without losing the state of work? Define reversal readiness as the ability to identify affected records, stop new handling, restore a trusted owner decision, and communicate the changed promise.',
  'Inspect the proposed scope, permissions, source records, open queue, approval path, and recovery owner. Test one ordinary case and one exception. Record the last trusted state, what the specialist may finish, what must pause, and how the client would prevent duplicate or contradictory actions.',
  'A “we can stop” statement is not evidence. Reversibility requires a trigger that someone can recognize, a named person with authority, a current queue, and a defined fallback. It also requires that the specialist is not blamed for pausing when the trigger is reached.',
  'NIST’s recover function provides a useful frame for restoring capability and communicating status. In a delegated lane, restoration may mean returning decisions to the manager, narrowing records to a safe subset, or replacing a source—not necessarily restoring the original volume immediately.',
  'The World Bank’s emphasis on data governance supports preserving provenance during reversal. Keep the source, status, timestamp, and action history together. If the owner cannot tell which records were handled under the changed rule, the scope was not reversible enough to expand.',
  'Review reversal readiness after changes in customer segment, system access, response promise, or work consequence. A role may be reversible for internal reports but not for live customer commitments. Make the boundary category-specific rather than relying on a generic emergency instruction.',
  'Limitations: a tabletop or small test cannot reproduce every disruption, and a reversal may still carry customer or operational cost. State those limits and define what evidence is needed before widening the scope again. Narrowing is an evidence-led decision, not a failure claim.',
  'Conclusion: expand only when pause, record recovery, owner authority, and communication are testable. Reversal readiness protects both the client’s decision rights and the Filipino specialist’s ability to work within a fair boundary.'
 ],sources:[nist,worldBank],related:['research-aug14-reversible-scope-pilot','research-aug14-continuity-dependency-map'],cta:'Use a reversal test to make scope decisions safer.'}
] as const;
