type Source = { name: string; url: string };
const nist: Source = { name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' };
const gao: Source = { name: 'GAO Standards for Internal Control in the Federal Government', url: 'https://www.gao.gov/products/gao-14-704g' };
const dol: Source = { name: 'U.S. Department of Labor: Misclassification Initiative', url: 'https://www.dol.gov/agencies/whd/flsa/misclassification' };
const ilo: Source = { name: 'ILO: Working from home, from invisibility to decent work', url: 'https://www.ilo.org/publications/major-publications/working-home-invisibility-decent-work' };
const image = '/illustrations/getillustrations/goodle-business/controlled-operations-team.svg';

export const september10ResearchRecords = [
  { slug: 'research-outsourced-queue-reopen-rate', title: 'What does a reopened outsourced work item actually measure?', excerpt: 'A cohort design that separates incomplete work, changed requests, reviewer variation, and system events.', sources: [gao, nist, ilo], related: ['research-outsourced-correction-recurrence'], cta: 'Define one reopen taxonomy before extracting a cohort.', body: [
    'Scope: examine every item first closed in one outsourced work lane during a fixed four-week period. Include items later reopened, corrected without reopening, cancelled, or still disputed. Define closure, reopening, and the unit of work before extraction.',
    'Methodology: join the queue history, instruction version, reviewer note, change log, and final disposition by stable identifier. Code each reopen as missing required work, changed request, new information, reviewer disagreement, system event, duplicate, or unresolved. Double-code a sample and report disagreements, exclusions, missing histories, counts, and rates.',
    'Inference boundaries: GAO, NIST, and ILO provide principles for records, governance, monitoring, and remote work. They do not set an acceptable reopen rate or prove that a worker, reviewer, vendor, or location caused a reopening. The study is descriptive and supports a narrower process test.',
    'Limitations: deleted events, informal approvals, changing queue definitions, unequal case difficulty, and repeated items can bias results. A low rate can also reflect failures to reopen. Report the denominator and taxonomy with the result. References are listed below so readers can inspect the primary guidance used.',
  ] },
  { slug: 'research-philippines-content-source-age', title: 'How old are the sources behind a Philippines content queue?', excerpt: 'A source-age audit that distinguishes publication date, last review, effective date, and page retrieval.', sources: [gao, nist, ilo], related: ['research-filipino-research-source-freshness'], cta: 'Audit one content cohort using recorded source dates.', body: [
    'Scope: review a consecutive set of articles prepared in one Philippines content lane under one editorial policy. Include published, rejected, returned, and cancelled drafts. Measure source dates only for factual claims selected by a documented sampling rule.',
    'Methodology: record each sampled claim, cited source, source owner, publication or effective date, retrieval date, and whether a newer authoritative version existed at review time. Keep undated pages in a separate category. Have a second reviewer check a subset and publish the sampling rule, cohort size, exclusions, and missing dates.',
    'Inference boundaries: the cited frameworks support reliable information, monitoring, and remote-work context. They do not establish a universal freshness limit or show that older evidence is wrong. Source age is an audit signal, not a quality verdict and not a geographic comparison.',
    'Limitations: web pages change without version histories, durable standards may remain valid for years, and fast-changing topics need different thresholds. Search visibility can affect which sources reviewers find. Report age alongside authority, relevance, and supersession status. References appear below.',
  ] },
  { slug: 'research-outsourced-role-scope-drift', title: 'Can change records reveal scope drift in outsourced roles?', excerpt: 'A longitudinal record review of added tasks, permissions, decisions, and acceptance criteria.', sources: [nist, gao, dol], related: ['research-outsourced-change-control'], cta: 'Build a dated scope history for one active role.', body: [
    'Scope: compare the approved starting brief for one outsourced role with every documented change over a defined six-month window. Include added and retired tasks, tool permissions, decision rights, review duties, schedule changes, and acceptance criteria.',
    'Methodology: construct a dated change history from approved briefs, access records, tickets, and decision logs. Classify changes by risk and whether the accountable owner approved them before use. Verify unclear events with the record owner, retain unknowns, and report both the number and substance of changes.',
    'Inference boundaries: NIST and GAO inform governance and change records. Department of Labor material explains why worker classification depends on applicable facts and law. None of these sources determines a site-specific classification, proves harmful drift, or substitutes for legal review.',
    'Limitations: missing early records, renamed tasks, temporary coverage, and undocumented verbal decisions can distort the history. One role cannot represent a provider or country. The review detects differences in recorded scope; it does not decide legal status, intent, or business value. References are listed below.',
  ] },
  { slug: 'research-remote-handoff-question-load', title: 'How many questions does a remote handoff create before work resumes?', excerpt: 'A retrieval study of clarification demand, answer latency, and missing context in distributed operations.', sources: [ilo, gao, nist], related: ['research-filipino-admin-record-recoverability'], cta: 'Observe one complete handoff cohort without changing the process.', body: [
    'Scope: study handoffs in one recurring remote operations lane across a fixed calendar month. Include handoffs that resumed immediately, needed clarification, expired, returned to the sender, or remained open. Define a substantive question before reviewing messages.',
    'Methodology: link each handoff record to authorized follow-up messages and state changes. Count substantive questions, time to first useful answer, time to resumed work, and missing fields under a preregistered codebook. Double-code a subset and separate questions caused by new events from questions caused by the saved handoff.',
    'Inference boundaries: ILO, GAO, and NIST offer context for remote work, documentation, and governance. They provide no universal question threshold and cannot show that fewer questions always mean a better handoff. Associations do not establish causation.',
    'Limitations: private channels, silent guessing, time-zone schedules, access outages, urgency, and case complexity affect both questions and restart time. Message count may reward under-reporting. Use the findings to test one record change, then repeat the same measurement. References are below.',
  ] },
  { slug: 'research-outsourced-access-request-completeness', title: 'Are outsourced access requests complete before approval review?', excerpt: 'A blinded checklist study of business purpose, permission scope, duration, owner, and revocation plan.', sources: [nist, gao], related: ['research-temporary-access-expiry-outsourced-teams'], cta: 'Sample one system and publish the completeness rubric.', body: [
    'Scope: evaluate every access request submitted for one outsourced work lane and one system during a fixed quarter. Include approved, rejected, returned, withdrawn, emergency, and pending requests. Define required evidence from the policy in force when each request was submitted.',
    'Methodology: before viewing disposition, reviewers score whether each request records business purpose, named person, requested permission, accountable sponsor, duration or review date, and revocation path. Double-code a random subset, reconcile disagreements, and report missing fields by request outcome without treating approval as proof of completeness.',
    'Inference boundaries: NIST and GAO support access governance, accountability, and control evidence. They do not prescribe this exact checklist, certify a request, or prove that incomplete documentation caused an incident. The analysis describes record completeness within the selected system and period.',
    'Limitations: emergency procedures, inherited access, bundled roles, policy changes, and evidence stored outside the request can cause misclassification. Complete paperwork does not show that access was appropriate or used safely. A system-level sample cannot be generalized to all outsourced work. References are listed below.',
  ] },
].map((record) => ({ ...record, published: '2026-09-10', image, headlineStat: undefined, keyStats: undefined, takeaways: undefined, service: undefined, faqs: undefined }));
