type Source={name:string;publisher:string;url:string;checked:string};
const published='2026-09-28',image='/filipino-operations-specialist.svg';
const source=(name:string,publisher:string,url:string):Source=>({name,publisher,url,checked:published});
const nist=source('NIST Cybersecurity Framework 2.0','National Institute of Standards and Technology','https://www.nist.gov/cyberframework');
const privacy=source('NIST Privacy Framework','National Institute of Standards and Technology','https://www.nist.gov/privacy-framework');
const identity=source('NIST Digital Identity Guidelines','National Institute of Standards and Technology','https://pages.nist.gov/800-63-4/');
const gao=source('The Green Book: Standards for Internal Control in the Federal Government','U.S. Government Accountability Office','https://www.gao.gov/greenbook');
const ftc=source('Cybersecurity for Small Business','Federal Trade Commission','https://www.ftc.gov/business-guidance/small-businesses/cybersecurity');
type Input={slug:string;title:string;excerpt:string;decision:string;unit:string;facts:string[];risks:string[];tests:string[];owners:string[];sources:Source[];related:string[]};
function make(p:Input){
 const body=[
 `Decision and boundary. ${p.title} The narrow decision is whether a Philippines-based specialist can prepare ${p.decision} while accountable managers retain consequential authority. Study ${p.unit}. Do not treat the specialist's location, a clean completion count, or a short response time as evidence that judgment transferred safely. The proposed lane needs a source of truth, permitted actions, explicit stops, response coverage, and a reversible finish state.`,
 `Population. Build a consecutive cohort of ${p.unit}. Include ordinary, incomplete, corrected, cancelled, escalated, reopened, and still-waiting units. Freeze the observation window, timezone, system versions, policy version, eligibility rules, and exclusions before viewing outcomes. Link later corrections to the original unit so rework cannot masquerade as new throughput. Report every removed unit and the reason it was removed.`,
 `Required evidence. A reviewable packet preserves ${p.facts.join(', ')}. Each field should identify its authoritative system, observation time, relevant version, and actor. Stable record identifiers are preferable to copied sensitive material. Conflicting fields remain visible until an authorized owner resolves them; a corrected record should retain enough history to explain what changed and why.`,
 `Authority map. The specialist may gather records, compare approved fields, identify gaps, apply written classifications, and draft a proposed next step. The specialist may not decide ${p.owners.join(', ')}. Translate that division into platform permissions, templates, and queue states. If software cannot express the boundary, use preparation-only access or supervised temporary elevation rather than broad standing privileges.`,
 `Intake test. Require the requester, business purpose, affected record, requested outcome, priority basis, source links, and deadline. Park an item when identity, authority, or the source record cannot be established. A private message is not a substitute for an approved request. The intake check should prevent urgency from silently changing ${p.decision} into a larger mandate.`,
 `Failure modes. Test ${p.risks.join('; ')}. Also inspect stale screenshots, partial exports, shared accounts, copied identifiers, unrecorded calls, and approvals given outside the system. A tidy final status can conceal a broken decision trail. Geography may shape coverage hours, but it does not explain missing evidence or excuse a weak control.`,
 `Method. Review the full eligible cohort when practical. Otherwise select an ordinary sample before reviewers know results and a separately labelled risk sample. The risk sample should include the oldest, most sensitive, most disputed, most consequential, and most frequently corrected units. Publish sample counts, unavailable records, selection logic, and deliberate oversampling; never present a risk-shaped sample as an ordinary error estimate.`,
 `Measures. For ${p.decision}, calculate packet completeness, correct classification, boundary adherence, evidence retrieval, owner response, first-pass acceptance, return reasons, reopenings, and reviewer agreement. Show numerators and denominators. Split active preparation time from source waiting, decision waiting, and system delay. A safe stop can be a correct outcome, while fast completion can reflect a skipped control.`,
 `Independent review. Give a second reviewer the retained packet and the instruction version without revealing the first conclusion. Preserve both assessments. Classify disagreement as source authority, missing fact, identity, timing, rule interpretation, action consequence, or ambiguous guidance. An accountable owner resolves the current unit; the team changes future instructions prospectively instead of rewriting the earlier record to manufacture agreement.`,
 ...p.facts.map((fact,index)=>`${p.decision} field analysis ${index+1}. Examine ${fact} alongside ${p.risks[index%p.risks.length]}. In the ${p.tests[index%p.tests.length]} scenario, ask whether the retained ${fact} identifies the relevant source, event time, version, actor, and unresolved conflict. The Philippines-based preparer should record the comparison and route any question about ${p.owners[index%p.owners.length]} to the named owner. Acceptance requires a reviewer to recover the same ${p.decision} state without private explanation. A missing ${fact} leaves this unit waiting; it must not be inferred from a nearby record or replaced with a convenient assumption. Cross-check ${fact} against ${p.facts[(index+3)%p.facts.length]} before proposing ${p.decision}; the relationship can reveal whether ${p.risks[(index+1)%p.risks.length]}. Preserve the result for the ${p.tests[(index+2)%p.tests.length]} review and keep ${p.owners[(index+2)%p.owners.length]} outside the preparer's authority.`),
 `Scenario tests. Run ${p.tests.join('; ')}. For each scenario, record the expected stop, evidence that travels, receiving owner, response window, safest holding state, and restart condition. Include one normal case that should proceed and one tempting shortcut that should be refused. The test succeeds when another authorized person can reproduce the status and next action from shared records alone.`,
 `Facts and inference. System events, approved documents, recorded communications, timestamps, versions, and observed actions are facts only within their provenance and completeness. Coding patterns and comparing cohorts are analysis. Predicting that a redesigned control will improve results is inference. State uncertainty when records conflict, were created after the event, omit offline action, or cannot establish who made a decision.`,
 `Decision rule. Expand ${p.decision} only when predeclared thresholds are met for packet completeness, boundary adherence, owner response, correction quality, reviewer agreement, and reversibility. If evidence is missing at intake, repair intake. If complete packets wait, repair owner coverage. If reviewers disagree with complete evidence, clarify the rule or narrow scope. Adding labor does not cure an authority or information defect.`,
 `Pilot. Begin with historical or reversible units, then use a small supervised live cohort. Keep instructions, permissions, owners, acceptance rules, and thresholds stable during the measurement period unless safety requires intervention. A material change begins a new study period. Record the reason, effective time, affected open units, training confirmation, and rollback state before evaluating the changed design.`,
 `Privacy and security. Minimize collected fields, retain raw evidence in approved systems, use named accounts, and log permission changes. Do not copy protected content into email or chat merely to make review convenient. The specialist should not decide that an identity discrepancy is harmless or that extra data might be useful. Escalation should expose only what the authorized reviewer needs.`,
 `Continuity and removal. Simulate the absence of the specialist, manager, or integration. A designated backup should locate ${p.unit}, understand its current state, and complete or safely pause the next authorized action. Record missing access, stale links, private context, and recovery time separately. After the test, confirm that temporary access, downloads, tokens, and shared links are removed or expire as intended.`,
 `Fairness. Evaluate the work lane, instruction, evidence availability, access, and owner coverage before attributing a failure to an individual. Give comparable cases the same approved examples and review rubric. Separate delays caused by missing sources or unavailable managers from actions within the specialist's control. A correct escalation or refusal must not be scored as low productivity.`,
 `Limitations. A documentary review can miss deleted history, inherited permissions, offline discussions, unlogged exports, synchronization delays, and actions in another system. Short pilots may miss seasonality, outages, fraud, absence, and rare high-consequence cases. Reviewers can share the same mistaken interpretation. Complete records do not prove an unrecorded event never occurred, and this method supplies no universal benchmark.`,
 `Conclusion. ${p.decision} is suitable for a bounded outsourced lane only when the buyer can name the unit, authoritative records, evidence packet, permitted actions, stop conditions, owners, coverage window, review method, thresholds, and rollback. The cited authorities inform governance, identity, privacy, security, and internal-control design; they do not endorse OutsourcedLabor.com or prove a staffing result. The conclusion applies only to the studied workflow, systems, policy, permissions, and period.`
 ];
 return {...p,published,image,headlineStat:undefined as string|undefined,keyStats:undefined as string[]|undefined,takeaways:undefined as string[]|undefined,service:undefined as {heading:string;body:string;href:string;label:string}|undefined,faqs:undefined as {q:string;a:string}[]|undefined,cta:`Map a bounded ${p.decision} lane before delegating live work.`,body};
}
export const september28ResearchRecords=[
make({slug:'research-philippines-customer-service-credit-evidence',title:'What evidence should a Philippines-based specialist prepare before a customer service credit?',excerpt:'A decision framework for contract, incident, usage, prior concession, and approval evidence without transferring credit authority.',decision:'customer service-credit preparation',unit:'one requested credit tied to one customer account, service event, stated reason, and proposed amount',facts:['the authenticated request','account and contract identifiers','applicable service commitment','incident and usage records','prior concessions','calculation inputs','proposed amount and form','customer draft','approval','ledger event','closure notice'],risks:['incident times differ across systems','a contract exception is mistaken for a standard entitlement','duplicate requests arrive through separate channels','a draft promise reaches the customer before approval'],tests:['a documented outage within a clear rule','a disputed service period with conflicting clocks','a repeat request after a prior concession','an amount above the specialist threshold'],owners:['contract interpretation','entitlement','exception approval','credit amount','ledger posting','the final customer commitment'],sources:[gao,nist,ftc],related:['research-philippines-order-refund-exception-packet','research-philippines-support-escalation-signal-quality','research-outsourced-work-acceptance']}),
make({slug:'research-outsourced-vendor-tax-record-change-boundary',title:'How should outsourced procurement support prepare a vendor tax-record change?',excerpt:'A controlled comparison of vendor identity, tax documents, master data, payment dependencies, and approvals.',decision:'vendor tax-record change preparation',unit:'one requested change to one vendor tax identity or classification record',facts:['the request and channel','existing vendor master record','approved tax document','legal-name and address comparison','requester identity','independent contact result','affected entities','open orders and invoices','review notes','owner decision','master-data audit event'],risks:['a compromised mailbox supplies plausible documents','a legal name change is confused with a new entity','tax and payment records diverge','an obsolete attachment is reused for another buying entity'],tests:['a formatting correction with matching identifiers','a legal-name change supported by authoritative records','conflicting taxpayer identifiers','a request bundled with new bank details'],owners:['tax classification','document sufficiency','vendor identity acceptance','payment release','legal interpretation','master-data approval'],sources:[identity,nist,gao],related:['research-philippines-vendor-bank-detail-change-verification','research-outsourced-vendor-due-diligence-evidence-boundary','research-outsourced-invoice-preparation-duplicate-payment-controls']}),
make({slug:'research-philippines-crm-suppression-reconciliation',title:'Can Philippines-based CRM support reconcile suppression records without deciding consent?',excerpt:'A field-level method for comparing requests, channel states, sync events, conflicts, and owner decisions.',decision:'CRM suppression reconciliation',unit:'one contact-channel-purpose combination with a suppression request or conflicting communication state',facts:['request provenance','contact and account identifiers','channel and stated purpose','identity evidence required by policy','consent and suppression history','source-system timestamps','integration events','campaign eligibility state','conflicts','owner decision','propagation check'],risks:['one channel state is applied to every purpose','an integration restores an older value','duplicate contacts carry different histories','a manual import bypasses the canonical suppression field'],tests:['an ordinary email opt-out','conflicting CRM and messaging-platform states','duplicate records with different suppression dates','a request whose identity evidence is incomplete'],owners:['legal basis','identity exceptions','consent interpretation','retention exceptions','campaign eligibility policy','irreversible deletion'],sources:[privacy,identity,nist],related:['research-outsourced-crm-record-export-approval-boundary','research-outsourced-crm-duplicate-merge-decision-evidence','research-outsourced-crm-data-stewardship-minimum-access']}),
make({slug:'research-outsourced-inventory-transfer-discrepancy-packet',title:'What belongs in an outsourced inventory-transfer discrepancy packet?',excerpt:'A traceable workflow for origin, transit, receipt, quantity, lot, condition, and system evidence while owners retain adjustment authority.',decision:'inventory-transfer discrepancy preparation',unit:'one transfer between two controlled locations with a quantity, identity, timing, or condition discrepancy',facts:['transfer order and version','origin pick and dispatch records','carrier or custody events','destination receipt','item lot and serial identifiers','quantities and units','condition evidence','cutoff times','open movements','proposed reconciliation','approval','final system events'],risks:['units of measure differ between sites','partial receipts hide under one transfer','labels are reused or mis-scanned','a late system event appears to resolve a physical shortage'],tests:['a straightforward timing lag','a partial shipment across two receipts','a lot-identity conflict','damaged goods awaiting disposition'],owners:['inventory adjustment','valuation','loss attribution','quality disposition','carrier claim','release of held stock'],sources:[gao,nist,privacy],related:['research-philippines-inventory-quarantine-release-readiness','research-philippines-inventory-reconciliation-evidence-design','research-outsourced-acceptance-evidence-quality']}),
make({slug:'research-philippines-proof-of-delivery-correction-controls',title:'Which controls belong before Philippines-based support corrects proof-of-delivery data?',excerpt:'A bounded review of shipment events, recipient evidence, location, attachments, customer disputes, and correction authority.',decision:'proof-of-delivery correction preparation',unit:'one proposed correction to delivery status, recipient, time, location, or supporting evidence for one shipment',facts:['order and shipment identifiers','carrier events','original proof record','recipient and location fields','attachment provenance','customer contact','driver or site statement','system timestamps','dispute status','proposed correction','owner approval','downstream notifications'],risks:['a screenshot loses carrier context','the recipient name exposes personal data','timezone conversion changes sequence','a status correction affects refund, claim, or customer promises'],tests:['a typographical recipient correction','conflicting carrier and customer evidence','an attachment tied to the wrong shipment','a correction requested after a financial dispute opens'],owners:['fraud conclusions','delivery acceptance','liability','claim submission','refund entitlement','customer compensation'],sources:[gao,nist,ftc],related:['research-philippines-vendor-delivery-exception-follow-up','research-philippines-order-delay-decision-boundary','research-philippines-dispatch-reroute-exception-boundary']})
] as const;
