type Source={name:string;publisher:string;url:string;checked:string};
const checked='2026-09-24',published=checked,image='/filipino-operations-specialist.svg';
const src=(name:string,publisher:string,url:string):Source=>({name,publisher,url,checked});
const nist=src('NIST Cybersecurity Framework 2.0','National Institute of Standards and Technology','https://www.nist.gov/cyberframework');
const identity=src('NIST Digital Identity Guidelines','National Institute of Standards and Technology','https://pages.nist.gov/800-63-4/');
const privacy=src('NIST Privacy Framework','National Institute of Standards and Technology','https://www.nist.gov/privacy-framework');
const gao=src('The Green Book: Standards for Internal Control in the Federal Government','U.S. Government Accountability Office','https://www.gao.gov/greenbook');
const dol=src('Recordkeeping and Reporting','U.S. Department of Labor','https://www.dol.gov/general/topic/wages/wagesrecordkeeping');
const ftc=src('Cybersecurity for Small Business','Federal Trade Commission','https://www.ftc.gov/business-guidance/small-businesses/cybersecurity');
type P={slug:string;title:string;excerpt:string;topic:string;unit:string;evidence:string;boundary:string;risks:string;sources:Source[];related:string[]};
const make=(p:P)=>({...p,published,image,headlineStat:undefined as string|undefined,keyStats:undefined as string[]|undefined,takeaways:undefined as string[]|undefined,service:undefined as {heading:string;body:string;href:string;label:string}|undefined,faqs:undefined as {q:string;a:string}[]|undefined,cta:`Pilot one bounded ${p.topic} queue before expanding access.`,body:[
`Decision context. ${p.title} The buyer decision is whether ${p.topic} can be divided into evidence collection, preparation, accountable review, and authorized action. Location and tool access do not create decision authority. A workable lane names the exact finish line, primary owner, backup owner, response window, and safe pause before work is assigned.`,
`Source foundation. The cited primary government sources establish broad concepts for identity, security, privacy, recordkeeping, or internal control. They do not endorse OutsourcedLabor.com, evaluate Filipino workers, prescribe this workflow, or prove savings, quality, compliance, or business results. The workflow design in this article is analysis. Contracts, system terms, sector rules, local law, and professional advice may require a different boundary.`,
`Research question. Ask whether a Philippines-based specialist can prepare a complete, traceable ${p.topic} record without making the consequential decision that the record informs. Use ${p.unit} as the unit of analysis. Define when an item enters the population, what makes it ready, which states count as paused or returned, and what evidence closes it. Keep reopened work linked to its first item so rework does not disappear.`,
`Method. Freeze the systems, channels, time zone, policy version, observation period, inclusion rules, and exclusions before reviewing outcomes. Include completed, pending, returned, cancelled, and escalated items. Review the full eligible population when practical. Otherwise select a reproducible ordinary sample and a separately reported risk-shaped sample before reviewers know the outcomes.`,
`Evidence packet. Preserve ${p.evidence} Each field should identify its authoritative system, observation time, relevant version, and actor. Prefer stable references or approved exports over copied sensitive content. Do not fill gaps from memory. Conflicting evidence stays visible until a named owner resolves it, and corrections retain the earlier state so another authorized reviewer can reconstruct what was known.`,
`Role boundary. ${p.boundary} Maintain three explicit lists: actions the specialist may complete, actions the specialist may prepare for review, and conditions that require a stop without change. Escalation should preserve the item, state the missing or conflicting fact, identify the decision required, name the owner, and show the consequence and deadline.`,
`Access design. Translate the work boundary into platform permissions. Test a permitted action, a blocked action, and an attempted route around the block. Interface roles can bundle exports, bulk edits, deletion, integrations, automation, impersonation, or inherited access. If the platform cannot express the intended boundary, use preparation-only work, supervised elevation, or a narrower lane rather than broad standing permission.`,
`Population and sampling. A convenience sample of clean completions cannot show how the lane behaves under uncertainty. Include ordinary work plus old, disputed, incomplete, reopened, sensitive, high-consequence, and overridden cases. Publish the population definition, selection method, sample count, exclusions, unavailable records, and missing fields. Report deliberate risk oversampling separately from any random portion.`,
`Measures. Report numerators and denominators for evidence completeness, correct classification, boundary adherence, owner response, rework, reopenings, and reviewer agreement. Separate active preparation from source waiting, owner waiting, and system delay. Throughput alone can reward unsafe shortcuts. An escalation or blocked action can be the correct outcome when it protects an authority boundary.`,
`Independent review. Give a second reviewer the packet and current rules without showing the first conclusion. Preserve both initial assessments. Classify disagreement as source authority, missing fact, identity, timing, policy interpretation, action consequence, or unclear instruction. An accountable owner resolves the case and changes standing guidance prospectively; the record should not be rewritten to create artificial agreement.`,
`Failure modes. ${p.risks} Additional risks include stale examples, screenshots without system context, shared accounts, private-message approvals, silent bulk changes, copied personal information, and deadlines measured from the wrong event. Different working hours can expose missing owner coverage, but geography by itself does not explain a control failure.`,
`Interpretation. If evidence is usually missing at intake, repair intake before adding labor. If packets are complete but wait, improve owner coverage or narrow the promise. If two reviewers disagree despite complete evidence, clarify policy or reduce scope. If failures cluster around one action, remove that action from standing access and examine it as a separate, supervised lane.`,
`Facts, analysis, and inference. System fields, timestamps, versions, messages, approvals, and observed actions are facts only to the extent their sources are authoritative and complete. Coding an exception or identifying a pattern is analysis. Predicting that a changed control will improve an outcome is inference. Report these layers separately and state when an important source cannot be recovered.`,
`Limitations. Exports may omit synchronizations, deleted history, inherited permissions, offline work, private messages, or actions in another system. Timestamps may reflect later entry rather than the event. A short period can miss seasonality, absence, fraud, outages, and rare consequential cases. Reviewers can share the same mistaken interpretation. A clean record does not prove that an event never occurred.`,
`Pilot design. Begin with historical or reversible items, then a small supervised live cohort. Freeze instructions, templates, permissions, and acceptance definitions during measurement unless safety requires a change. Predeclare thresholds for evidence recovery, classification, boundary adherence, response, and reversal. Any material change creates a new study period rather than being blended silently into earlier results.`,
`Privacy and security. Collect only fields needed for the stated decision, keep raw data in approved systems, use named accounts, and record access changes. The specialist should not decide that more data is convenient, that an identity discrepancy is harmless, or that an unusual request is routine. Escalation must preserve enough evidence for review without spreading sensitive content into new copies.`,
`Decision register. Create a versioned register naming the lane, unit, sources, required fields, permitted actions, stop conditions, owner decisions, response expectations, reviewers, thresholds, and removal trigger. Reconcile pilot records to the eligible source population and explain every unmatched item. The conclusion applies only to the studied workflow, system, permissions, policy, and period.`,
`Operational fairness. Evaluate the work lane rather than using a few errors or escalations as a proxy for an individual's ability or nationality. Give participants the same approved instructions, examples, access, owner coverage, and review rubric. Separate failures caused by unavailable evidence or delayed owner decisions from actions within the specialist's control. Safe refusal should not be scored as poor productivity.`,
`Change control. Version the instruction, access matrix, templates, field definitions, and acceptance thresholds. When a source, platform, policy, or owner decision changes, record what changed, why, who approved it, when it takes effect, and which open items need reassessment. Retire superseded copies and verify that search results, links, forms, and training point to the current version.`,
`Recovery test. Select at least one completed item and simulate the absence of the specialist, owner, or integration. Ask the designated backup to locate the record, understand its state, identify the next authorized step, and either complete or safely pause it without private context. Measure missing access, stale links, unclear ownership, and recovery time separately, then test timely access removal.`,
`Buyer conclusion. A defensible outsourced lane prepares reliable evidence and routine actions while keeping consequential judgment with the accountable owner. Before requesting a labor plan, the buyer should be able to name the queue, authoritative sources, permitted actions, stop conditions, owner coverage, review sample, and rollback path. Expand only when retained evidence supports that narrow decision.`,
]});
export const september24ResearchRecords=[
make({slug:'research-philippines-vendor-bank-detail-change-verification',title:'Which checks belong before a Philippines-based specialist prepares a vendor bank-detail change?',excerpt:'A controlled workflow separating evidence preparation from vendor identity, bank-detail acceptance, and payment authority.',topic:'vendor bank-detail change preparation',unit:'one requested change to one vendor payment profile',evidence:'the original request, known vendor record, requester identity, approved out-of-band contact path, callback evidence, proposed fields, change history, open invoices, risk signals, owner decision, and final audit event.',boundary:'Staff may assemble and compare evidence; they must not accept identity, choose a verification exception, alter bank data, release payment, or disclose protected account information without an authorized owner.',risks:'A compromised mailbox can imitate a known vendor, replies can remain inside the attacker-controlled thread, urgency can defeat independent verification, and broad permissions can combine preparation with payment capability.',sources:[ftc,nist,gao],related:['research-outsourced-invoice-preparation-duplicate-payment-controls','research-outsourced-vendor-due-diligence-evidence-boundary','research-outsourced-access-exception-expiry']}),
make({slug:'research-outsourced-sop-change-control-release-evidence',title:'What evidence should precede release of an outsourced SOP change?',excerpt:'A release protocol that preserves source authority, testing, approvals, affected work, and rollback without delegating policy ownership.',topic:'SOP change-control preparation',unit:'one proposed version of one operating procedure',evidence:'the change request, current approved version, source requirements, proposed text, affected roles and systems, reviewer comments, test cases, training impact, approval, effective time, superseded copies, and rollback path.',boundary:'Staff may reconcile inputs, draft language, and coordinate review; policy interpretation, risk acceptance, legal conclusions, approval, emergency exceptions, and final release remain accountable-owner decisions.',risks:'A polished draft can hide conflicting requirements, search may surface an obsolete copy, an effective date can precede training, and minor wording can silently expand authority or data access.',sources:[gao,nist,ftc],related:['research-aug14-source-authority-mapping','research-filipino-specialist-source-version-drift','research-outsourced-change-control']}),
make({slug:'research-philippines-dispatch-reroute-exception-boundary',title:'How should Philippines-based operations support prepare a dispatch reroute exception?',excerpt:'Evidence and decision boundaries for route disruption, service impact, safety signals, and owner-controlled dispatch changes.',topic:'dispatch reroute-exception preparation',unit:'one active dispatch assignment with one proposed route or destination change',evidence:'the original assignment, current location and timestamp, approved route data, disruption source, customer or site constraint, asset and operator status, service window, proposed options, safety flags, owner decision, messages, and final disposition.',boundary:'Staff may gather status and prepare reversible options; safety judgments, legal compliance, operator direction, customer commitments, priority conflicts, and the final reroute require the designated operations owner.',risks:'Location data can be stale, copied messages can omit later conditions, a faster option can violate an operating constraint, and ambiguous authority can cause two coordinators to issue conflicting instructions.',sources:[gao,nist,privacy],related:['research-philippines-support-escalation-signal-quality','research-philippines-order-delay-decision-boundary','research-outsourced-time-zone-handoffs']}),
make({slug:'research-outsourced-workforce-timesheet-correction-packet',title:'What belongs in an outsourced workforce timesheet-correction packet?',excerpt:'A record design for preparing time corrections while owners retain pay, classification, leave, discipline, and dispute decisions.',topic:'workforce timesheet-correction preparation',unit:'one proposed correction to one worker time record for one defined pay interval',evidence:'the original time record, source schedule, clock events, worker statement, manager record, applicable policy version, time zone, proposed correction, affected totals, exception reason, approval, system audit trail, and notification.',boundary:'Staff may check completeness and prepare a correction; deciding hours worked, pay treatment, classification, leave, discipline, disputed facts, retroactive exceptions, and final approval remains with authorized workforce and payroll owners.',risks:'Rounded exports can hide event times, schedules may differ from work performed, time-zone conversion can change the work date, and overwriting the original record can destroy the evidence needed to resolve a dispute.',sources:[dol,gao,privacy],related:['research-outsourced-workforce-schedule-change-record','research-philippines-operations-source-latency','research-aug13-record-lineage-check']}),
make({slug:'research-philippines-inventory-quarantine-release-readiness',title:'Can Philippines-based inventory support prepare quarantine-release evidence without owning release?',excerpt:'A bounded method for reconciling held inventory while quality, safety, valuation, and release decisions remain with accountable owners.',topic:'inventory quarantine-release preparation',unit:'one held inventory lot or uniquely identified item group',evidence:'item and lot identifiers, hold reason, quantity and location, receipt and movement history, applicable specification, inspection or test evidence, storage conditions, related orders, discrepancy record, proposed disposition, approvals, release event, and downstream reconciliation.',boundary:'Staff may reconcile records and assemble a release packet; they must not interpret safety requirements, waive specifications, choose disposition, adjust valuation, release stock, or substitute an approval.',risks:'Mixed lots can share a location, labels can outlive a system status, partial quantities can move under one record, missing test context can make a pass result misleading, and release in one system may not remove holds elsewhere.',sources:[gao,nist,ftc],related:['research-philippines-inventory-reconciliation-evidence-design','research-outsourced-acceptance-evidence-quality','research-philippines-quality-audit-corrective-action-follow-up']}),
] as const;
