type Source={name:string;publisher:string;url:string;checked:string};
const checked='2026-09-23',published=checked,image='/filipino-operations-specialist.svg';
const src=(name:string,publisher:string,url:string):Source=>({name,publisher,url,checked});
const nist=src('NIST Cybersecurity Framework 2.0','National Institute of Standards and Technology','https://www.nist.gov/cyberframework');
const identity=src('NIST Digital Identity Guidelines','National Institute of Standards and Technology','https://pages.nist.gov/800-63-4/');
const privacy=src('NIST Privacy Framework','National Institute of Standards and Technology','https://www.nist.gov/privacy-framework');
const gao=src('Standards for Internal Control in the Federal Government','U.S. Government Accountability Office','https://www.gao.gov/products/gao-14-704g');
const dol=src('Recordkeeping and Reporting','U.S. Department of Labor','https://www.dol.gov/general/topic/wages/wagesrecordkeeping');
type P={slug:string;title:string;excerpt:string;topic:string;unit:string;evidence:string;boundary:string;risks:string;sources:Source[];related:string[]};
const make=(p:P)=>({...p,published,image,headlineStat:undefined as string|undefined,keyStats:undefined as string[]|undefined,takeaways:undefined as string[]|undefined,service:undefined as {heading:string;body:string;href:string;label:string}|undefined,faqs:undefined as {q:string;a:string}[]|undefined,cta:`Pilot one bounded ${p.topic} queue before expanding access.`,body:[
`Decision context. ${p.title} The buyer decision is whether ${p.topic} can be divided into evidence collection, preparation, accountable review, and authorized action. Location and tool access do not create decision authority. A workable lane names the exact finish line, primary owner, backup owner, response window, and safe pause before work is assigned.`,
`Source foundation. The cited primary government sources establish broad concepts for identity, security, privacy, recordkeeping, or internal control. They do not endorse OutsourcedLabor.com, evaluate Filipino workers, prescribe this workflow, or prove savings, quality, compliance, or business results. The workflow design in this article is analysis. Contracts, system terms, sector rules, local law, and professional advice may require a different boundary.`,
`Research question. Ask whether a Philippines-based specialist can prepare a complete, traceable ${p.topic} record without making the consequential decision that the record informs. Use ${p.unit} as the unit of analysis. Define when an item enters the population, what makes it ready, which states count as paused or returned, and what evidence closes it. Keep reopened work linked to its first item so rework does not disappear.`,
`Method. Freeze the systems, channels, time zone, policy version, observation period, inclusion rules, and exclusions before reviewing outcomes. Include completed, pending, returned, cancelled, and escalated items. Review the full eligible population when practical. Otherwise select a reproducible ordinary sample and a separately reported risk-shaped sample before reviewers know the outcomes.`,
`Evidence packet. Preserve ${p.evidence} Each field should identify its authoritative system, observation time, relevant version, and actor. Prefer stable references or approved exports over copied sensitive content. Do not fill gaps from memory. Conflicting evidence stays visible until a named owner resolves it, and corrections retain the earlier state so another authorized reviewer can reconstruct what was known.`,
`Role boundary. ${p.boundary} Maintain three explicit lists: actions the specialist may complete, actions the specialist may prepare for review, and conditions that require a stop without change. Escalation should preserve the item, state the missing or conflicting fact, identify the decision required, name the owner, and show the consequence and deadline.`,
`Access design. Translate the work boundary into platform permissions. Test a permitted action, a blocked action, and an attempted route around the block. Interface roles can bundle exports, bulk edits, deletion, integrations, automation, impersonation, or inherited access. If the platform cannot express the intended boundary, use preparation-only work, supervised elevation, or a narrower lane rather than broad standing permission.`,
`Population and sampling. A convenience sample of clean completions cannot show how the lane behaves under uncertainty. Include ordinary work plus old, disputed, incomplete, reopened, sensitive, high-consequence, and overridden cases. Publish the population definition, selection method, sample count, exclusions, unavailable records, and missing fields. Report deliberate risk oversampling separately from any random portion.`,
`Measures. Report numerators and denominators for evidence completeness, correct classification, boundary adherence, owner response, rework, reopenings, and reviewer agreement. Separate active preparation from source waiting, owner waiting, and system delay. Throughput alone can reward unsafe shortcuts. An escalation or blocked action can be the correct outcome when it protects an authority boundary.`,
`Independent review. Give a second reviewer the packet and current rules without showing the first conclusion. Preserve both initial assessments. Classify disagreement as source authority, missing fact, identity, timing, policy interpretation, action consequence, or unclear instruction. An accountable owner resolves the case and changes standing guidance prospectively; the record should not be rewritten to create artificial agreement.`,
`Failure modes. ${p.risks} Additional risks include stale examples, screenshots without system context, shared accounts, private-message approvals, silent bulk changes, copied personal information, and deadlines measured from the wrong event. Different working hours can expose missing owner coverage, but geography by itself does not explain a control failure.`,
`Interpretation. If evidence is usually missing at intake, repair intake before adding labor. If packets are complete but wait, improve owner coverage or narrow the promise. If two reviewers disagree despite complete evidence, clarify policy or reduce scope. If failures cluster around one action, remove that action from standing access and examine it as a separate, supervised lane.`,
`Facts, analysis, and inference. System fields, timestamps, versions, messages, approvals, and observed actions are facts only to the extent their sources are authoritative and complete. Coding an exception or identifying a pattern is analysis. Predicting that a changed control will improve an outcome is inference. Report these layers separately and state when an important source cannot be recovered.`,
`Limitations. Exports may omit synchronizations, deleted history, inherited permissions, offline work, private messages, or actions in another system. Timestamps may reflect later entry rather than the event. A short period can miss seasonality, absence, fraud, outages, and rare consequential cases. Reviewers can share the same mistaken interpretation. A clean record does not prove that an event never occurred.`,
`Pilot design. Begin with historical or reversible items, then a small supervised live cohort. Freeze instructions, templates, permissions, and acceptance definitions during measurement unless safety requires a change. Predeclare thresholds for evidence recovery, classification, boundary adherence, response, and reversal. Any material change creates a new study period rather than being blended silently into earlier results.`,
`Privacy and security. Collect only fields needed for the stated decision, keep raw data in approved systems, use named accounts, and record access changes. The specialist should not decide that more data is convenient, that an identity discrepancy is harmless, or that an unusual request is routine. Escalation must preserve enough evidence for review without spreading sensitive content into new copies.`,
`Decision register. Create a versioned register naming the lane, unit, sources, required fields, permitted actions, stop conditions, owner decisions, response expectations, reviewers, thresholds, and removal trigger. Reconcile pilot records to the eligible source population and explain every unmatched item. The conclusion applies only to the studied workflow, system, permissions, policy, and period.`,
`Operational fairness. Evaluate the work lane rather than using a few errors or escalations as a proxy for an individual's ability or nationality. Give participants the same approved instructions, examples, access, owner coverage, and review rubric. Separate failures caused by unavailable evidence or delayed owner decisions from actions within the specialist's control. Safe refusal should not be scored as poor productivity.`,
`Change control. Version the instruction, access matrix, templates, field definitions, and acceptance thresholds. When a source, platform, policy, or owner decision changes, record what changed, why, who approved it, when it takes effect, and which open items need reassessment. Retire superseded copies and verify that search results, links, forms, and training point to the current version.`,
`Recovery test. Select at least one completed item and simulate the absence of the specialist, owner, or integration. Ask the designated backup to locate the record, understand its state, identify the next authorized step, and either complete or safely pause it without private context. Measure missing access, stale links, unclear ownership, and recovery time separately, then test timely access removal.`,
`Buyer conclusion. A defensible outsourced lane prepares reliable evidence and routine actions while keeping consequential judgment with the accountable owner. Before requesting a labor plan, the buyer should be able to name the queue, authoritative sources, permitted actions, stop conditions, owner coverage, review sample, and rollback path. Expand only when retained evidence supports that narrow decision.`,
]});
export const september23ResearchRecords=[
make({slug:'research-philippines-customer-account-change-identity-boundary',title:'Which identity checks belong before a Philippines-based specialist prepares a customer account change?',excerpt:'A decision study separating evidence gathering and draft preparation from identity acceptance and consequential account changes.',topic:'customer account-change preparation',unit:'one requested change to one customer account',evidence:'the request channel, claimed identity, approved verification evidence, account record, requested fields, risk flags, prior changes, prepared action, escalation, owner decision, and final state.',boundary:'Staff may gather approved evidence and prepare a reversible change; failed checks, security signals, sensitive fields, credential recovery, ownership disputes, and final high-consequence changes require authorized owners.',risks:'A familiar email address can be compromised, knowledge questions can expose data, copied documents can outlive their purpose, and urgency can bypass the approved verification path.',sources:[identity,nist,privacy],related:['research-aug17-access-scope-fit','research-outsourced-customer-escalation-evidence','research-outsourced-crm-data-stewardship-minimum-access']}),
make({slug:'research-outsourced-crm-duplicate-merge-decision-evidence',title:'What evidence should precede a CRM duplicate-merge decision in outsourced data stewardship?',excerpt:'A protocol for preparing likely duplicate records without delegating irreversible merges, consent interpretation, or record ownership.',topic:'CRM duplicate review',unit:'one proposed pair or cluster of CRM records',evidence:'record identifiers, source systems, creation times, normalized matching fields, consent and suppression fields, activity history, integration references, conflicts, proposed survivor, approval, merge log, and rollback evidence.',boundary:'Staff may identify candidates and document conflicts; ambiguous identity, consent differences, ownership disputes, bulk operations, deletion, and the final merge remain owner-controlled.',risks:'Shared names create false matches, integrations repopulate retired records, survivor rules erase fresher fields, and a merge can combine unrelated communication preferences.',sources:[privacy,nist,gao],related:['research-outsourced-crm-data-stewardship-minimum-access','research-aug13-record-lineage','research-outsourced-access-exception-expiry']}),
make({slug:'research-philippines-vendor-delivery-exception-follow-up',title:'How should a Philippines-based specialist prepare a vendor delivery exception for owner review?',excerpt:'Evidence and authority boundaries for late, partial, damaged, or conflicting vendor-delivery records.',topic:'vendor delivery-exception follow-up',unit:'one expected vendor delivery and its exception disposition',evidence:'purchase order, approved terms, promised date, shipment and receipt records, quantities, condition evidence, vendor messages, dependencies, operational impact, proposed follow-up, owner decision, and closure.',boundary:'Staff may reconcile records and send approved factual follow-ups; accepting substitutions, changing terms, asserting breach, approving credits, reprioritizing operations, and making payment decisions require owners.',risks:'Carrier scans can lag, partial receipts can be posted under another identifier, vendor language can be mistaken for an approved change, and a rushed follow-up can create an unintended commitment.',sources:[gao,nist,privacy],related:['research-philippines-procurement-follow-up-owner-readiness','research-outsourced-vendor-due-diligence-evidence-boundary','research-outsourced-invoice-preparation-duplicate-payment-controls']}),
make({slug:'research-outsourced-workforce-schedule-change-record',title:'What belongs in an outsourced workforce schedule-change record?',excerpt:'A study of schedule administration that preserves source facts, employee privacy, approval authority, and downstream time records.',topic:'workforce schedule-change preparation',unit:'one proposed or reported schedule change for one worker or defined group',evidence:'the request, requester authority, current schedule, applicable policy, effective interval, time zone, coverage impact, attendance or time-record dependencies, sensitive reason handling, approval, notifications, and final system state.',boundary:'Staff may check completeness and prepare an authorized update; accommodation, leave, pay, classification, discipline, privacy exceptions, staffing tradeoffs, and disputed time require appropriate owners.',risks:'Time-zone conversion can shift dates, a schedule system may not update timekeeping, private reasons can be copied unnecessarily, and retroactive edits can obscure the record that governed the work.',sources:[dol,privacy,gao],related:['research-philippines-remote-team-time-window-design','research-outsourced-time-zone-handoffs','research-aug14-continuity-dependency-map']}),
make({slug:'research-philippines-quality-audit-corrective-action-follow-up',title:'Can Philippines-based support track quality-audit corrective actions without owning acceptance?',excerpt:'A bounded method for evidence follow-up while process owners retain severity, remediation, risk, and closure decisions.',topic:'quality-audit corrective-action follow-up',unit:'one audit finding and its linked corrective-action record',evidence:'the finding, criterion, original evidence, accountable process owner, planned action, due date, status evidence, test method, reviewer result, exceptions, changes, acceptance decision, and closure time.',boundary:'Staff may maintain the register, request evidence, and prepare status summaries; severity, root cause, risk acceptance, remediation design, effectiveness judgment, deadline exceptions, and closure remain owner decisions.',risks:'Status labels can replace evidence, attachments can describe intent rather than completion, due-date changes can hide aging, and the same person can appear to prepare, test, and accept a correction.',sources:[gao,nist,privacy],related:['research-outsourced-review-sample-representativeness','research-workforce-operations-review-consistency-research','research-outsourced-small-batch-quality-signals']}),
] as const;
