type Source={name:string;publisher:string;url:string;checked:string};
const checked='2026-09-25',published=checked,image='/filipino-operations-specialist.svg';
const source=(name:string,publisher:string,url:string):Source=>({name,publisher,url,checked});
const nist=source('NIST Cybersecurity Framework 2.0','National Institute of Standards and Technology','https://www.nist.gov/cyberframework');
const privacy=source('NIST Privacy Framework','National Institute of Standards and Technology','https://www.nist.gov/privacy-framework');
const identity=source('NIST Digital Identity Guidelines','National Institute of Standards and Technology','https://pages.nist.gov/800-63-4/');
const gao=source('The Green Book: Standards for Internal Control in the Federal Government','U.S. Government Accountability Office','https://www.gao.gov/greenbook');
const ftc=source('Cybersecurity for Small Business','Federal Trade Commission','https://www.ftc.gov/business-guidance/small-businesses/cybersecurity');
type Input={slug:string;title:string;excerpt:string;question:string;unit:string;packet:string;boundary:string;failure:string;decision:string;sources:Source[];related:string[]};
const make=(p:Input)=>({...p,published,image,headlineStat:undefined as string|undefined,keyStats:undefined as string[]|undefined,takeaways:undefined as string[]|undefined,service:undefined as {heading:string;body:string;href:string;label:string}|undefined,faqs:undefined as {q:string;a:string}[]|undefined,cta:`Map a bounded ${p.decision} lane before delegating live work.`,body:[
`Decision context. ${p.title} This is an operating-design question, not a claim that location automatically improves or weakens performance. The buyer must decide whether a Philippines-based specialist can prepare reliable evidence and complete low-consequence steps while an accountable owner retains consequential judgment. The proposed lane should name its finish line, source systems, permitted actions, stop conditions, owner, backup, response window, and reversal path before live work begins.`,
`Research question. ${p.question} The unit of analysis is ${p.unit}. Define when a unit enters the eligible population, what makes it ready for review, which states count as waiting or returned, and what evidence closes it. Link reopened work to its original unit. Otherwise a team may report rework as fresh throughput and mistake a tidy queue for a reliable process.`,
`Source foundation. The cited NIST, GAO, and FTC materials provide authoritative concepts for governance, identity, privacy, security, and internal control. They do not endorse OutsourcedLabor.com, evaluate Filipino workers, prescribe this exact workflow, or prove a commercial result. The control design and niche conclusions below are analysis derived for this specific operating decision. Contracts, platform terms, sector rules, local law, and professional advice may require narrower boundaries.`,
`Evidence packet. Preserve ${p.packet} Each field needs an authoritative source, observation time, relevant version, and actor. Prefer stable record identifiers or approved exports to copied sensitive content. Keep conflicting evidence visible until a named owner resolves it, and retain the earlier state after a correction so an authorized reviewer can reconstruct what was known and when.`,
`Authority boundary. ${p.boundary} Maintain three explicit lists: actions the specialist may complete, actions the specialist may prepare but not execute, and conditions that require a stop. An escalation should identify the unit, missing or conflicting fact, decision required, accountable owner, business consequence, deadline, and safest reversible state.`,
`Intake design. Require a unique identifier, requester, received time, requested outcome, affected record, priority basis, and source links before work starts. Reject or park requests that arrive only through an unapproved message, cannot be matched to an authoritative record, or ask the specialist to infer identity or authority. A clear intake rule prevents urgency from silently expanding scope.`,
`Access design. Translate the written boundary into platform permissions. Test one permitted action, one blocked action, and one attempted route around the block. Roles may quietly include exports, bulk edits, deletion, integration management, impersonation, or inherited access. If a platform cannot express the intended separation, use preparation-only work, supervised temporary elevation, or a narrower queue instead of broad standing permission.`,
`Population design. Freeze the systems, channels, policy version, timezone, observation window, inclusion rules, and exclusions before measuring outcomes. Include completed, pending, returned, cancelled, escalated, overridden, and reopened units. Reviewing only clean completions hides the very exceptions that determine whether an outsourced lane is safe and useful.`,
`Sampling method. Review the full eligible population when practical. Otherwise select a reproducible ordinary sample before reviewers know outcomes and a separately labelled risk-shaped sample covering old, incomplete, sensitive, disputed, unusual, and high-consequence units. Report sample counts, exclusions, unavailable records, and deliberate oversampling. Do not present a risk sample as if it estimates the ordinary error rate.`,
`Measures. Report numerators and denominators for packet completeness, correct classification, boundary adherence, evidence recovery, owner response, rework, reopenings, and reviewer agreement. Separate active preparation time from source waiting, owner waiting, and system delay. Throughput alone can reward unsafe shortcuts; a blocked action or timely escalation can be the correct result.`,
`Review protocol. Give a second reviewer the packet and current instruction without revealing the first conclusion. Preserve both initial assessments. Classify disagreement as source authority, missing fact, identity, timing, policy interpretation, action consequence, or unclear instruction. The accountable owner resolves the case and changes future guidance prospectively rather than rewriting the record to manufacture agreement.`,
`Failure analysis. ${p.failure} Also test stale examples, partial exports, screenshots without system context, shared accounts, private-message approvals, silent bulk changes, copied personal data, and deadlines measured from the wrong event. Time-zone separation can expose weak owner coverage, but geography itself is not a diagnosis.`,
`Facts, analysis, inference, and uncertainty. System fields, timestamps, versions, messages, approvals, and observed actions are facts only to the extent their sources are authoritative and complete. Coding an exception and comparing patterns are analysis. Predicting that a changed control will improve an outcome is inference. State these layers separately and name important evidence that cannot be recovered.`,
`Decision rule. ${p.decision} should expand only when retained evidence meets predeclared thresholds for packet completeness, boundary adherence, owner response, correction quality, and reversibility. If evidence is missing at intake, repair intake. If complete packets wait, improve owner coverage. If reviewers disagree despite complete evidence, clarify policy or narrow scope. Do not answer a control problem by simply adding labor.`,
`Pilot sequence. Start with historical or reversible units, then use a small supervised live cohort. Freeze the instruction, template, permissions, owner roster, acceptance definition, and thresholds during the measurement period unless safety requires a change. Any material change begins a new study period rather than being blended into earlier outcomes. Record why the change occurred and which open units need reassessment.`,
`Privacy and security. Collect only fields needed for the decision, keep raw data in approved systems, use named accounts, and log access changes. The specialist should not decide that extra data is convenient, an identity discrepancy is harmless, or an unusual request is routine. Escalation must preserve enough evidence for review without spreading protected content into email, chat, or unmanaged copies.`,
`Continuity test. Select at least one completed unit and simulate the absence of the specialist, owner, or integration. Ask the designated backup to locate the record, understand its state, identify the next authorized action, and either complete or safely pause it without private context. Measure missing access, stale links, unclear ownership, and recovery time separately, then verify prompt access removal.`,
`Change control. Version the instruction, access matrix, templates, field definitions, approval roster, and acceptance thresholds. Record what changed, why, who approved it, when it takes effect, and which open work is affected. Retire superseded copies and verify that search results, saved links, forms, and training point to the current version.`,
`Operational fairness. Evaluate the work lane rather than treating a few errors or escalations as a proxy for an individual's ability or nationality. Give participants the same approved instructions, examples, access, owner coverage, and review rubric. Separate failures caused by unavailable evidence or delayed owner decisions from actions within the specialist's control. Safe refusal should not be scored as low productivity.`,
`Limitations. Exports may omit synchronization, deleted history, inherited permissions, offline work, private messages, or actions in another system. Timestamps can reflect later entry instead of the event. A short pilot can miss seasonality, absence, fraud, outages, and rare consequential cases. Reviewers may share the same mistaken interpretation. A complete record does not prove an unrecorded event never occurred.`,
`Buyer conclusion. A defensible outsourced lane prepares traceable evidence and routine, reversible work while consequential judgment remains with the accountable owner. Before requesting a staffing plan, the buyer should be able to name the unit, authoritative sources, required packet, permitted actions, stop conditions, response coverage, review method, thresholds, and rollback. The conclusion applies only to the studied workflow, systems, permissions, policy, and period.`
]});

export const september25ResearchRecords=[
make({slug:'research-philippines-workforce-schedule-coverage-gap-triage',title:'How should a Philippines-based scheduling specialist prepare a coverage-gap decision?',excerpt:'A decision-grade method for assembling availability, skills, leave, overtime, and service evidence while managers retain staffing authority.',question:'Can a scheduling specialist identify and prepare coverage-gap options without approving overtime, denying leave, changing staffing levels, or making employment decisions?',unit:'one uncovered or at-risk shift for one defined site, team, skill requirement, and service interval',packet:'the approved schedule version, staffing requirement, worker availability, approved leave, skill or certification record, rest and overtime flags, service priority, proposed options, worker communications, manager decision, release event, and change history.',boundary:'The specialist may reconcile availability, identify gaps, and draft options. Managers retain decisions about overtime, leave, assignment, discipline, accommodations, staffing levels, and publication.',failure:'Availability may be stale, a credential can expire between drafting and release, a proposed swap can create a different gap, and local dates can shift when schedules span time zones.',decision:'schedule coverage-gap preparation',sources:[gao,nist,privacy],related:['research-outsourced-workforce-schedule-change-record','research-outsourced-workforce-timesheet-correction-packet','research-outsourced-time-zone-handoffs']}),
make({slug:'research-outsourced-crm-record-export-approval-boundary',title:'What evidence should precede an outsourced CRM record export?',excerpt:'A bounded review framework for export purpose, requester authority, field minimization, destination, retention, and accountable approval.',question:'Can CRM support prepare an export request and minimized field set without deciding that the requester, purpose, destination, or disclosure is authorized?',unit:'one requested export of a defined CRM population to one named destination for one stated purpose',packet:'the request, requester identity and role, business purpose, population query, proposed fields, sensitivity classification, exclusions, destination, recipient, access method, retention period, approval, export audit event, transfer evidence, and deletion or expiry record.',boundary:'The specialist may validate completeness, preview counts, and propose field minimization. They must not approve disclosure, override consent or retention rules, choose an unapproved destination, or deliver the export without authorization.',failure:'Saved queries can expand after review, hidden columns can expose unnecessary data, a valid requester can name an unsafe destination, and downloaded copies can outlive CRM access removal.',decision:'CRM export-request preparation',sources:[privacy,nist,ftc],related:['research-outsourced-crm-data-stewardship-minimum-access','research-outsourced-crm-duplicate-merge-decision-evidence','research-outsourced-access-exception-expiry']}),
make({slug:'research-philippines-purchase-order-change-evidence',title:'Which checks belong before a Philippines-based specialist prepares a purchase-order change?',excerpt:'An evidence design for quantity, price, delivery, vendor, budget, and approval changes without transferring purchasing authority.',question:'Can procurement support assemble a complete purchase-order change packet while authorized owners retain supplier, budget, contractual, exception, and release decisions?',unit:'one proposed change to one purchase order version for one supplier and buying entity',packet:'the approved purchase order, change request, requester identity, supplier record, quote or contract reference, affected line items, price and quantity comparison, delivery impact, receipt and invoice status, budget reference, conflict flags, approvals, revised version, supplier notice, and system audit trail.',boundary:'The specialist may reconcile documents and draft a revised order. Supplier selection, commercial acceptance, budget commitment, policy exceptions, contract interpretation, final approval, and transmission remain with designated owners.',failure:'A supplier email may conflict with the contract, partial receipts can make quantity changes misleading, copied orders can retain obsolete bank or tax details, and revision numbers can diverge across systems.',decision:'purchase-order change preparation',sources:[gao,nist,ftc],related:['research-philippines-procurement-follow-up-owner-readiness','research-outsourced-vendor-due-diligence-evidence-boundary','research-philippines-vendor-bank-detail-change-verification']}),
make({slug:'research-outsourced-quality-inspection-sample-release',title:'How should outsourced quality support prepare an inspection-sample release decision?',excerpt:'A traceable sampling and evidence protocol that keeps specification, disposition, waiver, and release authority with quality owners.',question:'Can quality support select and document an approved inspection sample without interpreting specifications, waiving defects, or releasing affected work?',unit:'one inspection lot tied to one approved specification version, sampling instruction, and proposed disposition',packet:'the lot and item identifiers, eligible population, specification version, sampling instruction, selection record, instrument or observation evidence, defect classification, missing or conflicting facts, prior holds, proposed disposition, reviewer result, approval, release event, and downstream reconciliation.',boundary:'The specialist may assemble the population, apply a preapproved selection method, and record observations. Quality interpretation, defect acceptance, waiver, corrective action, disposition, and release remain accountable-owner decisions.',failure:'The sample frame may omit moved items, labels can outlive system status, reviewers can see earlier results and become biased, and a pass under one specification can be misapplied after a version change.',decision:'quality inspection-sample preparation',sources:[gao,nist,privacy],related:['research-philippines-quality-audit-corrective-action-follow-up','research-outsourced-acceptance-evidence-quality','research-philippines-inventory-quarantine-release-readiness']}),
make({slug:'research-philippines-order-refund-exception-packet',title:'What belongs in a Philippines-based order refund-exception packet?',excerpt:'A controlled workflow for order, payment, delivery, identity, policy, and communication evidence while owners retain refund authority.',question:'Can order support prepare a refund exception for prompt owner review without deciding customer identity, entitlement, fraud, amount, payment action, or policy waiver?',unit:'one refund request tied to one customer, order, payment event, stated reason, and proposed disposition',packet:'the original order, payment and fulfillment events, customer contact record, identity checks required by policy, delivery or return evidence, applicable refund-policy version, prior concessions, dispute or fraud signals, proposed amount and method, customer communication draft, owner decision, payment event, and closure notice.',boundary:'The specialist may reconcile records, classify the request under approved rules, and draft options. Identity exceptions, fraud conclusions, entitlement, amount, policy waiver, payment execution, and final customer commitment remain with authorized owners.',failure:'A customer thread can be compromised, partial fulfillment can distort the refundable amount, duplicate requests can exist in different channels, and a processor status can lag the underlying payment event.',decision:'refund-exception preparation',sources:[ftc,identity,gao],related:['research-philippines-order-delay-decision-boundary','research-outsourced-work-acceptance','research-philippines-support-escalation-signal-quality']})
] as const;
