type Source={name:string;publisher:string;url:string;checked:string};
const checked='2026-09-22',published=checked,image='/filipino-operations-specialist.svg';
const src=(name:string,publisher:string,url:string):Source=>({name,publisher,url,checked});
const nist=src('NIST Cybersecurity Framework 2.0','National Institute of Standards and Technology','https://www.nist.gov/cyberframework');
const privacy=src('NIST Privacy Framework','National Institute of Standards and Technology','https://www.nist.gov/privacy-framework');
const gao=src('Standards for Internal Control in the Federal Government','U.S. Government Accountability Office','https://www.gao.gov/products/gao-14-704g');
const payments=src('Streamlining the Payment Process While Maintaining Effective Internal Control','U.S. Government Accountability Office','https://www.gao.gov/assets/aimd-21.3.2.pdf');
const complaints=src('Solving Problems With a Business: Returns, Refunds, and Other Resolutions','Federal Trade Commission','https://consumer.ftc.gov/articles/solving-problems-business-returns-refunds-and-other-resolutions');
type P={slug:string;title:string;excerpt:string;topic:string;unit:string;evidence:string;boundary:string;risks:string;sources:Source[];related:string[]};
const make=(p:P)=>({...p,published,image,headlineStat:undefined as string|undefined,keyStats:undefined as string[]|undefined,takeaways:undefined as string[]|undefined,service:undefined as {heading:string;body:string;href:string;label:string}|undefined,faqs:undefined as {q:string;a:string}[]|undefined,cta:`Pilot one bounded ${p.topic} queue before expanding access.`,body:[
`Decision context. ${p.title} The decision is whether ${p.topic} can be separated into evidence gathering, preparation, owner judgment, and authorized action. Tool access is not decision authority. A buyer should name the exact finish line, accountable owner, backup, and safe pause before assigning work.`,
`Source foundation. The cited primary sources provide security, privacy, internal-control, payment, or consumer-record principles. They do not endorse OutsourcedLabor.com, evaluate Filipino workers, or prove savings or compliance. Applying them to this workflow is analysis. Contracts, platform terms, sector rules, and applicable law may require a different boundary.`,
`Method. Use ${p.unit} as the unit of analysis. Fix the systems, channels, time zone, policy version, observation period, inclusion rules, and exclusions before reviewing outcomes. Reopened items remain linked to their first record so rework cannot disappear from the denominator.`,
`Evidence. Preserve ${p.evidence} Record authoritative systems, observation times, versions, actors, approvals, and later corrections. Use stable references instead of copying sensitive content. Conflicting evidence stays visible until a named owner resolves it. Another reviewer must be able to reconstruct what was known without private chat.`,
`Boundary. ${p.boundary} Maintain separate lists for actions the specialist may complete, may prepare, and must escalate without change. Stop for missing authority, conflicting records, identity uncertainty, security concern, unusual value, deadline risk, or an out-of-scope request.`,
`Population. Review the full population when practical. Otherwise choose a reproducible sample before outcomes are known and retain the query or ordered identifiers. Include an ordinary random portion and a risk-shaped portion containing late, disputed, incomplete, reopened, sensitive, and overridden cases. Publish exclusions and missing records.`,
`Measures. Report numerators and denominators for complete evidence, correct classification, boundary adherence, owner response, rework, reopenings, and reviewer agreement. Separate preparation time from owner waiting and system delay. Throughput alone can reward shortcuts; escalation can be a correct controlled outcome.`,
`Independent review. Give a second reviewer the packet and rules without the first conclusion. Preserve initial scores. Categorize disagreement as source authority, missing fact, interpretation, identity, timing, or consequence. Resolve it through the owner and update instructions prospectively rather than rewriting history.`,
`Failure modes. ${p.risks} Further risks include stale instructions, screenshots without system context, shared credentials, copied personal data, approvals that cannot be recovered, and deadlines measured from the wrong event. Different working hours magnify missing owner coverage but are not themselves the cause.`,
`Interpretation. If inputs are usually missing, repair intake before adding labor. If packets are complete but wait, improve owner coverage. If reviewers disagree with complete evidence, clarify policy or narrow scope. If escapes cluster around one action, remove it from standing access.`,
`Limitations. Exports may omit synchronizations, deletions, inherited permissions, private messages, or actions in another channel. Historical cases may miss new products, seasonal pressure, absence, fraud, and policy changes. Reviewers can share the same mistaken interpretation. A clean record does not prove an event never occurred.`,
`Pilot design. Start with historical or reversible cases, then a small supervised live cohort. Freeze instructions and access during measurement unless safety requires change. Predeclare thresholds for evidence recovery, classification, boundary adherence, response, and reversal. Test access removal or rollback.`,
`Privacy and security. Minimize fields to the stated purpose, keep raw data in approved systems, use named accounts, and log access changes. The specialist should not decide that extra data is convenient or that a security anomaly is harmless. Escalation must preserve evidence without spreading it.`,
`Buyer conclusion. Create a versioned register naming the lane, unit, sources, fields, permitted actions, owner decisions, response targets, reviewers, thresholds, and removal trigger. Reconcile pilot rows to the source population and explain every unmatched item. Success supports only this studied lane, tool, and policy period.`,
`Implementation record. For every item retain identifiers, timestamps, source references, classification, prepared action, escalation, owner decision, outcome, rework, and review result. Record limitations and unresolved cases. Expand only through a deliberate owner approval supported by retained evidence.`,
`Decision cadence. Review exceptions at a fixed interval appropriate to their consequence and deadline. The owner should distinguish a missing fact from a judgment call, respond in the shared record, and state whether the answer applies only to this item or changes the standing rule. Trend recurring exceptions by cause without treating frequency as proof of importance. Retire temporary workarounds after the underlying source, permission, or instruction is repaired. At the end of the pilot, publish the unresolved population and the exact recovery action for each item rather than declaring the queue clean because ordinary work was completed.`,
]});
export const september22ResearchRecords=[
make({slug:'research-philippines-shared-inbox-delegation-boundary',title:'How should a shared inbox be delegated to a Philippines-based specialist?',excerpt:'A study separating triage and drafting from security, customer-promise, and policy decisions.',topic:'shared-inbox triage and draft preparation',unit:'one inbound thread and its disposition',evidence:'the message, sender context, thread, category, instruction version, linked record, draft, escalation, approval, and response.',boundary:'Staff may classify and draft from approved facts; identity changes, security events, refunds, threats, commitments, and novel exceptions require owners.',risks:'Thread splitting hides context, display names impersonate senders, forwards detach evidence, and drafts can promise unauthorized outcomes.',sources:[nist,gao,privacy],related:['research-outsourced-labor-communication-reliability','research-aug17-access-scope-fit','research-outsourced-customer-escalation-evidence']}),
make({slug:'research-outsourced-invoice-preparation-duplicate-payment-controls',title:'Which duplicate-payment controls belong in an outsourced invoice-preparation lane?',excerpt:'Controls for invoice packets without vendor, bank, approval, or payment authority.',topic:'invoice intake and duplicate screening',unit:'one invoice submission tied to a vendor and obligation',evidence:'the invoice, channel, vendor ID, authorization, receipt, normalized number, amount, currency, prior search, exception, and decision.',boundary:'Staff may normalize and flag; vendor creation, bank changes, accounting judgment, exceptions, approval, and payment remain owner actions.',risks:'Exact matching misses altered numbers, copies look original, recurring bills resemble duplicates, and urgency defeats verification.',sources:[payments,gao,nist],related:['research-outsourced-procurement-evidence','research-philippines-procurement-follow-up-owner-readiness','research-outsourced-vendor-due-diligence-evidence-boundary']}),
make({slug:'research-philippines-customer-complaint-evidence-packet',title:'What belongs in a customer-complaint evidence packet prepared from the Philippines?',excerpt:'A protocol for complaint facts without delegating findings, admissions, refunds, or legal responses.',topic:'complaint evidence preparation',unit:'one complaint about a defined transaction or service event',evidence:'the statement, requested remedy, transaction, policy, prior contacts, promises, times, attachments, disputed facts, deadline, owner, and response.',boundary:'Staff may build neutral chronologies; fault, legal characterization, admissions, discretionary remedies, and promises require owners.',risks:'Summaries flatten customer words, omit promises, treat silence as agreement, expose excess data, or present allegations as facts.',sources:[complaints,gao,privacy],related:['research-outsourced-customer-escalation-evidence','research-philippines-order-delay-decision-boundary','research-aug14-customer-record-freshness']}),
make({slug:'research-outsourced-knowledge-base-change-approval',title:'When can an outsourced specialist prepare knowledge-base changes without publishing them?',excerpt:'Versioned change control preserving policy interpretation and release authority.',topic:'knowledge-base change preparation',unit:'one material change to one canonical knowledge item',evidence:'the request, current version, source, proposed text, affected workflows, links, preview, comments, approval, publication time, version, and rollback.',boundary:'Staff may prepare sourced drafts; novel policy, legal or security instructions, removed warnings, unsupported claims, and publication require owners.',risks:'Correct sentences can be wrong in context, previews expose data, renames break links, and parallel copies preserve retired instructions.',sources:[nist,gao,privacy],related:['research-knowledge-transfer-checklist','research-sop-version-control','research-outsourced-labor-instruction-freshness']}),
make({slug:'research-philippines-calendar-scheduling-minimum-access',title:'What is the minimum calendar access for Philippines-based scheduling support?',excerpt:'A field-and-action study for scheduling without unnecessary exposure or commitment authority.',topic:'calendar option preparation',unit:'one scheduling request and its proposed or approved event',evidence:'the requester, identity, purpose, attendees, duration, time zones, windows, privacy label, conflicts, options, selection, invitation, and changes.',boundary:'Staff may prepare options; private events, priority tradeoffs, sensitive attendees, travel, contractual meetings, overrides, and unclear identities require owners.',risks:'Free-busy reveals patterns, descriptions expose information, time-zone assumptions move meetings, and acceptance can imply authority.',sources:[privacy,nist,gao],related:['research-aug17-access-scope-fit','research-outsourced-access-removal-lag','research-philippines-remote-team-time-window-design']}),
] as const;
