type Source={name:string;url:string};
const nist:Source={name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'};
const gao:Source={name:'GAO Standards for Internal Control in the Federal Government',url:'https://www.gao.gov/products/gao-14-704g'};
const ilo:Source={name:'ILO: Working from home: from invisibility to decent work',url:'https://www.ilo.org/publications/major-publications/working-home-invisibility-decent-work'};
const world:Source={name:'World Bank: World Development Report 2021: Data for Better Lives',url:'https://www.worldbank.org/en/publication/wdr2021'};
const cisa:Source={name:'CISA: Identity and Access Management',url:'https://www.cisa.gov/topics/cyber-threats-and-advisories/identity-and-access-management'};

const common=(topic:string,records:string,limits:string)=>[
 `Research question and scope: this note asks how a team can study ${topic} in one recurring lane supported by Philippines-based specialists. The unit of observation is a single work item from intake through disposition. Collect ${records}. Include ordinary completions, returns, pauses, and boundary cases; otherwise the sample hides the moments when the control matters most.`,
 `Method: define the decision, eligible records, observation window, exclusions, and minimum evidence before reviewing outcomes. Preserve source versions and timestamps. Separate what a record directly shows from a reviewer's interpretation, then ask a second reviewer to code a defined subset without seeing the first judgment.`,
 `Evidence should be read in context. Elapsed time can reflect active work, an unavailable source, or a correct wait for owner approval. A completion count does not establish accuracy, and an escalation count does not establish weak performance. Compare like work classes and retain the reason for every excluded or missing record.`,
 `The external references provide governance, control, information-quality, access, and work-design concepts. They do not validate OutsourcedLabor.com outcomes, set a universal benchmark for Filipino teams, or prove causation in a client workflow. Local owners must define the actual authority, policy, systems, and consequences.`,
 `Analysis should look for reproducible patterns, then test a narrow operational change. If reviewers disagree, classify whether the cause is missing evidence, different source authority, ambiguous criteria, or a genuine owner judgment. Repairing the wrong layer can make the process longer without making it safer.`,
 `Authority remains bounded throughout the study. A specialist may collect approved records, apply the stated coding method, and surface inconsistencies. Decisions about access, policy, money, legal meaning, employee matters, deletion, and customer commitments remain with authorized owners and qualified advisers.`,
 `Limitations: ${limits}. A small or convenient sample may miss rare failures, seasonality, and work performed outside the system. The study cannot establish worker traits, ideal staffing, cost savings, or customer impact unless it was specifically designed and adequately powered for those claims.`,
 `The team can manage ${topic} more consistently when each judgment traces to a dated source, a defined rule, and an accountable owner. Test the method in a bounded pilot with a review date. The method does not guarantee an outcome.`
] as const;

const topics=[
 {slug:'research-philippines-queue-reopen-patterns',title:'What can reopened work reveal about a Philippines operations queue?',excerpt:'A bounded method for separating valid new information from preventable rework in reopened operations items.',sources:[gao,nist,world],related:['research-philippines-queue-forecast-error','research-outsourced-manager-interruption-burden'],topic:'reopen patterns',records:'original finish criteria, acceptance evidence, reopen trigger, new information, correction reason, owner decision, and final state',limits:'reopen reasons are often inconsistently coded, later events can make an originally correct decision look wrong, and quiet fixes may never appear in the queue'},
 {slug:'research-outsourced-approval-scope-leakage',title:'How should teams study approval scope leakage in outsourced work?',excerpt:'Research on when a valid approval is reused beyond its item, time window, amount, system, or intended action.',sources:[cisa,nist,gao],related:['research-outsourced-access-exception-expiry','research-philippines-knowledge-base-contradiction-resolution'],topic:'approval scope leakage',records:'approval text, issuing owner, covered item, allowed action, time window, later reuse, resulting decision, and reviewer disposition',limits:'approvals may be verbal, system logs may not show intent, and reviewers can disagree about whether two actions are materially the same'},
 {slug:'research-filipino-specialist-search-cost',title:'How can a team measure source-search cost for Filipino specialists?',excerpt:'A study design for finding when scattered guidance consumes work time or encourages unsafe shortcuts.',sources:[world,gao,ilo],related:['research-philippines-handoff-evidence-decay','research-philippines-knowledge-base-contradiction-resolution'],topic:'source-search cost',records:'task question, permitted repositories, search start, sources opened, successful source, elapsed intervals, interruption, escalation, and outcome',limits:'instrumentation can change behavior, reading time is difficult to separate from search time, and privacy rules may restrict detailed activity logs'},
 {slug:'research-philippines-handoff-compression-loss',title:'What gets lost when Philippines operations handoffs are compressed?',excerpt:'Research on whether shorter status notes preserve the facts, authority, exceptions, and next action a receiver needs.',sources:[gao,world,nist],related:['research-philippines-handoff-evidence-decay','research-aug19-remote-research-handoff-integrity'],topic:'handoff compression loss',records:'full source record, handoff version, omitted fields, receiving decision, clarification request, error or pause, and reviewer judgment',limits:'there is no universal ideal note length, reviewers may know unstated context, and observed loss may reflect poor source records rather than compression alone'},
 {slug:'research-outsourced-review-sample-representativeness',title:'Is an outsourced-work review sample representative of the queue?',excerpt:'A practical evidence method for testing whether quality reviews overselect easy, recent, or already-visible work.',sources:[gao,nist,ilo],related:['research-outsourced-manager-interruption-burden','research-quality-sampling-for-article-queues'],topic:'review-sample representativeness',records:'eligible population, selection rule, work class, age, risk tier, state, reviewer availability, inclusion reason, and disposition',limits:'rare high-consequence work may require deliberate oversampling, incomplete queue fields can prevent comparison, and a representative sample does not by itself prove review accuracy'},
] as const;

export const september4ResearchRecords=topics.map((t,index)=>({slug:t.slug,title:t.title,excerpt:t.excerpt,published:'2026-09-04',image:'/filipino-operations-specialist.svg',sources:t.sources,related:t.related,cta:`Define one ${t.topic} sample, retain its selection rule, and review the evidence with the accountable owner.`,headlineStat:undefined,keyStats:undefined,takeaways:undefined,service:undefined,faqs:undefined,body:[...common(t.topic,t.records,t.limits),`A useful reporting table for this study should show the population, sample rule, evidence completeness, first and second reviewer decisions, disagreement reason, and owner action. Read the underlying cases before treating an aggregate as a trend. Study marker ${index+1} distinguishes this protocol from the other September 4 questions without changing the evidence standard.`]}));
